### ISSUE TITLE
Using generateImages_browserless.js without Node.js

### ISSUE THREAD

**Issue by mt633** [opensheetmusicdisplay/opensheetmusicdisplay#1055]
I'm trying to figure out if there could be a way to generate images in other JavaScript engines than Node.js using the `generateImages_browserless.js` method. At the moment I'm trying it in QuickJS but I'm a novice in this area so I am currently stuck.

I've been trying to include jsdom when building OSMD but it says it won't find some methods. I also gave it a try with [linkedom](https://github.com/WebReflection/linkedom) but didn't get any further.

Correct me if I'm wrong, but I'm starting to suspect that both are using modules that cannot be exported to plain JavaScript. Might there be a way around it?

If anyone has any pointers here I'd appreciate it!

**Comment by sschmidTU** [comment]
Why don't you want to use NodeJS, if you just need to generate pngs/svgs?
What methods are not found?
What modules can't be exported to plain JavaScript?
It seems like you need some adjustments to replace Nodejs. What the script does is add any DOM methods that are missing in NodeJS (like Canvas), so this may differ for other JS engines.
I'm afraid this may be quite complex to implement, because as you can see in `generateImages_browserless`, it has been quite complex for NodeJS too.
I'm also not experienced in these other JS engines, so I'm afraid I won't be able to help much here.

**Comment by mt633** [comment]
OK, thanks for the feedback. I'm trying to implement OSMD in app development and using a webview doesn't feel like the quickest way to do it, so thought it would be nice if the images could be user-side generated. I also figured that the less commanding engine the better and QuickJS looked like a good option. But I feel like I'm a bit over my head when I'm trying to solve this, so unless someone else have any experience here I'll just go for the webview option.

**Comment by sschmidTU** [comment]
You can always use a Webview. But have you thought about NodeJS for Mobile?
https://code.janeasystems.com/nodejs-mobile
(Also, you could build a nodejs server that creates/serves the images for you)

**Comment by mt633** [comment]
No, haven't look at that yet. Looks like it could be a good option! Sure, a server solution might work, but I'd prefer the offline support.

Thanks for the help! Feel free to close this issue if you want to.
