### ISSUE TITLE
Bug in commit 5686daa

### ISSUE THREAD

**Issue by rvilarl** [opensheetmusicdisplay/opensheetmusicdisplay#1112]
In commit 5686daa there is a bug
```
ERROR in ./src/MusicalScore/Graphical/VexFlow/SvgVexFlowBackend.ts
./src/MusicalScore/Graphical/VexFlow/SvgVexFlowBackend.ts 188:36-47
[tsl] ERROR in ./src/MusicalScore/Graphical/VexFlow/SvgVexFlowBackend.ts(188,37)
      TS2554: Expected 1-3 arguments, but got 0.
```
`ctx.openGroup()` cannot be called with 0 parameters.

**Comment by sschmidTU** [comment]
No. openGroup() doesn't have parameters in Vexflow 1.2.93, at least not according to our interface.

**Comment by sschmidTU** [comment]
It's also in other existing methods in SvgVexFlowBackend.

**Comment by sschmidTU** [comment]
It also works without issues.

**Comment by rvilarl** [comment]
https://github.com/0xfe/vexflow/blob/430f607053f7caa24cb96feac722c1b5fb821b06/src/svgcontext.js#L96

Now that you remind me I had to place `// @ts-ignore` in front of all of them in #1094

It would be good to fix them, I believe.

**Comment by sschmidTU** [comment]
@rvilarl Fixing this by updating the definitions in DefinitelyTyped (only relevant for Vexflow 1.2.93 or 3.0.9).
The definitions for `openGroup()` were missing the parameters:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/29216607f433cbb900acdcf4a0e4ea69e9db5376/types/vexflow/index.d.ts#L74

I've submitted a PR to DefinitelyTyped:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58042

Hopefully I'll soon be able to merge it, as I'm listed as an owner on DefinitelyTyped, otherwise I'll have to ask someone for a PR review.

**Comment by sschmidTU** [comment]
@rvilarl the PR is merged. Though now that I look at it, the ts-ignore shouldn't have been necessary from the DefinitelyTyped definitions, because `openGroup()` didn't have any parameters there before (now they're optional).
We can also just call `openGroup(undefined)` or just give a class, like `openGroup("text")` in `renderText()`.

**Comment by rvilarl** [comment]
you are right, the error is in VexFlow, sorry for that. The first string is checked not to be undefined. I will fix that in VexFlow and you can undo this one if you want.

**Comment by sschmidTU** [comment]
No problem! Having class names in the SVG is nice anyways, so I added them.
