### ISSUE TITLE
feature request in setOptions

### ISSUE THREAD

**Issue by scoresmexico** [opensheetmusicdisplay/opensheetmusicdisplay#1135]
Hello,
Perhaps I don't know how to do this.

Is there an option for **not** displaying key signatures and clefs?

A feature that would be nice for notation extraction could be drawFromBeatNumber and drawUpToBeatNumber.

Thank you, I'll always say its an awesome library
Best

**Comment by sschmidTU** [comment]
Hi, there are no such options yet.
Although when using the SVG backend, you could just remove all (child) elements of class `vf-keysignature` and `vf-clef` from the SVG node:
![image](https://user-images.githubusercontent.com/33069673/151595704-20b1682b-32c2-4722-b7a5-0314117cec9f.png)

We could add these options in the future, it would be quite easy to not add these in `MusicSystemBuilder.AddInstructionsAtMeasureBegin()` when the options are set.

`drawFrom/UpToBeatNumber` might be a little tricky, because it could make vexflow voices incomplete (so vexflow will complain), but you could maybe just make the other notes transparent.

**Comment by sschmidTU** [comment]
Actually `osmd.EngravingRules.RenderKeySignatures` already existed, so I just added `RenderClefsAtBeginningOfStaffline`.
![image](https://user-images.githubusercontent.com/33069673/151598226-15641dd7-e7ed-4447-a45e-6a8da8e17f7c.png)

**Comment by sschmidTU** [comment]
You could implement your beat number options yourself by deleting SVG nodes or making them transparent depending on the timestamp, which you can get from the cursor (go through the score, make all notes up to or after a timestamp transparent by getting the SVG node of a GraphicalNode, going through its children, setting fillStyle, etc.)

**Comment by scoresmexico** [comment]
How can I call `osmd.EngravingRules.RenderKeySignatures` within Javascript?

Like this?
```
osmd.EngravingRules({ 
     renderKeySignatures: false
})
```

**Comment by sschmidTU** [comment]
No, like this:
`osmd.EngravingRules.RenderKeySignatures = false;`
EngravingRules is an existing object.

**Comment by scoresmexico** [comment]
Thank you @sschmidTU
Everything worked fine
```
osmd.EngravingRules.RenderKeySignatures = false;
osmd.EngravingRules.RenderClefsAtBeginningOfStaffline = false;
```
