### ISSUE TITLE
Incorrect location of lyrics after MusicXML parsing with lyrics

### ISSUE THREAD

**Issue by nyhxiaoning** [opensheetmusicdisplay/opensheetmusicdisplay#1152]
Incorrect location of lyrics after MusicXML parsing with lyrics
![image](https://user-images.githubusercontent.com/34833782/155709499-3ac0da61-13fd-4bb6-a205-06eeb956e6fa.png)
The correct museScore is shown below
![Uploading Snipaste_2022-02-25_19-45-13.jpg…]()

**Comment by nyhxiaoning** [comment]
The correct museScore is shown below
![Snipaste_2022-02-25_19-45-13](https://user-images.githubusercontent.com/34833782/155710119-fc48ed88-9d5f-42d3-b6f9-6ffc30a0750e.jpg)

**Comment by nyhxiaoning** [comment]
@matt-uib 
Could you please tell me why this lyric is wrong after parsing, thank you

**Comment by sschmidTU** [comment]
@nyhxiaoning Please share the musicxml sample, otherwise it's impossible to tell. You can rename it to .txt or zip it.
I'm guessing that the lyrics are incorrectly written or exported to MusicXML. It looks to me like there are multiple characters on a single note, and OSMD can't fit 10 characters on a single note.

**Comment by nyhxiaoning** [comment]
this is my file ,
[twotiger (2).zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/8140920/twotiger.2.zip)


please see it ,thanks and you  @sschmidTU

**Comment by nyhxiaoning** [comment]
thank very much. 
You've been a great help.

**Comment by nyhxiaoning** [comment]
@sschmidTU thank you

**Comment by sschmidTU** [comment]
@nyhxiaoning Were you able to change the sample so that it displays better?
I checked and there were indeed many words on a single note, which is not how lyrics are supposed to be used usually.
<img width="389" alt="image" src="https://user-images.githubusercontent.com/33069673/155715473-f431323d-f3ea-400b-9c81-31807579358c.png">
I believe in Musescore you can press the space bar when entering lyrics to go to the next note.

**Comment by nyhxiaoning** [comment]
As you say, the absence can show better,thank you 
![image](https://user-images.githubusercontent.com/34833782/155715889-8107b369-ff74-40a3-bfd3-36e7a5dbd3b9.png)
@sschmidTU
