### ISSUE TITLE
Rendering error when resizing during render()

### ISSUE THREAD

**Issue by showtan001** [opensheetmusicdisplay/opensheetmusicdisplay#1206]
`start index of line is greater than the end index`
This error occurs when the size of the rendering area is changed during browser rendering. And mobile phone rendering also has this error, I think it is similar to #373, is there any good solution?

![image](https://user-images.githubusercontent.com/32892347/184117689-51d48a85-784d-4fdb-8961-2a824505d6e1.png)

**Comment by JanVeb** [comment]
Do you really have to resize osmd during rendering?
you could easily set desired osmd zoom before calling rendering

```
osmd.zoom = 2
osmd.render();
```

Also instead of resizing osmd you could resize its parent div:
```
transformOrigin: '0% 0% 0px',
transform: osmdSizeTrans,
```
This way resizing is almost instant and you don't have to call `osmd.render();` afterwards. Just keep in mind that osmdSizeTrans has to be state variable in order to update ui when it changes. Also afterwards if you need osmd width for example, you get it by multiplying osmd width with osmdSizeTrans

```
let scaleScoreWidth = document.getElementById('osmdSvgPage1').width.animVal.valueInSpecifiedUnits
  setScoreWidth(scaleScoreWidth * osmdSizeTrans)
```
etc


https://user-images.githubusercontent.com/93236084/187059594-c729a984-78f3-403c-a5ca-b766bb7c3f32.mp4

**Comment by showtan001** [comment]
@JanVeb This is only part of the xml, you can look at #1213

**Comment by JanVeb** [comment]
File "/Users/name/Downloads/2f48085f69174525ead3f6b4321e622c.musicxml" corrupted
Cant load it to Musescore, getting this error that file is corrupted.

It loads to OMSD demo and plays as well, though it doesn't show on screen.
Cant load it to my project:
OSMD loading ERROR occured... Error: OpenSheetMusicDisplay: The document which was provided is invalid
    at opensheetmusicdisplay.min.js:2:1

Seems this particular score is corrupted.

**Comment by showtan001** [comment]
@JanVeb   Use the link directly
https://hi-virtual.oss-cn-chengdu.aliyuncs.com/file/20220810/f05ab38c3d6e40e2339c80d03471168c.xml is the same for this xml

**Comment by JanVeb** [comment]
Im sorry I don't really understand your issue, was thinking that if your issue is rendering error when resizing during rendering, this could be easily solved by not resizing osmd during rendering but rather before it, think this is also proper way to do this.

Otherwise could I just ask you whats the name of this score?

**Comment by sschmidTU** [comment]
Yes, ideally OSMD should not be resized during rendering.
