### ISSUE TITLE
Notes crowded together

### ISSUE THREAD

**Issue by yogaliu** [opensheetmusicdisplay/opensheetmusicdisplay#1220]
Notes crowded together on the phone

![image](https://user-images.githubusercontent.com/15954570/187629957-a4b06b17-e6a6-4ec1-91fe-785f247cdbd1.png)

how can i fix it

[Chopin_-_Heroic_Polonaise_Op._53.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/9459851/Chopin_-_Heroic_Polonaise_Op._53.musicxml.zip)

**Comment by JanVeb** [comment]
On my phone and chrome it looks good but only when `renderSingleHorizontalStaffline: true`, otherwise when `renderSingleHorizontalStaffline: false`, score is not rendered on the screen, just to be sure, as its little hard to read, is this measure 168?

And with these OSMDOptions
```
  const OSMDoptions = {
    drawComposer: false,
    drawCredits: false,
    drawTitle: false,
    drawSubtitle: false,
    drawLyricist: false,
    drawFingerings: true,
    coloringEnabled: true,
    coloringMode: 0,
    renderSingleHorizontalStaffline: true,
    autoResize: true,
    followCursor: true,
    disableCursor: false,
    measureNumberInterval: 1,
    drawingParameters: 'compacttight',
    drawMetronomeMarks: true,
    drawMeasureNumbers: true,
    defaultColorRest: 'white',
    defaultColorMusic: black,
    backend: 'svg',
  };
```
everything seems good

And with these OSMDOtions
```
  const OSMDoptions = {
    coloringMode: 0,
    renderSingleHorizontalStaffline: true,
  };
```
it will load just 99 measures, moving cursor to selected measure even when measure is < 99 is not working

Simon might have some idea about whats going on.

Chrome
![Screen Shot 2022-08-31 at 8 47 08 PM](https://user-images.githubusercontent.com/93236084/187682731-f7a2173d-0e85-401c-9977-d99963156785.png)

Error I get when `renderSingleHorizontalStaffline: false` or is outcomented
![Screen Shot 2022-08-31 at 9 20 48 PM](https://user-images.githubusercontent.com/93236084/187688579-73544131-af08-4262-88c1-aca1dd1f48d4.png)

**Comment by JanVeb** [comment]
Skybottomline
Found two mentions about this, one that might relate to this issue, has little info and is only stated that it was fixed

Mobile screen
![Screenshot_20220831-205024419](https://user-images.githubusercontent.com/93236084/187691799-696bbe70-3ed6-43e3-91b4-b8cf24c831dc.png)

From error it seems that there is an issue with file data, but it seems it's rather an issue within OSMD

**Comment by sschmidTU** [comment]
The likely issue is that the width is just too small and the zoom too big for this score.
If you give a measure much less space than it needs, vexflow can't handle that and puts notes on top of each other.

In your case I would reduce the zoom (osmd.Zoom), increase the OSMD draw area (container width), or use landscape mode.

**Comment by JanVeb** [comment]
One more note I forgot to mention, Musescore loads the file and it seems it works good from my quick fly over it

**Comment by JanVeb** [comment]
OSMD Demo
![Screen Shot 2022-08-31 at 10 13 43 PM](https://user-images.githubusercontent.com/93236084/187700193-5b541733-affd-4a27-a794-0a66ce301020.png)

In Osmd demo it loads this score without issues as far as I can notice, so this is not osmd issue but rather issue with your code, Im sorry I didn't check that first, while I immediately loaded score to osmd demo I forgot to check it up while checking it up in my project.

So I guess there's some issue with my code as I don't pay much attention to multiline rendering eg. `renderSingleHorizontalStaffline: false, `

If Simon answer didn't help you, try and see if copying osmdOptions from osmd demo index.js helps you out

```
  const OSMDoptions = {
   minMeasureToDrawStashed: 1,
    maxMeasureToDrawStashed: Number.MAX_SAFE_INTEGER,
    measureToDrawRangeNeedsReset: false,
    drawingParametersStashed: 'default',
    drawingParametersNeedsReset: false,
    autobeamOptionNeedsReset: false,
    autobeamOptionStashedValue: false,
    autoCustomColoringOptionNeedsReset: false,
    autoCustomColoringOptionStashedValue: false,
    drawPartNamesOptionStashedValue: true,
    drawPartAbbreviationsStashedValue: true,
    drawPartNamesOptionNeedsReset: false,
    pageBreaksOptionStashedValue: false,
    pageBreaksOptionNeedsReset: false,
    systemBreaksOptionStashedValue: false, // reset handled by pageBreaksOptionNeedsReset

    showControls: true,
    showExportPdfControl: false,
    showPageFormatControl: false,
    showZoomControl: true,
    showHeader: true,
    showDebugControls: false,
}
```

It didn't help with my issue, but as well, your issue is different than mine.

**Comment by yogaliu** [comment]
> The likely issue is that the width is just too small and the zoom too big for this score. If you give a measure much less space than it needs, vexflow can't handle that and puts notes on top of each other. Also, this is a very complex score. The more complex the score and the smaller the draw area, the more likely there will be errors.
> 
> In your case I would reduce the zoom (osmd.Zoom), increase the OSMD draw area (container width), or force landscape orientation on the user.

It looks good if there is enough width to display, unfortunately we can't control which zoom level the user uses

**Comment by JanVeb** [comment]
osmd.zoom = 0.3;

![Screen Shot 2022-09-01 at 5 12 28 PM](https://user-images.githubusercontent.com/93236084/187878019-13133dca-6aa4-4ff1-be3d-f4491d8e553e.png)

For me it looks good even with osmd.zoom = 0.3;

Don't think think this is your issue

**Comment by JanVeb** [comment]
Maybe it would help if you enable:
`overflow-y: auto;` or
`overflow-y: scroll;`

osmd.zoom = 2;
![Screen Shot 2022-09-01 at 7 41 20 PM](https://user-images.githubusercontent.com/93236084/187905636-e9c0b702-88e2-4030-8115-5e4ecb660551.png)

**Comment by sschmidTU** [comment]
test
