### ISSUE TITLE
MacOS build issues with npm / node-gyp / node-pre-gyp

### ISSUE THREAD

**Issue by sschmidTU** [opensheetmusicdisplay/opensheetmusicdisplay#1239]
MacOS can fail the build on some machines, the current workaround is using node 14.
This is described in more detail [here in the wiki](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Build-Instructions#2-get-source-code-and-install-modules) (expand the section), or [here (start of discussion)](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/pull/1158#issuecomment-1083404387), but it's good to have an issue for it, and hopefully we can fully eliminate this issue at some point.
Strangely, Linux and Windows never have this issue.

Recent screenshot, courtesy of playthatsheet:
![image](https://user-images.githubusercontent.com/33069673/192511592-9ce64eb3-8844-412b-92ea-cceb194db8c7.png)

- [X] Added a .nvmrc to indicate node v14 use for MacOS. Can be used with `nvm use` in the project root.

**Comment by JanVeb** [comment]
Does this help with issue that OSMD is not running on local host on Safari and neither on iOS as mobile version for IOS is based on safari rather than chrome.

Also was looking to reinstall node 14 but have issues
when I run ` npm install -g node@14.9.1`, it says:
`npm ERR! code ETARGET
npm ERR! notarget No matching version found for node@14.9.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.`

You know some simple to follow guide how to instal node 14? Do I have to uninstall current node version or it will get uninstalled once version 14 is being installed?

**Comment by sschmidTU** [comment]
This has nothing to do with Safari, it's just a build issue, not an issue for npm start.
You need to install a different node version with nvm. e.g. nvm install v14, or nvm use, now that we have a .nvmrc.

**Comment by JanVeb** [comment]
Thank, figured out my issue, issue was mobile devices related packages, on Chrome it will still load the app with them, but not on Safari. Though I have code for checking devices and enabling/disabling packages that was working before but now it doesn't, need to check this out, for now I manually disable these packages for web

**Comment by sschmidTU** [comment]
This seems to have been fixed in the gl library around 2 weeks after this issue was created:
https://github.com/stackgl/headless-gl/releases/tag/v6.0.1
adding support for node v18.

See also #1433

gl library dependency bumped to 6.0.2.

**Comment by sschmidTU** [comment]
One recent 3rd party [build error](https://discord.com/channels/796778104419909732/796796488331427841/1298781140546748519) was solved by these [node-canvas instructions in their readme](https://github.com/Automattic/node-canvas?tab=readme-ov-file#compiling):
```sh
brew install pkg-config cairo pango libpng jpeg giflib librsvg pixman python-setuptools
```
(node 20 was used)

---

Also, if there are errors with minimatch, try the 2 different fixes from here onwards:
https://github.com/strapi/strapi/issues/23859#issuecomment-3031237511
