### ISSUE TITLE
Proper way of implementing transposition

### ISSUE THREAD

**Issue by ljfreelancer88** [opensheetmusicdisplay/opensheetmusicdisplay#1240]
I'm trying to transpose a tablature with notation but it's not working. I'm not sure if I did follow the wiki correctly.

Here's the code that I used.
```javascript
let openSheetMusicDisplay = new opensheetmusicdisplay.OpenSheetMusicDisplay("osmdContainer");
openSheetMusicDisplay.setOptions({
  backend: "svg",
  drawTitle: true,
  drawingParameters: "compacttight" // don't display title, composer etc., smaller margins
});

openSheetMusicDisplay
  .load("$score")
  .then(function() {
    openSheetMusicDisplay.Sheet.Instruments[0].Transpose = 1
    openSheetMusicDisplay.updateGraphic();
    openSheetMusicDisplay.render()
  });
```
Thank you in advance.

**Comment by JanVeb** [comment]
Hi there, welcome to the OSMD community.

I'm not really sure what's wrong, Simon later might help you more, though also more data would be helpful, what kind of errors are you getting?
How do you import OSMD to your project?

Maybe better replace 
`let openSheetMusicDisplay = new opensheetmusicdisplay.OpenSheetMusicDisplay("osmdContainer");`
with `let osmd = new opensheetmusicdisplay.OpenSheetMusicDisplay("osmdContainer");`
and of course any further openSheetMusicDisplay with osmd.
it's easier to read, especially as you are probably going to reuse openSheetMusicDisplay many times in your code.

You could also add 
window.osmd = osmd;
to your code, then in console you could in console run window.osmd, if you get something along these lines, then at least you know score was loaded
 "P {version: '1.5.0-audio-extended', cursorsOptions: Array(1), cursors: Array(1), zoom: 1, zoomUpdated: false, …}"

Otherwise its hard to know like this what's an issue, maybe your path to score is wrong, maybe osmd was not properly imported etc.

Have fun OSMDing

**Comment by ljfreelancer88** [comment]
The score is displayed correctly. I used the plain javascript approach. No framework. 
But when I tried to transpose this score (OSMD_Function_Test_Tabulature_hayden_study_1.xml) found in your Github it's not transposing.

**Comment by JanVeb** [comment]
Sorry I misunderstood your issue, Simon will help you more on that.
I see, it wouldn't be that hard to transpose playing the score, on your own, but I don't have a clue how to transpose generated music sheet image, but it seems this is a function in OSMD,I just never used it.

Otherwise it's not mine GitHub repository as I'm just a user of OSMD.

**Comment by ljfreelancer88** [comment]
It did transpose using this code. 

```javascript
let openSheetMusicDisplay = new opensheetmusicdisplay.OpenSheetMusicDisplay("osmdContainer");
openSheetMusicDisplay.setOptions({
  backend: "svg",
  drawTitle: true,
  drawingParameters: "compacttight" // don't display title, composer etc., smaller margins
});

openSheetMusicDisplay
  .load("$score")
  .then(() => openSheetMusicDisplay.render());

  // quick and dirty way to transpose
  openSheetMusicDisplay.TransposeCalculator = new opensheetmusicdisplay.TransposeCalculator();
  document.querySelector('.js-transpose').addEventListener('click', function() {    
    openSheetMusicDisplay.Sheet.Instruments[0].Transpose = 2;
    openSheetMusicDisplay.updateGraphic();
    openSheetMusicDisplay.render();
  });
```

**Comment by sschmidTU** [comment]
Great! I would probably just create the TransposeCalculator once directly after creating the OSMD object, but it's a tiny class, so it shouldn't matter performance-wise.
