### ISSUE TITLE
Brackets for time modifications are not shown

### ISSUE THREAD

**Issue by mauxion** [opensheetmusicdisplay/opensheetmusicdisplay#1252]
Brackets for eight triplets are not visible.
OSMD version 1.5.8 

Expected: 
![image](https://user-images.githubusercontent.com/3764909/196174820-1925f54c-1b75-49ce-aa8e-2f8ba9b9a416.png)

Actual:
![image](https://user-images.githubusercontent.com/3764909/196175322-f28c7ca9-57a2-4ac2-b329-0e8098afb901.png)

My settings:

> backend: 'Canvas',
> drawTitle: false,
> drawPartNames: false,
> pageFormat: 'Endless',
> drawFingerings: false,                                                                                                                                                                                                   
> drawCredits: false,
> drawMetronomeMarks: false,
> drawTimeSignatures: false,
> renderSingleHorizontalStaffline: true,
> autoResize: false,
> coloringMode: 0,
> pageBackgroundColor: '#FFFFFF',
> performanceMode: false,
> drawingParameters: 'compacttight',                    
> drawUpToMeasureNumber: Number.MAX_SAFE_INTEGER     
> osmd.EngravingRules.RenderClefsAtBeginningOfStaffline = false

Here is file itself:
(sorry for .txt format, can't upload .musicxml or .xml)
[SwingOnRide.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/9800029/SwingOnRide.txt)

Related to:
#1253 
#1254

**Comment by sschmidTU** [comment]
They are displayed for me, also with your options.
<img width="180" alt="image" src="https://user-images.githubusercontent.com/33069673/196480908-d648cb14-b992-4de1-bea5-9fa62be1beec.png">

Maybe your top margin is too low so it's cut off? Try `osmd.EngravingRules.PageTopMarginNarrow = 0.5` or something if you're using compact mode.

Bugs should be reproducible in our demo, otherwise it's hard to test.
https://opensheetmusicdisplay.github.io/demo/
