### ISSUE TITLE
Lyrics misaligned when there is a rest in second voice

### ISSUE THREAD

**Issue by eddycurrently** [opensheetmusicdisplay/opensheetmusicdisplay#1267]
Hello all,

I've found a bit of a problem with lyric alignment when the bar contains a rest in the second voice. In this case the first lyric in the bar seems to be aligned with the rest rather than the first note in the first voice like this:
![lyric_misaglinment](https://user-images.githubusercontent.com/33544599/200286998-3590a96b-57aa-4e91-bb65-9e179d18c170.png)
[Here is a small example MusicXML file that reproduces the issue](https://drive.google.com/file/d/1TBr0aJrbGvKwpoSBt8-qpSY9UiQ2lNmx/view?usp=sharing)

If you need any more info, please let me know.

Regards

**Comment by sschmidTU** [comment]
Fixed.
<img width="742" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/c626075e-b4ab-4004-8b77-3214bd8f8993">

The issue was that the secondary whole rest overwrote the staff entry's x-position, since it belongs to the same staffentry as the first note.
It might be better to create a separate staffentry for a whole note if there are parallel staff entries with different x-positioning, but on the other hand we have some code that assumes there's only one staffentry per staff per timestamp.

The first note ("lorem") and the whole rest are technically on the same timestamp, so they're on the same staffentry.
<img width="751" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/04072216-528b-4ecd-859b-9a86f2a6b300">
That's why I had to add some positioning offsets to make sure the voice entry's position was still correct.
Otherwise it would be for example like this:
<img width="148" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/df836d20-12ea-4cfd-a0c9-eaaa7fda6678">
Or like this:
<img width="187" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/16033bea-0aa3-42c9-b949-4c086807e672">
