### ISSUE TITLE
Unnecessary space rendered for unused lyric lines

### ISSUE THREAD

**Issue by ErdoesiT** [opensheetmusicdisplay/opensheetmusicdisplay#1272]
If there are multiple lyrics (e. g. for multiple verses), OSMD always leaves space for this lyrics, even when there is nothing to display in the current line:

Example:
[Test cases - Partitur - 03 Lyrics.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/9971941/Test.cases.-.Partitur.-.03.Lyrics.txt)

Expected result:
![image](https://user-images.githubusercontent.com/28756388/200855810-80235c3a-47a8-4934-8e8c-86cc2c4b4140.png)

Actual result:
![image](https://user-images.githubusercontent.com/28756388/200855880-8965aca5-654e-4b55-b207-ca130b9f825f.png)

**Comment by sschmidTU** [comment]
Fixed in https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/pull/1284#issuecomment-1357693105

before:
<img width="386" alt="image" src="https://user-images.githubusercontent.com/33069673/208438671-8a34bfa5-e381-4522-97f5-700b2d84f9f3.png">

after:
<img width="401" alt="image" src="https://user-images.githubusercontent.com/33069673/208438849-c4831127-ec54-4f5f-8ba7-c75cb80ea1bf.png">

Note that the space is still used if on the same line:
<img width="688" alt="image" src="https://user-images.githubusercontent.com/33069673/208438814-545ed5da-54ef-4353-94e8-bcf0efb3ba45.png">
