### ISSUE TITLE
Long Cres. Hairpins (wedges) Not rendering properly

### ISSUE THREAD

**Issue by boblete** [opensheetmusicdisplay/opensheetmusicdisplay#1277]
![image](https://user-images.githubusercontent.com/445490/202670155-368b4da4-6c81-45b9-b2ac-140ca8f6511a.png)

See the example above 
Haripins when rendered across 3 or more staves lines do not render under the middle line. The hairpin should continue across the staves but the middle line is not rendering (probably because there is no data on that line to force it to render)

NB from Dischord Simon (sschmidTU):  'I've tried going back some commits, until about 1.4.6, but it doesn't seem like the bug is a recent regression'

Example score attatched
[HumanRightsDanceNights_DoubleBass_LEARNAPP_en-gb.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/10040115/HumanRightsDanceNights_DoubleBass_LEARNAPP_en-gb.musicxml.zip)

**Comment by sschmidTU** [comment]
Fixed in #1459.

<img width="340" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/996193ea-c7d6-4360-983c-cfeaf0693c55">

<img width="425" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/8626a793-4382-4a8d-a3d0-09fccc2704c8">

before:
<img width="435" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/66c5279e-a0d8-4c61-85ce-aab91b705acd">

settings:
`osmd.EngravingRules.NewSystemAtXMLNewSystemAttribute = true`

Sorry for the late fix, this was a lot more complicated than I thought.
