### ISSUE TITLE
Umlauts not allowed in key identifiers

### ISSUE THREAD

**Issue by RunaMC** [opensheetmusicdisplay/opensheetmusicdisplay#1293]
Please remove the german umlauts from
src/MusicalScore/SubInstrument.ts
The javascript compressor removes the quotes and then you will have something like
,flöte:n.MidiInstrument.Flute,
in opensheetmusicdisplay.min.js
which results in a "Invalid or unexpected token" error in the browser.
Please change flöte and blockflöte to floete and blockfloete.

**Comment by sschmidTU** [comment]
We can definitely do that, also for internationalization and accessibility, though it's odd that this should be an issue considering UTF-8 is used.
Where and from what source process exactly does this error arise? From webpack using the javascript compressor?

**Comment by RunaMC** [comment]
I used
<script src="opensheetmusicdisplay.min.js"></script>
and get errors with Chrome and Firefox.
You can also make a simple html page like

<html><head><script>
a={flöte:1};
alert(a["flöte"]);
</script></head></body></html>

and it will trigger the same error.
a={"flöte":1};
will work, but the javascript compressor that generates the opensheetmusicdisplay.min.js seems to illegaly remove the quotes.

**Comment by sschmidTU** [comment]
Done. Not getting a syntax error anymore in Chrome with the build after above commit.

Error I saw in Chrome:
`Uncaught SyntaxError: Invalid or unexpected token (at opensheetmusicdisplay.min.js:2:598401`

Test html with 1.7.1 build and fixed build:
[umlaut-test-osmd.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/10371936/umlaut-test-osmd.zip)

The fix will be in the next release 1.7.2.
(not currently scheduled because this is the first fix after the last release. but shouldn't be too far off)

Thanks for reporting!
It's odd that this was a problem, considering UTF-8 is used almost everywhere now, as I said.
I'm also pretty sure this used to not be a problem, we have a very similar, basic setup in our plain javascript example project, and I didn't see errors like this before. Maybe updates in javascript engines/browsers.
Anyways, doesn't matter much now, the object keys with umlauts probably weren't even used in base OSMD (maybe in the audio player).

**Comment by sschmidTU** [comment]
@RunaMC Released in 1.7.2, thanks again!
