### ISSUE TITLE
Discussion topic: Cursor disappears when switching parts in some cases

### ISSUE THREAD

**Issue by michaelcchu** [opensheetmusicdisplay/opensheetmusicdisplay#1312]
Example from "An die ferne Geliebte (Page 1)" in [demo](https://opensheetmusicdisplay.github.io/demo/):

<img width="282" alt="image" src="https://user-images.githubusercontent.com/50280000/215021906-c7f13e15-17a4-4e9f-8206-bfde9a0d1f99.png">

```js
osmd.sheet.Instruments[0].Visible = false;
osmd.render();
```
<img width="282" alt="image" src="https://user-images.githubusercontent.com/50280000/215022482-5fdbed44-d037-4cec-83e6-aa54495ca1d3.png">

I'm not sure what should happen in this case. What do you think?

Some possibilities are:

- nothing is highlighted (this is how it is currently)
<img width="282" alt="image" src="https://user-images.githubusercontent.com/50280000/215022482-5fdbed44-d037-4cec-83e6-aa54495ca1d3.png">

- the closest previous note is highlighted
<img width="282" alt="image" src="https://user-images.githubusercontent.com/50280000/215022875-2c620850-66bc-4cdb-a942-71d6c43bdb43.png">

- the closest next note is highlighted
<img width="282" alt="image" src="https://user-images.githubusercontent.com/50280000/215022989-cf3caf61-4928-40eb-bbc8-c71b08d8aa2a.png">

- a space between the closest previous note and the closest next note is highlighted
<img width="282" alt="image" src=https://user-images.githubusercontent.com/50280000/215023729-e847f192-1682-4253-ba65-8e8a04506bca.png>

This is not a very urgent issue, but it would be interesting if any people in the OSMD community had any thoughts or preferences on this topic. Feel free to discuss! :)

**Comment by sschmidTU** [comment]
I think the cursor should be reset by the developer in this case.
Technically, the previous cursor position doesn't exist anymore, when you make the instrument that had a note under it invisible.
Because the cursor works by going to the next x-position where there is a note anywhere vertically. Now there is no note.
What you can do in any case is either going backwards or forwards one position (next or previous).
The position in-between is an interesting option, but would be hard to implement on OSMD's side, because the x-positioning information of the now hidden note does not exist anymore.

**Comment by sschmidTU** [comment]
I've now changed behavior to show the previous position instead of nothing, if the current position now doesn't have visible notes.

<img width="262" alt="image" src="https://user-images.githubusercontent.com/33069673/215217933-df47cfc0-9fb6-4977-b04e-e36b561ae3c8.png">

```js
osmd.Sheet.Instruments[1].Visible = false;
osmd.render();
```

<img width="259" alt="image" src="https://user-images.githubusercontent.com/33069673/215218062-fd78a9e2-4f65-4ba0-a9ec-e08f059e5d9c.png">

**Comment by michaelcchu** [comment]
Thanks! This seems good to me.
