### ISSUE TITLE
[Question] Same width for all measures ?

### ISSUE THREAD

**Issue by CorentinTh** [opensheetmusicdisplay/opensheetmusicdisplay#1314]
Hi !
Is there a way to have the same width for all the measures ?

I need to align a [single horizontal staff line](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/src/OpenSheetMusicDisplay/OSMDOptions.ts#L175) with custom data for each note and division, so I'm trying to make so the measures all have the same width, is this possible ?  

Thank you in advance for your time 🙏🏻

**Comment by sschmidTU** [comment]
This is currently not possible.
The problem is that some measures need a lot of space, in which case you would more than double the space used for some measures unnecessarily.
I'm not sure what you're trying to do exactly, but you can simply get the position of each note and place the custom data above it, see here:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Exploring-the-Demo
(paragraph "Drawing overlay lines over the score and getting a note's position")

**Comment by CorentinTh** [comment]
Okey thanks for the details, I'll try with the note positions

Thank you for your time 🙏🏻

**Comment by sschmidTU** [comment]
Note that this (same measure width for all measures) can now be tested on the branch `feat/fixedMeasureWidth`.
But I hope you'll see that it's not a good idea.
We have to set the width of all measures to the width of the biggest measure, so small measures get very bloated.

Otherwise, measures will have less space than Vexflow needs (see `formatter.preCalculateMinTotalWidth`), and the layout will fail, creating tons of overlaps:
![image](https://user-images.githubusercontent.com/33069673/219523915-09783350-3539-4621-80c0-962920faafd2.png)

You can try this by setting `osmd.EngravingRules.FixedMeasureWidthFixedValue = 10` or other values. (this EngravingRule is just for testing)

We could merge the FixedMeasureWidth option into the main build, but I don't see where this could be reasonable when MusicXML files can contain very small and very large measures, which won't behave well with a fixed width.

**Comment by CorentinTh** [comment]
Thanks you very much for the feedback and the implementation, I'll give it a try 🙏🏻 
If you dont want to merge, I'll maybe use the `fixedMeasureWidth` branch

**Comment by fheyen** [comment]
@sschmidTU I would appreciate merging `feat/fixedMeasureWidth`, as some people (including myself) could find it very useful.
Examples:
- You already know the file(s) that will be displayed, such as exercises, so you know they will look better or more readable with fixed measure widths
- You want to be able to align measures for better comparison

Another option would be to give developers the freedom to specify the width of each measure separately, e.g., to avoid enlarging empty measures.

Is there any reason against merging the branch except that it will not be used by many?

**Comment by sschmidTU** [comment]
We can merge if multiple people want to use this, which as apparently the case.
Reasons for not merging were that I thought people would not think it's a good option after testing it, for reasons in my comment above, and also there's a tiny performance impact because of the additional if checks, but that's negligible.

Giving the measure width per measure could also be an option, though I think its usage can never be automatized, as every measure has a minimum width below which vexflow breaks and the layout creates tons of overlays, and it's basically not possible to predict when that happens. I think this will be a very fringe option, much more so than fixed measure width.

**Comment by fheyen** [comment]
I just saw this issue here: https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/534#issuecomment-511070265

> If you still want to change the measure widths, look at VexflowMusicSheetCalculator.calculateMeasureXLayout.
> Specifically, the width is set here, i think:
> 
> vexflowMeasure.formatVoices(minStaffEntriesWidth * unitInPixels);

So it seems possible to still have individual measure widths, but I agree that implementing this into OSMD is probably to much effort to be worth it.

**Comment by sschmidTU** [comment]
Merged to develop in #1368 (see comments there).
Will be in the next release.

**Comment by sschmidTU** [comment]
Fixed a bug where the first measure did not get the fixed measure width.

Also disabled applying the fixed width to pickup measure widths by default, because this option is clearly not good for them:
![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/0253f126-a56f-4c7e-b948-a671f4694a4a)

If you still want it as in the image above with the fixed width for pickup measures, set this:
`osmd.EngravingRules.FixedMeasureWidthUseForPickupMeasures = true`
