### ISSUE TITLE
Deleting/Removing OSMD Object

### ISSUE THREAD

**Issue by pokemon963** [opensheetmusicdisplay/opensheetmusicdisplay#1322]
Hi! I am trying to delete the OSMD object from the div container when a button gets clicked. Here is my code:

```
document.getElementById('changeSheet').addEventListener('click', function() {
  document.getElementById('osmdCanvas').innerHTML = "";
  sheet_loaded = false;
})
```

For some reason, it does not fully disappear. There are still contents in the div container when I check. Does anyone know what's wrong?

**Comment by sschmidTU** [comment]
It seems like you can't remove all children just by setting innerHTML.
try something like this:
```js
const div = document.getElementById("osmdCanvas") // or osmdCanvasPage1
while (div.children.length > 0) {
    div.removeChild(div.children[0])
}
```

unfortunately you can't just use a for loop, because children is an HTMLCollection which is only evaluated when you access it as an array.
Maybe add an iterator variable and break out of the while loop when you hit 100 loops or something so you don't infinite loop when the removing fails for some reason.

**Comment by pokemon963** [comment]
Just adding osmd.clear() before document.getElementById('osmdCanvas').innerHTML = ""; works! I checked the innerHTML afterwards and it worked!
