### ISSUE TITLE
rendering in a container with style.display = "none"

### ISSUE THREAD

**Issue by MaximeTuab** [opensheetmusicdisplay/opensheetmusicdisplay#1323]
Hi all,

First, many thanks to all devs here, you are wonderfull!!

I'm trying to render OSMD in a container with the property `style.display` equal to `"none"`. 
(my sheet music is rendered within a tab, and when I am rendering the sheet music, the tab is not necessary visible).

Unfortunately, OSMD is warning me: 

> SkyBottomLineBatchCalculatorBackend: width not > 0 in measure 1

And when I finally set `style.display` equal to `"block"` (activating the tab containing the sheet music), no sheet music would appear. 

Any idea on how to deal with displaying in such a container? 

Thanks all!

M.

**Comment by sschmidTU** [comment]
I don't think this is possible, because OSMD needs a DOM element and indirectly the canvas it provides, and I don't think a container with display none has a canvas to draw on.
Maybe you can use a collapsed element? But that probably also doesn't provide a canvas.
Otherwise you may have to toggle display to block and then create OSMD and/or call render().
