### ISSUE TITLE
[Job Offer] Looking for developers wanting to extend osmd

### ISSUE THREAD

**Issue by joaocc** [opensheetmusicdisplay/opensheetmusicdisplay#136]
Hi,
We are looking for experts in (and preferably contributors to) opensheetmusicdisplay to build some features, with focus on MusicXML rendering and cursor handling.
This will be a paid engagement, whose result may be contributed back to the community at some point in the future.
If you qualify and are interested, please do:
- get in contact at "jobs at highskillz dot com"
- apply to this [upwork job](https://www.upwork.com/jobs/~01c68f592b42790ecf)

We will close this issue when staffing is completed.
Thanks!

**Comment by matt-uib** [comment]
Hi @joaocc ,
 
I’m Matthias, one of the creators and core devs of OSMD. We love to see that you want to build additional features for OSMD and even posted a job offer for that :-)
 
Actually the features you requested are also on our roadmap. We already created the software concept for playback and repetitions. Due to limited resources we cannot start working on it immediately, but we think we will be done by end of this year.
 
Our plan is to offer these features as premium add-ons. How urgent do you need the features?
 
Let me know what you think!

**Comment by joaocc** [comment]
Hi Matthias. 
Thanks for your answer. 
We would love to use a version of osmd with the features we need.
Unfortunately, we will not be able to wait that long, as we are looking to have this in a few weeks time (probably not as fully featured or polished as if it was done by you guys :)).
Anyway, pls ping me on gitter to continue this discussion.
Cheers
