### ISSUE TITLE
Bounding box too tight when using drawingParameters: "compacttight"

### ISSUE THREAD

**Issue by bolau** [opensheetmusicdisplay/opensheetmusicdisplay#1372]
Hi,

when I use the drawingParameters "compacttight", the bounding box around the score actually seems too tight. Here's a screenshot, where the tie on the bottom gets cropped off:

![Example Image](https://user-images.githubusercontent.com/488733/235806119-9b9b12dd-74db-47ed-a7f6-d5645ad11a94.png)

Here's the XML file to reproduce the problem:
[short.xml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/11378306/short.xml.zip)

Is this is bug? Is there a simple workaround, e.g., a way to control additional margins?
I could also use the regular drawingParameters and delete all the extra stuff, but that doesn't sound like fun.
This is OSMD 1.7.5, tested using Firefox and Chrome on MacOS.

Thanks for any help,
Best, Boris

**Comment by sschmidTU** [comment]
`compacttight` mode sets the margins as tight as possible, and for some elements it can happen that the boundingbox is a few pixels too small and gets cut off.
It also sets the BottomMargin to 0. A slightly larger margin helps:
`osmd.EngravingRules.PageBottomMargin = 0.3`

You can see all the options that are set in this mode:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/4c31dde446ae0b962735f06340f62470ecccbec8/src/MusicalScore/Graphical/DrawingParameters.ts#L130

You can modify some of them after you've set the mode.

It would be nice if the tie wasn't getting cut off even in `compacttight` mode, but bounding box calculations can be a bit fickle, it's probably due to some details in our Skybottomline calculations.

Anyways, I hope the workaround is satisfactory.

**Comment by bolau** [comment]
Thank you so much, this worked like a charm!
