### ISSUE TITLE
Additional cursor capabilities

### ISSUE THREAD

**Issue by joaocc** [opensheetmusicdisplay/opensheetmusicdisplay#139]
Current cursor could be improved with the following features:
* move to next note and highlight the complete bar and note
  the goal is to highlight a complete bar (light shading) and note (darker shading)
* move to the next beat in the bar (according to time signature)
  the goal is to highlight all the notes that are start to be played in that beat, to make it easier to move through the score at a constant speed
* set cursor to clicked note or beat

**Comment by jepcolombia** [comment]
Set cursor to any decided mesure.
Set cursor back
Set cursor to start and end point to be able to play a loop
Iam needing this

**Comment by sebastianhaas** [comment]
@matt-uib is this something we could do easily?

**Comment by jepcolombia** [comment]
Could you please give us a tip on how to do this ? Where in the code to look to implement move to back and move to x measure?
Thanks in advance for your answer!

**Comment by matt-uib** [comment]
@jepcolombia what exactly do you mean here? Move to the end of the music piece? Move to the n-th Measure in the piece?
Actually we will very soon start working on a plugin infrastructure for osmd. Our plan here is, that we can offer services and plugins for a license fee. The first plugin on our list is a playback engine.
Features:
* Set start position (via click onto a note on the score)
* set end position (for looping)
* set speed in BPM
* play back a metronome together with the music (with pre-count)
* Playback of given chord symbols
* Solo, Mute switches and volume settings for all instruments, the metronome and the chords (if avaliable)
* React on repetitions (backjumps), on dynamics (p, ff) and tempo instructions
Maybe this is exactly the stuff you need.

**Comment by jepcolombia** [comment]
Thanks Matt that first plugin in your list for playback is what iam looking for! Have you an estimated date for release?
Thanks again

**Comment by matt-uib** [comment]
We are just about to priorize and estimate the coming features and plugins like playback. As a rough estimate i would say October/November.

**Comment by jepcolombia** [comment]
Great!

**Comment by jaredjj3** [comment]
At the time of writing, `Cursor` and `MusicPartManagerIterator` only have the capability of moving to the next voice  entry via `Cursor.prototype.next` or `MusicPartManagerIterator.prototype.next`.

---

In my application, I need the ability to jump to any voice entry based on the time stamp. The idea is to keep the cursor synced with a video/media at all times.

I'd like to share what I did in case there's someone else that is trying to do the same thing.

## Naive Solution

Since cursors can only move forward, a naive solution would be to reset the cursor and move to the next voice entry until the target voice entry is found.

Let `n` be the number of voice entries in a `MusicSheet`. This approach has a time complexity of `O(n)` which is unacceptable as this might be done every tick (using `requestAnimationFrame`). I also did not want to accept the performance degrading for larger transcriptions. The inefficiency was significantly noticeable on mobile devices.

## Hacky Solution

[MusicPartManager.prototype.doBackJump](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/e0d70bc67d26465078fc224c69615bd0789cdaa3/src/MusicalScore/MusicParts/MusicPartManagerIterator.ts#L393) is a method that is called when handling repetitions, as the cursor needs to jump backwards. A hacky solution would be to mimic the mutations done in this method except the repetitions. This is certainly more performant than the naive solution, but there is no guarantee on the API.

Let `n` be the number of voice entries in a `MusicSheet`. This approach has a time complexity of `O(1)`, but a space complexity of `O(n)`, since you have to store a mapping of time ranges to voice entries, source measures, and measure indexes (i.e. the data needed to perform the mutations in `MusicPartManager.prototype.doBackJump`)

What's even worse about this solution is that the caller must manage repetitions appropriately. I couldn't figure this out without more hacks, so I decided on another approach.

## Best Solution (so far)

This solution involves the following steps:

- Create a throwaway probe `Cursor`
- Reset the probe cursor
- Until the probe cursor is at the end
  - Snapshot the probe cursor's iterator using `MusicPartManagerIterator.prototype.clone`
  - Associate a time range with the iterator snapshot
- Store the mappings of time ranges to snapshot

- When a caller wants a cursor to move to a snapshot
  - Replace the cursor's iterator with a clone of the snapshot's iterator
  - Update the cursor
  
Let `n` be the number of voice entries in a `MusicSheet`. This approach has a time complexity of `O(1)`, and a space complexity of `O(n)`, since you have to store a mapping of time ranges to iterator snapshots. I considered this the best solution since I didn't have to hack the internals of `MusicPartManagerIterator` nor `Cursor`.

It's still a very scrappy solution, but it worked out for my use case. I'm still skeptical if this works for repetitions or pieces with multiple voices with different rhythms.
  
I'll try to spare the minutiae of the actual implementation, but it's lengthy:

_IteratorSnapshot.ts_

```ts
export class IteratorSnapshot {
  static create(iterator: MusicPartManagerIterator) {
    return new IteratorSnapshot(iterator.clone());
  }

  private iterator: MusicPartManagerIterator;

  private constructor(iterator: MusicPartManagerIterator) {
    this.iterator = iterator;
  }

  get() {
    return this.iterator.clone();
  }
}
```

_VoiceSeeker.ts_

```ts
private calculateVoicePointers(): void {
  const voicePointers = new Array<VoicePointer>();

  // Initialize accounting variables
  let prevVoicePointer: VoicePointer | null = null;
  let currBeat = 0;
  let currTimeMs = this.syncSettings.deadTimeMs;
  let index = 0;

  // this.probe is a Cursor object
  this.probe.reset();

  while (!this.probe.iterator.EndReached) {
    const iteratorSnapshot = IteratorSnapshot.create(this.probe.iterator);

    // Get OSMD-specific references
    const entries = this.probe.VoicesUnderCursor();
    const note = entries[0].Notes[0];
    const bpm = this.probe.iterator.CurrentMeasure.TempoInBPM;
    const numBeats = note.Length.RealValue;

    // Calculate beat range
    const startBeat = currBeat;
    const endBeat = startBeat + numBeats;
    const beatRange = NumberRange.from(startBeat).to(endBeat);

    // Calculate time range
    const startTimeMs = currTimeMs;
    const endTimeMs = startTimeMs + this.convertNumBeatsToMs(bpm, numBeats);
    const timeMsRange = NumberRange.from(startTimeMs).to(endTimeMs);

    // Calculate voice pointer
    const voicePointer: VoicePointer = {
      index,
      next: null,
      prev: null,
      beatRange,
      timeMsRange,
      iteratorSnapshot,
      entries,
    };
    voicePointers.push(voicePointer);

    // Perform linking if necessary
    if (prevVoicePointer) {
      voicePointer.prev = prevVoicePointer;
      prevVoicePointer.next = voicePointer;
    }

    // Update accounting variables
    prevVoicePointer = voicePointer;
    currBeat = endBeat;
    currTimeMs = endTimeMs;
    index++;

    this.probe.next();
  }
  this.probe.reset();

  this.voicePointers = voicePointers.map((voicePointer) => Object.freeze(voicePointer));
}
```

_example usage_

```ts
update(timeMs: number) {
  const seekResult = voiceSeeker.seek(timeMs);
  
  if (seekResult.voicePointer === this.currVoicePointer) {
    return;
  }
  
  // The cursor will jump to wherever the iterator snapshot was taken.
  this.cursor.iterator = seekResult.voicePointer.iteratorSnapshot.get();
  this.cursor.update();
}
```

**Comment by sschmidTU** [comment]
@jaredjj3 Thanks for sharing your solution! You could probably construct the cursor/iterator even more directly, setting its timestamp and even repetition state, but it might get more complex. Usually what we've found so far was that just calling `cursor.next()` until you're at the right spot is fast enough (instantaneous), but I can imagine that on mobile, with complex scores and especially updates every frame, it'll be too slow.
Also, I wonder if just storing a cursor clone for the start of each measure, then doing the usual .next() loop, would be fast enough, and consume less memory. But you already have a faster and more precise solution.

**Comment by sschmidTU** [comment]
Basically all of this is possible now.
