### ISSUE TITLE
Best way to debug app

### ISSUE THREAD

**Issue by coderhelps** [opensheetmusicdisplay/opensheetmusicdisplay#141]
I have some music that was scanned in through smartscore x2 and then converted to musicxml.
When trying to render it in opensheetmusic I can see the notes but everything else doesn't show up, lyrics, titles, text, etc. What is the best way to see what is being read in and what content is being skipped?

**Comment by sebastianhaas** [comment]
Run

`$ grunt build:demo`

to run a debug-build of OSMD.

In another terminal, run

`$ npm start`

and keep it running to serve the OSMD demo at http://localhost:8080.

You should be able to use your browser to step through the application. The core functionality when it comes to reading a MusicXML file is located in [`MusicSheetReader.ts`](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/src/MusicalScore/ScoreIO/MusicSheetReader.ts).
You're always more than welcome to upload your MusicXML here so that other people can maybe take a look. Have you tried opening your MusicXML in, for instance, MuseScore to see if your file is looking good?

**Comment by coderhelps** [comment]
Thanks, I will look into this.
If I open up the music in musescore, all the content is there, some of this positioning is incorrect but it looks like all the text is in the document. It definitely has more than what is showing up in opensheetmusic. If I cant see anything obvious I will post a test file here

**Comment by sebastianhaas** [comment]
You may also want to try and save your file from MuseScore again before loading it with OSMD; I have the feeling that MuseScore produces a more standard MusicXML output than some other products.

**Comment by bneumann** [comment]
I guess it would be easier if you could provide the MusicXML file for debug purposes. Otherwise the "easiest" way is to check the file itself which version (OSMD seems only to support V3 of MusicXML) is used and if the tags are on correct order.

**Comment by bneumann** [comment]
Is this still active?

**Comment by matt-uib** [comment]
@coderhelps see here on our roadmap:
https://opensheetmusicdisplay.org/develop/roadmap/
(which has to be updated now, as Articulations, Lyrics and Repetitions are rendered now in a first version)
