### ISSUE TITLE
Inverted triangle NoteHeadValue displays wrong

### ISSUE THREAD

**Issue by mauxion** [opensheetmusicdisplay/opensheetmusicdisplay#1418]
I have notes where one of instrument (cowbell) has a NoteHeadValue == inverted triangle.

Expected:
![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/3764909/986d00d1-febd-4734-ab76-3297b96c566e)

Actual:  
![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/3764909/4aa7548a-94d2-48f7-b673-8dbb7e7ccc95)

MusicXml attached 
[Money beat.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/11903195/Money.beat.txt)

**Comment by sschmidTU** [comment]
Done.

<img width="256" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/d9d31d81-2a59-4fd3-915e-7afd0299977c">

<img width="254" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/b3905d0f-963c-4489-95dc-ef67e6dd364f">

[test_notehead_inverted_triangle_stem_up_down.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/12051266/test_notehead_inverted_triangle_stem_up_down.zip)

Note that the x and y positioning especially for the smaller notes isn't ideal, but hard to optimize. If we e.g. shift everything right one more pixel, the triangle of the small notes is not well visible, basically "eaten up" by the stem, or not connected to it. There are some intricacies of the glyph code here because this is a custom glyph that wasn't originally supported by Vexflow, so without a real deep dive into the custom glyph code, I think this is as far as we can go right now. Probably the x-shift would need to scale with note scaling.

**Comment by mauxion** [comment]
Looks great! Thank you @sschmidTU !
