### ISSUE TITLE
Subtitles sometimes not displayed

### ISSUE THREAD

**Issue by fablau** [opensheetmusicdisplay/opensheetmusicdisplay#1456]
Hello @sschmidTU  and team,
I am just wondering if OSMD is evaluating anything inside the "[credit](https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/credit/)" element of MusicXML. From my tests and analysis of the code, it looks like OSMD is completely ignoring it. Am I mistaken? And if not, why?

Looking forward to your thoughts on this.

Thanks!

**Comment by sschmidTU** [comment]
Yes, composer, lyricist, title, etc. You can just search for `"credit` in the code.
What are you missing and why?

**Comment by fablau** [comment]
Ok Simon, I can't find any reference to the `<credit-type>` tag.

Try the attached MusicXML file, the subtitle isn't shown in the OSMD demo despite osmd.EngravingRules.RenderSubtitle should be true by default. 
[01MeditationVlPf Nuova.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/12613265/01MeditationVlPf.Nuova.musicxml.zip)

**Comment by sschmidTU** [comment]
Fixed.
<img width="873" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/bca8fa03-5df6-4880-b90c-ef91755798fe">

You can set e.g. `osmd.EngravingRules.SheetMinimumDistanceBetweenTitleAndSubtitle = 2` if you want to increase the margin between title and subtitle.

And by the way, just to show you that MusicXML parsing is hard, this is how MuseScore (a project much larger and older than ours) loads the file:
<img width="658" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/b588f57c-ef64-4268-b65d-fcf1ca5973be">
(it also says the file is corrupt)

---

> I can't find any reference to the `<credit-type>` tag.

Unfortunately we can't rely on the credit-type tag, because it's optional.
[credit element](https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/credit/):
<img width="226" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/cfa43dfc-8a14-43d4-8274-547b060d3856">

Beethoven example:

<img width="927" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/e97e35d0-1c2c-438a-b5cc-30cb61511502">

**Comment by fablau** [comment]
Fantastic! Thank you Simon!!

**Comment by fablau** [comment]
@sschmidTU have you idea why OSMD doesn't show the subtitle with the attached MusicXML file? Thanks for looking into this.
[AveMariaVoce.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/12754706/AveMariaVoce.musicxml.zip)

**Comment by sschmidTU** [comment]
Because the credit-y given corresponds to a higher placement in the sheet than the title (bigger y = further down), which of course doesn't make much sense.
So, you can increase that default-y value to make the subtitle appear.
<img width="514" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/8e6dece2-d8e5-4eb9-8b08-6ed5cf060a99">

**Comment by sschmidTU** [comment]
Fixed, all subtitles with `<credit-type> subtitle` in the XML will now be recognized.
No changes in our existing samples.

**Comment by fablau** [comment]
Awesome! Thank you Simon!
