### ISSUE TITLE
Why is tuplet number shown here?

### ISSUE THREAD

**Issue by fablau** [opensheetmusicdisplay/opensheetmusicdisplay#1460]
Hello team,
Here is another issue I can't explain. Look at the attached XML file. Although all triplets are set NOT to show the number (with `show-number='none'`), OSMD shows the number for the first two triplets in the right hand. Why's that?

 
[01Adagio_sostenutoOSMDtest.xml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/12777671/01Adagio_sostenutoOSMDtest.xml.zip)

**Comment by sschmidTU** [comment]
Simple answer: We didn't read that attribute. Question solved ;)

I've added parsing of this attribute, it should be respected now.
Before:
<img width="548" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/75f157da-297d-4255-a21d-6b62853a4652">

After:
<img width="686" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/34691cde-a7a0-4f41-906e-2e0e5578691e">

You can set `osmd.EngravingRules.TupletNumberUseShowNoneXMLValue = false` to ignore this attribute if desired.

By the way, the other tuplet numbers weren't shown because of `osmd.EngravingRules.TupletNumberLimitConsecutiveRepetitions = true` which perhaps shouldn't be the default option, though it helps in a lot of piano scores exactly like this one by not showing a number on every single triplet.

Interestingly, the `show-number` attribute is not used in any of our current 198 test samples, despite existing since MusicXML 3.0.

**Comment by fablau** [comment]
Awesome, thank you Simon!

How interesting that most viewers ignore that definition. In classical music that's often necessary ;)
