### ISSUE TITLE
Incorrectly displaying sheet

### ISSUE THREAD

**Issue by katinas15** [opensheetmusicdisplay/opensheetmusicdisplay#1462]
Hi, sorry for an abstract title, but I have multiple issues rendering a musicxml file using osmd.

OSMD demo -> [file used](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/12777991/012.red.XML.zip)
![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/41838906/11f4dfc4-6896-458a-ac76-ff437bb8dbd2)

But the sheet should look like this:
![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/41838906/67eef8fa-ea3e-4a5d-a180-b9b94f56e63e)

I do not know the full musical term, but here are a few issues a client has listed:
1. Accolade is not correct
2. There are no lines inbetween
3. Text "Fine" is of wrong font and not in the correct place
4. Word "Coda" should not even appear
5. Missing dotted line between notes
6. these "<" are not in the correct height

Is there something wrong with my file? Do I need to adjust something with my settings? Or is this some bug?

**Comment by fablau** [comment]
The MusicXML protocol is somewhat limited from the "graphical accuracy" standpoint. Furthermore, OSMD is still in development, and some of those markings and signs are probably not yet handled.

As for the connected bar lines, is that the "piano" instrument clearly defined inside the MusicXML file? Just wondering...

I am sure @sschmidTU can further clarify and correct me if I am wrong.

**Comment by sschmidTU** [comment]
As fablau implied, you will unfortunately simply never get the exact same result that you see in your music editor when rendering a MusicXML file with another program. So 6 and maybe 2 are not going to happen. This is because the rendering systems are different, elements need a different amount of space and are placed differently, so we can't do everything the same without causing collisions and so on.

1. I assume you mean the group / instrument brace / bracket. Again, you won't get the exact same style as in your music program.
2. I assume you mean the measure bars (vertical lines) not connecting. Not planned for OSMD, irrelevant musically.
3. Font is similarly not a main concern of OSMD, though you can change `osmd.EngravingRules.DefaultFontFamily`. Theoretically, we could try to read the font from the MusicXML if given, though that would also depend on the user having that font installed /available for the browser.
4. Again this is musically irrelevant, as the coda text is a representation of the coda symbol, but the MusicXML file also does not specify that no text should appear.
5. This is interesting, the MusicXML does say `<slur line-type="dashed"`, I've never seen that so far, OSMD does not support that yet. Could be considered for implementation. Though I don't think we have ready-made API calls for dashed bezier curves right now.
6. As mentioned, exact height is impossible to achieve for all MusicXML elements the same as in a particular music program, OSMD checks where elements can be placed without collisions.

All in all this issue is a bit hard to approach because these are many different sub-issues and most of them will not be solved in OSMD, so your initial goal of getting the exact same rendering as in your music program is unfortunately not going to happen anyways.
But we could split these into sub-issues, and especially if we (both/all) think about which issues are higher priority (also for the community as a whole), we can definitely work on some of these.

**Comment by katinas15** [comment]
Thank you for your details answer. Really awesome.

We can close the issue, because it seems it just doesn't work 1 to 1 as I imagine it would.

I will do as you suggested, just talk to my client and see if we work out some compromise.

Thanks again, closing

**Comment by fablau** [comment]
Thank you Simon, happy to help! ;)
