### ISSUE TITLE
Weird horizontal placement of the starting syllable

### ISSUE THREAD

**Issue by olin256** [opensheetmusicdisplay/opensheetmusicdisplay#1470]
Hello,

what is the reason for the extra indent here?
![osmd_indent](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/84866288/41602028-1890-41db-ac98-6f16c2a66e4a)

It seems to affect syllables with `<syllabic>begin</syllabic>`, but not always.

[XML example (uploaded as txt)](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/12844308/mnozi_spravedlivi.txt)

**Comment by sschmidTU** [comment]
It might be due to margins, the below example is technically a collision with the downwards stem of the note, if you include margins.
It would be great if you could pinpoint the exact version where this switched. Even better, the exact commit, though that's of course a lot to ask. I'm curious which code change exactly caused this behavioral change myself.

**Comment by olin256** [comment]
Fortunately, the complexity of binary search is `O(log n)`, so this was not that hard to locate. The guilty commit is 8e1301f8116a6bc71cdcd1e175345496cfa20add. Which makes sense, it seems to have made many changes in lyrics spacing. I guess I should take a look at the engraving rules introduced there and see if I can find a suitable setting. (The reason I posted this was that I was more satisfied with the output of 1.7.6…)

**Comment by sschmidTU** [comment]
Very nice, thanks for finding it! Haha, yes, I also usually try to do binary search for guilty commits (cutting the range in half every time).

Right, you might be able to change a few EngravingRules to improve your outcome, e.g. you could try to increase `LyricsXPaddingWidthThreshold`. That seems like the most likely candidate to me.

**Comment by sschmidTU** [comment]
@olin256 `osmd.EngravingRules.LyricsXPaddingWidthThreshold = 5.5` seems to do the trick.
I'm not sure why the layout changes so much with varying values, though that's just a side note. (for a second I thought you might need to reduce the value instead of increasing it, but no, that just causes weird layout changes)

**Comment by olin256** [comment]
@sschmidTU Thanks, this setting is indeed better.
