### ISSUE TITLE
Support color attr in <words> element

### ISSUE THREAD

**Issue by knoguchi** [opensheetmusicdisplay/opensheetmusicdisplay#1492]
According to [MusicXML spec](https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/words/) document, <words> element can have an optional color attribute.  Please support color attribute.
```
<direction placement="above">
  <direction-type>
    <words color="#ff0000">text in read</words>
  </direction-type>
</direction>
```

Is interpretWords the right place to add such support?
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/314f8f55dcc4b7581c3fdc2d92285fa46d8727a5/src/MusicalScore/ScoreIO/MusicSymbolModules/ExpressionReader.ts#L523

**Comment by sschmidTU** [comment]
Do you have a sample in mind for this? Because it depends how these words are used. (Tempo? Dynamics? etc)

PR #1498 will likely have the solution.

<img width="124" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/d5d0443d-1d66-4e1c-a207-e198474821d9">

**Comment by sschmidTU** [comment]
@knoguchi Do you have a sample in mind for this? Because it depends how these words are used. (Tempo? Dynamics? etc)
Can you share a MusicXML file? (either rename it to .txt or zip it, then you can drop it here)

PR #1498 will likely have the solution.

<img width="124" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/d5d0443d-1d66-4e1c-a207-e198474821d9">
