### ISSUE TITLE
customize the number of measures per line

### ISSUE THREAD

**Issue by miller06** [opensheetmusicdisplay/opensheetmusicdisplay#1494]
Hello, how to customize the number of sections per line

**Comment by miller06** [comment]
![11](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/38524928/b4b3d4ad-3218-4fe1-9d54-4d28dad67384)

**Comment by sschmidTU** [comment]
You mean to customize the number of measures per line. That's not possible. It also wouldn't look good, because then some measures would be extremely compressed, and some extremely stretched.

You can set an equal measure width for all measures, which might lead to the same number of measures per line, but that's also not recommended. See #1314.

**Comment by miller06** [comment]
Thank you for your answer.

**Comment by miller06** [comment]
The customer's requirement is that the format of the score presentation should be consistent with the format in the book. Is there any way to solve this problem

**Comment by sschmidTU** [comment]
You can set `osmd.EngravingRules.NewSystemAtXMLNewSystemAttribute = true;`, then OSMD will make a system break (line break) when there's a system break in the sheet music. Usually that doesn't make sense for OSMD, because it can happen that you will only have a single measure in a line. So you will have to make sure that the system breaks in your MusicXML files are exactly what you need, for a given canvas size (size in the browser, window dimensions, etc).

**Comment by miller06** [comment]
When NewSystemAtXMLNewSystemAttribute is set to true, the format displayed for MusicXML line breaks will be broken. If it is a pagination mark, the displayed format will not be broken and will be squeezed together, resulting in the last line not being filled
![1111](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/38524928/1e618445-53e3-4eb1-b16b-12f8250a19bf)

**Comment by miller06** [comment]
The format displayed for MusicXML newline tags will wrap. If it is a pagination tag symbol, the displayed format will not wrap and will be squeezed together
![555](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/38524928/8d31f63a-0d2e-4460-8576-8da3139eab84)

**Comment by miller06** [comment]
I set NewPageAtXML NewPageAttribute to true and generated two osmdCanvasPages
![66](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/38524928/574a0727-9c36-46c6-afd0-e21a64f25fb3)

**Comment by sschmidTU** [comment]
You can also set `NewSystemAtXMLNewPageAttribute = true` so that you will get a new system instead of a new page.
That should solve your issue above, right?

**Comment by miller06** [comment]
Thank you for solving my problem
