### ISSUE TITLE
Build is broken when I try to create a pull request

### ISSUE THREAD

**Issue by bneumann** [opensheetmusicdisplay/opensheetmusicdisplay#152]
My pull request doesn't build and always gives me:

```The command "openssl aes-256-cbc -K $encrypted_170846311824_key -iv $encrypted_170846311824_iv -in bin/gh_pages_deploy_key.enc -out bin/gh_pages_deploy_key -d" failed and exited with 1 during .```

Looks like I don't have the correct set of keys or something. Such a petty :(

PR is #127

**Comment by sebastianhaas** [comment]
Sorry for that, I'll have a look today.

**Comment by sebastianhaas** [comment]
Sorry again for today becoming a week.

TL;DR it should work now.

We're using encrypted environment variables for deployment. There seems to be a security issue with the way this was handled. https://blog.travis-ci.com/2016-07-07-security-advisory-encrypted-variables
So apparently, it's not working on forks anymore. I just moved the decryption section to a point in the Travis build that is only called on deploys rather than `before_install`.
