### ISSUE TITLE
Cursor scrolls entire page when followed

### ISSUE THREAD

**Issue by NyuBlara** [opensheetmusicdisplay/opensheetmusicdisplay#1541]
This is less of an issue report and more of a small feature request.

When a cursor is followed, it calling `scrollIntoView()` scrolls, not just the OSMD container, but every one of its scrollable parent elements as well. In turn, when OSMD is used only within a smaller div in the page, this div is forcefully scrolled into view every time the cursor moves. This process happens outside of any event bubbling and is thus not preventable to my knowledge. 

It would be nice to be able to toggle this behavior on or off, i.e. make it so the cursor only scrolls, at most, the OSMD container, leaving the rest of the page to scroll away from it if needed.

**Comment by J43fura** [comment]
Any workaround?

**Comment by NyuBlara** [comment]
@J43fura In my case, I resorted to directly editing the `scrollTop` property of the OSMD container element with a set of conditions based on the cursor element's current position.

**Comment by sschmidTU** [comment]
That seems to be the way to do it (setting the scrollTop property of the container).
I tried `scrollIntoView({block: "nearest", inline: "nearest"})` (in `Cursor.update()`), but it still scrolls the whole page even when the container is embedded (with its own scroll bar).
(you can try this in the osmd embedded demo)

We could maybe make this the default behavior, but it gets a bit complicated because 1) We currently do a smooth scroll which we'd have to implement manually for just setting the scroll bar and 2) with a PageLayout where you have multiple pages we might need to choose different containers to scroll programmatically.
We could do that if there's a lot of demand, but on the other hand people might want to implement this on their own anyways to fine tune custom behavior.

**Comment by NyuBlara** [comment]
@sschmidTU Yes, I also tried the `scrollIntoView` options on my end and can attest to the fact that they do not work for this purpose.

I understand that the feature is not on the road map. Thanks for the reply !

**Comment by chz8494** [comment]
the default behavior of update() is quite annoying. 
I tried to add and adjust `scrollIntoView` after cursor loaded, but because update() has default setup to always center, when I put `start` there, it would just move my whole window, pretty bad user experience.
can we do something like
```ts
this.cursorElement.scrollIntoView({ behavior: "smooth", block: "start", inline: "start" })
```
so that my window/view won't be jump up/down?

**Comment by sschmidTU** [comment]
You can disable `osmd.FollowCursor` and scroll however you want.

**Comment by sschmidTU** [comment]
We've tried only scrolling the OSMD container with scrollIntoView, it's impossible as far as I know.
