### ISSUE TITLE
Misplaced breath marks

### ISSUE THREAD

**Issue by olin256** [opensheetmusicdisplay/opensheetmusicdisplay#1548]
This is what I'm getting (via both the demo and my own page):
![breath](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/84866288/83f7aef6-34d2-43c1-a86e-9b1afd1802d1)
[MusicXML file](https://github.com/user-attachments/files/15753918/102-1.txt)

**Comment by sschmidTU** [comment]
Fixed.
<img width="99" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/74b0d856-1cb4-48e9-b3ee-08911926a86c">

also fixed for this sample:
![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/a602d6e9-7acc-4ac8-aa7b-262950e80f71)
fixed:
![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/ef69c2fe-eaf3-496e-93d1-fcc67a8c2007)

added to test samples as `test_breath_mark_non-implicit_multiple_drums.musicxml`

Will be in the next Release OSMD 1.8.9, should be coming in the next few days.

**Comment by olin256** [comment]
It seems to me that there is still something wrong. Consider the following file:
[misplaced.txt](https://github.com/user-attachments/files/17329187/misplaced.txt)
This is what I'm getting from the demo:
![misplaced_517](https://github.com/user-attachments/assets/4645ae9e-8a45-418a-8df3-f8e250e47aa9)
However, the breath mark should come _after_ the final note in the top voice, not before.

After a bit of experimenting, it seems to be affected by the eighth notes in bass; when I turned them to one quarter, the breath mark moved to its correct place. Removing the other two voices had no effect.

**Comment by olin256** [comment]
Is this not worth reopening? Or should I open a new issue?

In the meantime, I've produced a more minimal example:
[dalsi_pokus.txt](https://github.com/user-attachments/files/17377827/dalsi_pokus.txt)

**Comment by sschmidTU** [comment]
@olin256 Fixed.
<img width="220" alt="image" src="https://github.com/user-attachments/assets/692b8608-c070-41c2-b56f-1eb0851caf1a">

Somehow Vexflow saw a next tick context after the B (last note of the measure), maybe a Vexflow tick system bug.
We now ignore the next tick context if its x value is smaller.

I'll take the first sample for the test samples, because too many notes with the same note value makes debugging harder.

(Note that we the demo will take some time to update, because we don't release new versions every day, usually only at npm releases)
