### ISSUE TITLE
What are the defaults for OSMDOptions?

### ISSUE THREAD

**Issue by supersational** [opensheetmusicdisplay/opensheetmusicdisplay#1558]
Just wondering if defaults are specified anywhere for the OSMD options object? Some are listed in comments here, but with many others the defaults are not specified e.g. spacingBetweenTextLines: 
[opensheetmusicdisplay/src/OpenSheetMusicDisplay/OSMDOptions.ts at develop · opensheetmusicdisplay/opensheetmusicdisplay](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/src/OpenSheetMusicDisplay/OSMDOptions.ts)

The reason is I'm planning to expose them to the end user in Python, so was going to convert the options to python type to support type hinting [supersational/showscore: Render music21 scores in jupyter notebooks](https://github.com/supersational/showscore)

Thanks!

**Comment by sschmidTU** [comment]
Yes, the default OSMDOptions are later on in the file you shared:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/src/OpenSheetMusicDisplay/OSMDOptions.ts#L301

There are more "options" in the EngravingRules class, though not all of these are meant to be changed, otherwise they are kind of an extended options set. The default values are set in `loadDefaultValues()`.
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/src/MusicalScore/Graphical/EngravingRules.ts#L529

Feel free to keep asking questions, I'll just close this so it won't accidentally stay open for a long time, but I'll keep answering.
