### ISSUE TITLE
How to add additional classes to svg elements

### ISSUE THREAD

**Issue by playpianu** [opensheetmusicdisplay/opensheetmusicdisplay#282]
Hello! Big fan of this project. 

I was just wondering the best way to add a class to each svg element to describe what it is. I'd love to be able to select individual elements based on if they're a rest or a note.  For instance, all notes and rest are drawn with the vf-notehead class: 

<g class="vf-notehead"></g>

After page load, I'd like to be able target elements based on if their a note or rest such as:

<g class="vf-notehead rest"></g>

is this possible? 

Thanks.

**Comment by bneumann** [comment]
Hi @playpianu ,

thanks for the praise, good to hear. About your request: That is not possible at the moment. We are relying on the vexflow library for drawing and as far as I know they also don't support this feature. On the highest level we create Vexflow notes which are drawing SVG stuff. So in order to get the groups on our side we would need access to the exact DOM nodes written by vexflow.

Sorry pal. BUT we are currently working on a plugin system which can be used to access different parts in the sheet and do whatever you want. But this will take some time.
