### ISSUE TITLE
Create Demo xml for articulations and ornaments

### ISSUE THREAD

**Issue by bukaznik** [opensheetmusicdisplay/opensheetmusicdisplay#284]
Please create 

- [X] articulations xml
- [X] ornaments xml

showing all items we currently support.

Then add this to the demo.

**Comment by bneumann** [comment]
I can also check in my expresssions demo files

**Comment by sebastianhaas** [comment]
Is this something where I could help out? What's the plan? Create some artificial xml that contains all articulations/ornaments or find a piece that contains a realistic subset e.g. multiple pieces that cover a large amount of symbols?

**Comment by sschmidTU** [comment]
I already created a test file for ornaments+articulations+slurs, adapted from @ChrisUib's test file, which looks like this:
![image](https://user-images.githubusercontent.com/33069673/42562633-86f42648-84fc-11e8-8411-15a419dfe363.png)
I will add it to the demo, it's currently in an internal shared folder.

I had to separate the notes a bit and put the texts as lyrics, because otherwise they are currently not shown. The ornaments are currently only shown in the ornaments branch, and the slurs in the slurs branch, though there are some errors when you put in a lot of different slurs.

I might make a separate file for the slurs so that they get their own heading, but i talked with bukaznik and we agreed one OSMD function test file with ornaments+articulations+slurs is also useful.

**Comment by bukaznik** [comment]
would be great to have everything osmd manages to display in this file. is there anything like an osmd feature list derived from the code @matt-uib?

**Comment by sebastianhaas** [comment]
> would be great to have everything osmd manages to display in this file. 

That would be great for a first visual regression test as well.

**Comment by bneumann** [comment]
Meanwhile I had a look at the visual regression test from vexflow and we could easily do that. But the problem is that the generated images should be very stable to make it work nicely

**Comment by sebastianhaas** [comment]
Is that a problem when drawing on a fixed-sized canvas and taking a screenshot from there? Or even render to a svg and rasterize that?

**Comment by bneumann** [comment]
Nº it is more that: if you add notes, decoration, stuff it will return that the image didn't match. And you can set a threshold how many pixels have to be identical.

**Comment by sebastianhaas** [comment]
Obviously, but that's the point of a visual regression test right? 🤷 Of course, if you change the source xml or add features or enhancements, you will have to "manually" update the reference image of the regression tests. But it guards against unintended visual regressions/changes. At least that's what I understood this is all about.

**Comment by matt-uib** [comment]
the visual regression tests are best suited for refactoring where everything should look exactly the same afterwards. For everything else we need to look at the output images ourselves and highlight the diff-pixels in red for example to see what has changed - this would be also nice when adding some new symbol.

**Comment by sschmidTU** [comment]
Done, these tests are already in the demo.
Note that there is some open discussion on visual regression tests in this issue.
