### ISSUE TITLE
Fix wrong x-layout for delayed ornaments

### ISSUE THREAD

**Issue by matt-uib** [opensheetmusicdisplay/opensheetmusicdisplay#286]
Some ornaments are "delayed" and shall be played at the end of the note. They shall also be rendered to the right, after the note x-pos (close to the next following note).
This somehow doesn't work currently: when delayed is true the ornaments are drawn wrongly to the left of the note - so before the note.
The problem seems to be in Vexflow, but maybe because we don't set some variable there correctly.
See "An Chloe - Mozart" measure 4.

**Comment by matt-uib** [comment]
![grafik](https://user-images.githubusercontent.com/17180665/42277304-36300e80-7f97-11e8-886c-43de6e1cd451.png)

**Comment by sschmidTU** [comment]
The issue seems to be in VexFlow, not on our end. I will create an issue on the VexFlow github.

Detailed explanation:
I recreated the code for the voice line in VexFlow and it's pretty clear that the delay is wrong for any note and setup.
You can execute and change the code here:

https://jsfiddle.net/sschmidTU/pt8njz7e/

The output should look like this (i made the second turn delayed as well to better show the bug):
![image](https://user-images.githubusercontent.com/33069673/42335695-77ff8e7c-8081-11e8-91a8-de4577dfdd39.png)

**Comment by sschmidTU** [comment]
I created an issue in the VexFlow repository:
https://github.com/0xfe/vexflow/issues/627

I'm trying to fix it myself, but i'm having compile issues with VexFlow.

**Comment by sschmidTU** [comment]
I found out that delayed ornaments in VexFlow work in narrow circumstances, namely with only one bar and no clef, key and time signatures. That's what their internal test does, and since it works, they probably didn't notice the issue.

I'll update the issue in the VexFlow repository, and continue to try to fix the problem myself, when i'm not working on issues that are more important for us.

I created a test fiddle with 4 example tests:
https://jsfiddle.net/sschmidTU/L2dcbkqy/

Test 1: VexFlow's working internal test, Works fine. (code slightly adapted)
Test 2: Test 1 with added signatures. Causes missing right-shift of ornaments on its own
Tests 3&4: Test 1 with multiple bars, a different source of missing right-shift. Tests 3 and 4 are nearly identical, 4 is for trying to fix the issue.

It looks about like this in fiddle's display:
![image](https://user-images.githubusercontent.com/33069673/42576242-39981e10-8522-11e8-828e-ac95b0d60add.png)

**Comment by sschmidTU** [comment]
This issue disappears in the skyline debug mode (debugTmpCanvas=true):
![image](https://user-images.githubusercontent.com/33069673/42897383-268e62c2-8ac0-11e8-9208-934b7677573c.png)
I made all the turns delayed here, and all are displayed correctly.

This debug mode leaves out some x-layouting methods in MusicSheetCalculator.calculate, where this bug almost certainly comes from.

The debug mode also "fixes" the grace note x-shift issue:
![image](https://user-images.githubusercontent.com/33069673/42897355-131f82e8-8ac0-11e8-9288-ce02c5dca761.png)

This shows that we have a general issue with modifier positions and x-layouting, as both ornaments and grace notes are modifiers to StaveNotes.

You can test this in the test/SkylineDebugDelayedOrnaments branch, which will immediately show this in the demo. (because "debugTmpCanvas" was set to true in SkyBottomLineCalculator)

However, this does not mean that there is not also an issue in VexFlow, as you can see from my previous comment. Though it's still interesting, that the debug mode completely fixes the positioning.

**Comment by sschmidTU** [comment]
fixed along with grace notes positioning issue by our [Vexflow PR#632](https://github.com/0xfe/vexflow/pull/632).

Now we only need a new Vexflow npm package release, so that we don't have to build Vexflow locally anymore (the PR was merged to master, but no new vexflow release yet).
