### ISSUE TITLE
Implement Cue notes

### ISSUE THREAD

**Issue by ChrisUib** [opensheetmusicdisplay/opensheetmusicdisplay#349]
**Cue notes (Stichnoten)** (, **section marks** like `[A]`)
![image](https://user-images.githubusercontent.com/33069673/44660847-3119c480-aa09-11e8-8c6f-68550e2da975.png)
(Haydn Concertante)

Cue notes should be easy, by drawing smaller Vexflow notes.
in xml: `<note><type size="cue">...` (element `type`, attribute `size`, value `cue`)

**Comment by sschmidTU** [comment]
Done.
The current state in [00941f1f](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/commit/0094f1f1dd6fce39e7ba71590f9d38425d35a748) is that we simply use StaveNotes with a smaller scale setting in Vexflow, like GraceNotes.
![image](https://user-images.githubusercontent.com/33069673/46495319-61792d80-c815-11e8-980f-f29a9e334bd8.png)

We could already simply use Vexflow GraceNotes, which is cleaner and also scales down stems and modifiers, but that currently needs a simple fix in Vexflow, which i'll make a PR for.
Then stems and accidentals will be correctly scaled:
![image](https://user-images.githubusercontent.com/33069673/46495444-b9179900-c815-11e8-8ad8-ee37d1e0fdd0.png)

I also improved the grace note code so that grace notes can have accidentals too:
![image](https://user-images.githubusercontent.com/33069673/46495605-2297a780-c816-11e8-81c7-aad2efb70536.png)

**Comment by sschmidTU** [comment]
Before this fix OSMD actually crashes for these grace note articulations:
![image](https://user-images.githubusercontent.com/33069673/46496955-90919e00-c819-11e8-840d-642523778895.png)
xml:
[grace_articulation.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/2447769/grace_articulation.zip)

**Comment by sschmidTU** [comment]
Cue notes are added as grace notes in develop now (8d1371f0c32ed68f446c0b1930c9015b00201f9e), possible since our upgrade to Vexflow 1.2.87. So, the issue should be fully resolved now.
