### ISSUE TITLE
Dividing score into pages

### ISSUE THREAD

**Issue by LearnedLately** [opensheetmusicdisplay/opensheetmusicdisplay#372]
When printing the score or saving as PDF, page breaks can occur in the middle of a staff, which is not ideal.

I created a fork that divides the score into pages using CSS 'page-break-before' and multiple "backend" objects:
https://github.com/LearnedLately/opensheetmusicdisplay/commit/13b56f184dbee4f94012a76a245b24991f60e1e6

Is this an acceptable solution or is there a better way to do this?

**Comment by sschmidTU** [comment]
Sounds good to me, could also help with perceived performance by rendering page for page, like a PDF viewer.
It surprises me that we get page breaks in the middle of a staff, because we try to only draw the amount of measures that fit the current line and window width.

@LearnedLately Thanks for the implementation! I will take a look at it and probably make a PR, at least we'll discuss this.

**Comment by bneumann** [comment]
Did you have the chance to take a look?

**Comment by sschmidTU** [comment]
I did take a look, but i'm not sure it can be merged yet. At least i would only merge it onto a feature branch, not develop.
For example, the naming of the backends is not very clear yet.

Yeah the "156 commits" is weird, it's from when i merged something onto develop, except it was only one commit really. But for some reason Github says it's 156 commits (git says it's only one).

**Comment by sschmidTU** [comment]
I suppose this is solved now with our new pagination, creation of GraphicalMusicPages, and pdf export feature (f4f890739a0e7ea2f38fbf03082685d89419e35b).
Though for #419, we probably still need an autoscale mechanism to fit something on x pages.
