### ISSUE TITLE
Cursor misplaced for whole rest

### ISSUE THREAD

**Issue by sschmidTU** [opensheetmusicdisplay/opensheetmusicdisplay#380]
![image](https://user-images.githubusercontent.com/33069673/45327151-b3040480-b556-11e8-83cc-11b0cf6884da.png)
This still happens in the cursorStepping branch, not sure why.
For a sample, try the first OSMD Function test.

**Comment by bneumann** [comment]
Ah yeah that's the whole rest thing. Switch on the staffentry bounding boxes and you see the prob.
Vexflow draws the rest note to far right that's why I manually shifted it's x position. Can't remember the code line where this happens. But there lies the root cause. It needs to update our bounding boxes as well

**Comment by matt-uib** [comment]
We had a similar problem in our apps and used the following work around:
Our bounding box needs to stay where it is at the beginning of the measure -> no shifting, so that the cursor will be placed at the start of the measure. At least the staffEntry relative position must not be shifted and shall be at the start of the measure, as other notes would be. 
Only the rendering of the symbol can be shifted which leads to a mismatch of symbol and bounding box, but thats tolerable for a full rest. 
Or maybe better just shift the graphicalVoiceEntry for the full rest to the right. This will lead to an x-elongated bounding box for the parent staffEntry, but the rest should work.
