### ISSUE TITLE
Use <stem> element to force stem direction

### ISSUE THREAD

**Issue by kenanbit** [opensheetmusicdisplay/opensheetmusicdisplay#415]
It looks like OSMD ignores the [stem element](https://usermanuals.musicxml.com/MusicXML/Content/EL-MusicXML-stem.htm) at the moment:
![screenshot_2018-10-04 screenshot](https://user-images.githubusercontent.com/6500636/46500469-e56cee80-c7f0-11e8-80fa-a4beaf00c050.png)
All of the notes in this measure have `<stem>down</stem>`, but their rendered stem direction seems to be decided based on height and voicing.

Musescore's exported musicxml seems to have the stem tag on every note, so adding this to OSMD would go a long way to making things behave similarly between them.

**Comment by sschmidTU** [comment]
Yes, we could simply force the stem direction.
Would people often use this though?

**Comment by jimutt** [comment]
If it wouldn't be too much work to use the specified stem direction (if it's provided) I think the rendering engine should follow what's specified in the mxml. For example when transcribing analog sheet music you most likely prefer to have the digital version look like the original composer intended it to. It often makes the score more readable and in some choral arrangement it can also help make room for lyrics. 

But I've already given my thoughts about this in https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/52. 

With that said I believe this shouldn't be a very high-priority feature. As long as most scores renders fine with the automatic direction it's not a very big deal.

**Comment by sschmidTU** [comment]
Stem direction is now taken by Xml by default, if specified.
I created a sample xml where this clearly improves the layout, because the second voice should be stemmed upwards as it is (unusually) above the first voice:
Before and after:
![image](https://user-images.githubusercontent.com/33069673/46890375-ef34c880-ce66-11e8-96a3-91bb8b281e2e.png)
samples: [stem_direction.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/2474375/stem_direction.zip)

This is an example from a real piece:
![image](https://user-images.githubusercontent.com/33069673/46890396-02e02f00-ce67-11e8-86d8-6519e698c1ed.png)

I also didn't notice any bad stemming in our demo samples, even though it might take hundreds of stems specified in xml now. I guess they were well layouted.

Kenan, your sample is interesting because Musescore joins the quarter and eigth stems together, which makes it impossible to tell that the upper note is a quarter note. i thought we would need a complex solution to create one voice in Vexflow to achieve the joining, but i prefer what we do now, which is separating them, so their note values are clear. Of course then the layout doesn't look very good, but i think stemming both notes down is not a good idea in this case.
![image](https://user-images.githubusercontent.com/33069673/46890611-a16c9000-ce67-11e8-9d08-a9d3369640c5.png)

@jimutt @kenanbit if you have any more suggestions on using stem direction, you're welcome to keep commenting here. (though as i said it's already implemented)

**Comment by kenanbit** [comment]
Thanks a bunch! My excerpt was just a dumb example to show how OSMD ignores stem direction, rather than an example of good layout-ing ;) I really appreciate this feature!
