### ISSUE TITLE
Write documentation for basic classes

### ISSUE THREAD

**Issue by phonicscore** [opensheetmusicdisplay/opensheetmusicdisplay#43]
as discussed on Aug. 11, 2016: Class documentation: Andrea writes basic classes

**Comment by matt-uib** [comment]
please take a look at the C# classes and copy existing comments to typescript classes (adapt old comments, if you feel like it) . Unfortunately the conversion removed them all...

**Comment by sebastianhaas** [comment]
You can preview the generated documentation on https://opensheetmusicdisplay.github.io by running `grunt docs` locally. This will render documentation to `build/docs`.

Maybe you can try to use typedoc syntax when writing documentation. It's quite obscure what annotations are being supported atm since their website is down. I suggest taking a look at their tests https://github.com/TypeStrong/typedoc/tree/master/test/converter so you can gather a quick overview of what can be done.

Some useful stuff:
```
@see [[TestClass]] @ fixtures
```
```
/**
 * This is a function with multiple arguments and a return value.
 *
 * @param paramZ - This is a string parameter.
 * @param paramG - This is a parameter flagged with any.
 *     This sentence is placed in the next line.
 *
 * @param paramA
 *   This is a **parameter** pointing to an interface.
 *
 *   ~~~
 *   var value:BaseClass = new BaseClass('test');
 *   functionWithArguments('arg', 0, value);
 *   ~~~
 *
 * @returns This is the return value of the function.
 */
```

In the end, its http://usejsdoc.org/about-getting-started.html

**Comment by bukaznik** [comment]
as of 9/13/16 @acondolu commented on 75 out of 124 classes.
