### ISSUE TITLE
OSMD in Android without Webview

### ISSUE THREAD

**Issue by dominikmeixner** [opensheetmusicdisplay/opensheetmusicdisplay#432]
Hello!

I just wanted to ask, if it is possible to somehow integrate OSMD into an Android Application without having to use a WebView.

Thanks in advance!

**Comment by sschmidTU** [comment]
Hi, i'm not sure, but couldn't you take the image rendered by OSMD (maybe even inside a hidden WebView)?
Or you could parse the SVG inserted into the HTML:
![image](https://user-images.githubusercontent.com/33069673/47266513-11e67180-d538-11e8-8802-b5e6051ac0b5.png)

Or maybe @bneumann knows something.

**Comment by dominikmeixner** [comment]
Alright, thanks alot for the quick and helpful response.

Kepp up the great work!

**Comment by willkurk** [comment]
Hi,
I am interested in this feature for a project, but I am guessing it is not in the latest version. Is that the case?
I am interested making the needed changes if that is the case. 

Thanks!

**Comment by sschmidTU** [comment]
Yes, we need a div-element to render for now, and so does Vexflow.
If you want to render OSMD without a div-element (and Webview), you'll probably have to make changes in both Vexflow and OSMD.
If you can do that, that would be great!

by the way, @bneumann set up a react-native example project, WIP:
https://github.com/opensheetmusicdisplay/react-opensheetmusicdisplay

**Comment by willkurk** [comment]
Thanks, I hadn't see that example before, it is helpful to see that. 

I think Vexflow supports it, I found an example of using Vexflow by passing an SVG context. I built it and was able to get it working, so I was thinking about extending that into OSMD. I'll take a look at that.

**Comment by sschmidTU** [comment]
Interesting. If you can find that example to pass a SVG context to Vexflow, please reference it here.
This wiki page indicates you still need a DOM element:
https://github.com/0xfe/vexflow/wiki/Using-SVG-or-HTML5-Canvas-with-VexFlow

**Comment by willkurk** [comment]
Yeah, it is here: https://github.com/panarch/react-native-vexflow-seed/blob/master/index.ios.js
Note that it is only implemented for ios in the example, but I moved to android and it worked.

**Comment by willkurk** [comment]
Scratch what I said about android vs ios, I was thinking about a different example. But my point was, it ran fine.

**Comment by sschmidTU** [comment]
Ah, of course, it simply passes the ReactNativeSVGContext to the draw methods instead of creating a Vexflow.SVGContext.
The question is whether this can completely replace the Vexflow.SVGContext, because it has a lot of other methods like setFont, setFillStyle, clearRect, beginPath, stroke, fill, etc.
Maybe the ReactNativeSVGContext and other Contexts offer all of these same methods as well.

In any case, if this works, you should add another option to options.backend, and maybe the backend data type has to be changed, because it won't be all Vexflow backends anymore.

You could create a class that extends VexFlowBackend, so you can return the context in getContext(). That's how we get the context to draw in OSMD.

By the way, the Cursor also relies on HTML elements and a zIndex, so you'll probably have to create a new Cursor as well.

Just some quick thoughts, i might look more into this, and i'm looking forward to follow your progress!

**Comment by willkurk** [comment]
Ok, thanks for the info! If I get something working, at least on a basic level, I'll be sure to share to get feedback.

**Comment by sschmidTU** [comment]
You can now generate PNGs without a browser, using a node script, see #670.
SVG export is also implememented on a branch, just needs transfer into the script, which should be easy. see #670 and #491.
