### ISSUE TITLE
Help needed with Vue integration

### ISSUE THREAD

**Issue by sandianstudio** [opensheetmusicdisplay/opensheetmusicdisplay#461]
Hello,

I've been unable to add OSMD to an existing Vue project and wondered if anyone had experience with this type of integration. I tried to add OSMD using the npm package as well as a vanilla JS approach neither of which worked for me. I'm relatively new to JS programming and haven't used Typescript at all. I would greatly appreciate any advice on how to proceed with this. Thanks in advance!

**Comment by sebastianhaas** [comment]
What module bundler are you using? Have you tried taking a look at the [webpack example project](https://github.com/opensheetmusicdisplay/webpack-usage-example)?

**Comment by sschmidTU** [comment]
There's also a [Plain Javascript example project](https://github.com/opensheetmusicdisplay/RawJavascript-usage-example). In the [Wiki](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki) you'll find a lot more information about how to use OSMD and how OSMD works internally.

We've been thinking about Vue integration, but haven't set up a Vue example yet.
Feel free to keep asking questions and telling us about your progress!

**Comment by sschmidTU** [comment]
Yes, you have to load files from a local server or via file dialog for example.
This is not Vue-related though, you can never just load local files from Javascript, because then any website could read your local hard drive. This has to do with security and CORS settings.
The [Plain Javascript example project](https://github.com/opensheetmusicdisplay/RawJavascript-usage-example) shows this.

But good to know it works for you in Vue now!

**Comment by bneumann** [comment]
Hi,

I was about to setup a example using typescript and Vue. Nothing good happened since we don't have the correct vexflow types, but that's already WIP.

But Something odd about your example @sandianstudio:

```javascript
var osmd = new OpenSheetMusicDisplay("test")

osmd.load("[http://localhost:8080/clementi.xml").then(function](http://localhost:8080/clementi.xml).then(function) () {
osmd.render()
})
```

This looks like the clementi.xml file is in your assets root. BUT later you say `../../assets/musicxml/clementi.xml` this does not work. There is a musicxml in between? Might that be a simple path error?

Cheers
