### ISSUE TITLE
Export MusicalScore.MusicSource/ScoreIO and Common.FileIO 

### ISSUE THREAD

**Issue by shishkin** [opensheetmusicdisplay/opensheetmusicdisplay#462]
In relation to #5, it would be helpful to be able to separately use `MusicSheetReader` and `MXLHelper` without `OpenSheetMusicDisplay` class.

It's also in general quite inconvenient that the whole library is bound to that class and requires a DOM element to even read the score for analysis. Maybe it would make sense to further modularize the project by extracting score model and reader from the layout and display?

**Comment by sschmidTU** [comment]
Sure, that would be nice.
Though OSMD isn't made for analysis but rendering, and this issue could be less trivial than it seems, because rendering and analysis are somewhat intertwined.
And what's the drawback to using a DOM element? Only performance, it seems to me, and that shouldn't be critical.
So, if this is easy and we have the time for it, i agree this would be a useful separation. Though i'm not sure how many people use OSMD for analysis.

I feel like we discussed something similar somewhere, but i'm not sure where.

**Comment by shishkin** [comment]
I'm new to music theory and notation. Could you please give an example of an edge-case that makes score analysis and rendering intertwined?

I'm trying to use OSMD in a react/redux or Elm Architecture style of application. I rely on OSMD to parse MusicXML to get the MusicSheet with Voices. I want to be able to do some interesting stuff with the MusicSheet model (e.g. turn on/off voices or change key) and then be able to render it in a view. So for me DOM element comes last and referencing DOM elements directly is not something react really encourages.

If OSMD was designed around data structures and functions over them, it would be much easier for me to use. Unfortunately OSMD is designed around encapsulated classes organized top-down from the rendering use case.

**Comment by sschmidTU** [comment]
I meant that for OSMD specifically, analysis and rendering are intertwined because OSMD only cares about analyzing the score when it's relevant for rendering, not for example what kind of chord a chord is (e.g. Eb7).
Also, rendering options can change the sheet model (automatic beaming changes beam information for the note).
OSMD is made for rendering, and not for convenient score analysis.
That being said, you don't need to care about the DOM element, and you can access the sheet model as much as you want (see MusicSheet class) and build your wrapper, helper and analysis functions around it.

Of course, if there's an easy change we can make for more convenient analysis, we'll gladly implement it. But separating the whole analysis from rendering is probably not an easy fit for OSMD.

**Comment by sschmidTU** [comment]
By the way, are the exports from the title of this issue still missing? I can easily add those. I forgot about the title, because you didn't mention the exports in the main text of the issue.

**Comment by matt-uib** [comment]
@shishkin actually osmd is very much designed for one use case you mentioned: turn on/off voices for rendering (if you meant that). Simply load a musicsheet, then e.g. get the first Instrument and set visible to false and then render. Then you will get the layout without this instrument.

**Comment by sschmidTU** [comment]
I thought he meant voices within a part (e.g. piano right hand playing two voices at the same time), but of course this is very good to mention.

**Comment by shishkin** [comment]
Thanks @sschmidTU for quick update and thanks @matt-uib for mentioning how to toggle instruments render.

I was indeed interested in toggling piano hands (are they handled as instruments within the same instrument group or as voices within an instrument?).

Another use case would be to add notes to the voice dynamically as well as dynamically change color of individual notes. By dynamically I mean through the parsed object model instead of manipulating MusicXML source. Could you please give me some pointers how to implement that using OSMD?

**Comment by sschmidTU** [comment]
Piano hands are added together like other parts as an **Instrument** class (which we might rename to Part),
containing **staves: Staff[]** (two in this case),
containing **voices: Voice[]** (which also has a **parent: Instrument**),
containing **voiceEntries: VoiceEntry[]** which contains notes.

So, there may be multiple, more or less direct ways to go through from notes to instruments or instruments to notes which you can consider for your implementation. I would check which one is most convenient depending on which OpenSheetMusicDisplay member you access (e.g. MusicSheet).

In MusicXML, the piano is given as a `<part>` containing `<measure>` containing `note` containing `staff id="(1|2)"` for right hand (id="1") and left hand (id="2").

**To color individual notes,** simply change the **Note.NoteheadColorXml**, which is a RGB Hexadecimal, like `#FF0000` for Red.

In theory, you should be changing **Note.NoteheadColor**, not the Xml variable, which should always remember the color set in Xml, but that's the one that's currently used for coloring, i just noticed that.
I'll fix it.

By the way, are you using the develop branch of OSMD or the NPM package? In the latter case, you'll have to wait for a new release for any changes. I'll make a new one soon anyways, because i also fixed some npm audit warnings caused by packages we don't use anymore.

**Comment by sschmidTU** [comment]
So, since OSMD 0.6.6 you should use Note.NoteheadColor instead of Note.NoteheadColorXml for modification.
Here's an example you can try in the [Demo](https://opensheetmusicdisplay.github.io/demo/) (Console):
```javascript
osmd.sheet.instruments[0].Staves[0].voices[0].voiceEntries[0].notes[0].noteheadColor = "#FF0000";
osmd.sheet.instruments[0].Staves[0].voices[0].voiceEntries[0].stemColor = "#FF0000";
osmd.render();
```

![image](https://user-images.githubusercontent.com/33069673/49475796-7b84bb80-f818-11e8-9921-f9acda5ea8a6.png)

**Comment by shishkin** [comment]
Thanks @sschmidTU! That's exactly I was looking for.

**Comment by luyunxu** [comment]
![www](https://user-images.githubusercontent.com/53037972/71159053-f718a580-227f-11ea-8b62-f5b58da4d0d7.png)
How to change the color of the marked places in the figure
