### ISSUE TITLE
Missing Vexflow Types

### ISSUE THREAD

**Issue by loganknecht** [opensheetmusicdisplay/opensheetmusicdisplay#473]
# Problem

Hey guys, love the work. Donated because I'm very much excited about what you're putting out.

I recently migrated over to typescript, and am trying to use `OpenSheetMusicDisplay`

However, I keep getting this error
```
(1,22): Could not find a declaration file for module 'vexflow'. ..../typescript_front_end/node_modules/vexflow/releases/vexflow-debug.js' implicitly has an 'any' type.
  Try `npm install @types/vexflow` if it exists or add a new declaration (.d.ts) file containing `declare module 'vexflow';`
``` 

When I read your documentation though,  you explicitly say:
```
Note that when using TypeScript, you should not install @types/vexflow in addition to OSMD, as that will cause conflicts with the definitions in OSMD/vexflow.d.ts.
```

And if I do `yarn add @types/opensheetmusicdisplay` it doesn't find the types for `OpenSheetMusicDisplay`.

Lastly if I do `yarn add @types/vexflow` it gives me this:
```
.../typescript_front_end/node_modules/opensheetmusicdisplay/build/dist/src/MusicalScore/Graphical/VexFlow/VexFlowBackend.d.ts
(17,37): Namespace 'Vex.Flow' has no exported member 'RenderContext'.
```

# `package.json`
Not sure if this will help, but here's my package.json
```
{
    "name": "my-app",
    "version": "0.1.0",
    "private": true,
    "dependencies": {
        "@types/bootstrap": "^4.1.2",
        "@types/classnames": "^2.2.6",
        "@types/jquery": "^3.3.22",
        "@types/popper.js": "^1.11.0",
        "@types/react-router-dom": "^4.3.1",
        "@types/reactstrap": "^6.4.2",
        "@types/webmidi": "^2.0.2",
        "bootstrap": "^4.1.3",
        "classnames": "^2.2.6",
        "email-validator": "^2.0.4",
        "jquery": "^3.3.1",
        "mediastream": "^0.0.5",
        "opensheetmusicdisplay": "^0.6.6",
        "popper.js": "^1.14.5",
        "react": "^16.6.3",
        "react-dom": "^16.6.3",
        "react-router-dom": "^4.3.1",
        "react-scripts-ts": "3.1.0",
        "reactstrap": "^6.5.0",
        "typings": "^2.1.1",
        "vexflow": "^1.2.87"
    },
    "scripts": {
        "start": "react-scripts-ts start",
        "build": "react-scripts-ts build",
        "test": "react-scripts-ts test --env=jsdom",
        "eject": "react-scripts-ts eject"
    },
    "devDependencies": {
        "@types/jest": "^23.3.9",
        "@types/node": "^10.12.9",
        "@types/react": "^16.7.6",
        "@types/react-dom": "^16.0.9",
        "typescript": "^3.1.6"
    }
}
```

# Request

When someone uses the [React typescript create-react-app](https://facebook.github.io/create-react-app/docs/adding-typescript) method of building a web app, how does one use `OpenSheetMusicDisplay` in typescript?

It would be cool to see this on the wiki or somewhere clearer for how to use it.

I know that your organization on git hub has [a react example](https://github.com/opensheetmusicdisplay/react-opensheetmusicdisplay), but the lack of content leaves me scratchin' my head a bit ❓ 

Would appreciate any guidance

**Comment by sschmidTU** [comment]
Hey loganknecht, thanks, nice to hear you like the project!
The React example is a work in progress by @bneumann, maybe he can tell you how to use OSMD in Typescript with create-react-app.

About your error, why do you have Vexflow as a dependency? If you only use OSMD, you don't need the Vexflow dependency.
If you use OSMD and Vexflow independently in a project, that may be a problem, because OSMD has its own definition file for Vexflow and that conflicts with the @types definitions.

We should probably unite our definitions with the @types ones (which we sometimes contribute to) and then use these. We just needed to be able to use many new types immediately without waiting for a merge, so we used our own ones.

Have you looked at the [Webpack usage example project](https://github.com/opensheetmusicdisplay/webpack-usage-example)? You don't need to add external type definitions for OSMD, they should be included in the NPM package.
Just `import { OpenSheetMusicDisplay } from "opensheetmusicdisplay";` and you should have the types.

**Comment by sschmidTU** [comment]
Yes, the @types definitions are quite outdated. Maybe we should merge ours there, so you can use Vexflow and OSMD together in Typescript with definitions. If you do that right now, you'll get conflicts because of our Vexflow definitions.

**Comment by sebastianhaas** [comment]
@sschmidTU I thought about that a while ago, I guess it will be possible to adapt our definitions in a way that they merge nicely with the DT ones.

**Comment by loganknecht** [comment]
Hey @sschmidTU,

Thank you for the catch! I've removed it! However I'm still encountering the same issue.

The work around I'm using is to steal the Vexflow `typings.d.ts` file from the `OpenSheetMusicDisplay` node module and using that in my project.

**Comment by sschmidTU** [comment]
@loganknecht What did you remove? The Vexflow dependency? I guess something else, because you still use our Vexflow typings. But good to know that that's a workaround.
It seems like for a final solution to your problem we need to merge with and use the @types definitions for Vexflow, so that there are no conflicts.

**Comment by bneumann** [comment]
@loganknecht @sschmidTU I just updated the repo. Looks good at my PC ;) 
So I still need to release it as a react component on npm but then you can use it without any other hokus pokus.

**Comment by sschmidTU** [comment]
@loganknecht good news, we use the DefinitelyTyped @types/vexflow types now! (#497)
So, no more definition conflicts when using OSMD and Vexflow together!
At least when we release OSMD 0.8.0 in the very near future ;)

We also added lots of internal OSMD class definitions to our exports, so you should be able to import and use both OSMD and Vexflow types in Typescript projects soon.
