### ISSUE TITLE
Duplet and Quadruplet problems/feature request

### ISSUE THREAD

**Issue by misterallx** [opensheetmusicdisplay/opensheetmusicdisplay#488]
Thank you very much for this tremendously helpful project! 
I would like to bring to your attention a feature I hope can be implemented.

It appears that OSMD does not yet support duplets. When I import a duplet-containing XML, the file
simply never loads to the display:
![duplet_pic](https://user-images.githubusercontent.com/33357194/52825815-4b655e80-308c-11e9-83f5-6596ec377a21.png)

It also does not yet support 8th note Quadruplets and reacts similarly. 

It appears to support quadruplet 16th notes - But it misrepresents them as eighth notes and misalignes the rhythm:
![quadrup_pic](https://user-images.githubusercontent.com/33357194/52825902-a008d980-308c-11e9-91a2-5ad554870158.png)

These would be excellent and useful features and I would be extremely grateful for them.

Again, thank you very much for this amazing contribution to music!

**Comment by matt-uib** [comment]
Dear @misterallx you are right, that OSMD doesn't do it right here, but maybe that's actually a good thing to look into this case.  
I have never seen such notation and therefore we also never checked this case.   
The reason is, that such a notation can be written simply with dotted notes, which is much more common to musicians and, to my opinion, should be used here for better readability. See the dotted versions here:
![grafik](https://user-images.githubusercontent.com/17180665/52846600-5363e380-310a-11e9-8c6d-d330817fcfcc.png)
![grafik](https://user-images.githubusercontent.com/17180665/52846614-5f4fa580-310a-11e9-94e7-f83edad7539c.png)

To what i understand duoles, quadruplets (2, 4, 8, ...) are mainly for 3 beat time signatures (3/4, 3/8).

**Comment by misterallx** [comment]
Hi @matt-uib thank you for your reply!
You're certainly correct in regards to dotted notes being a reasonable rhythmical replacement. 
For performing musicians who have to sight read (as myself), duplets are much easier to interpret in a musical context speedily. They also look a lot cleaner. Additionally, they have separate meanings - dotted notes signify syncopation to the rhythm while duplets signify true subdividing of the rhythm. I actually believe duplets are far more common than consecutive dotted notes - that has certainly been my and my colleagues' experience. In my opinion, these are important reasons to allow the engraver the choice. 
Thank you for your time!

**Comment by sschmidTU** [comment]
Completely fixed now.
![image](https://user-images.githubusercontent.com/33069673/53111557-90323f00-353d-11e9-9c17-3b8f0225241e.png)
[Duplet_Quadruplet_Tests.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/2885586/Duplet_Quadruplet_Tests.zip)

The error and beam issues were already fixed, probably due to #485,
but we gave the wrong normal notes value (notes_occupied) to Vexflow, so the layout was wrong.
This is how it looked before the most recent commit:

![image](https://user-images.githubusercontent.com/33069673/53108453-53fbe000-3537-11e9-90f5-5887ccafb1c3.png)

**Comment by sschmidTU** [comment]
@misterallx fixed, thanks for the report! Will be included in the next release, which will be soon, after some of our dependencies get updated.

**Comment by misterallx** [comment]
sschmidTU That is great news! Thank you very much for the update!
