### ISSUE TITLE
Automatically disappearing measures

### ISSUE THREAD

**Issue by abarnett12** [opensheetmusicdisplay/opensheetmusicdisplay#509]
I'm interested in using OMSD to make a site that would display MusicXML files with automatically disappearing notes/measures (similar to the ReadAhead app on iOS).

The user would select a file to read, then select a tempo and the number of beats or measures that would disappear with each beat.  Then the user would select start, and begin reading through the score.

The idea is to learn to read ahead in sheet music, by memorizing a group of notes, having them disappear, then playing them after they have disappeared while reading the next group.

Any thoughts on how and whether this could be accomplished with OMSD?  Is it possible to remove notes from the score after they have been rendered with OMSD?

**Comment by sschmidTU** [comment]
in theory, you should just be able to set a Note.PrintObject to false and call osmd.render(), and it deletes (makes transparent) the note.
I just commited a fix to develop that enables this after re-render.
The only problem is that we can't selectively re-draw single measures right now, so you'll have to take the performance hit of re-rendering the whole score.

Try this in the demo, Beethoven Geliebte piece:
```js
osmd.graphic.measureList[0][0].staffEntries[0].graphicalVoiceEntries[0].notes[0].sourceNote.PrintObject = false
osmd.render()
osmd.graphic.measureList[0][0].staffEntries[1].graphicalVoiceEntries[0].notes[0].sourceNote.PrintObject = false
osmd.render()
```
The first two lines will "make the rest disappear" (transparent), the first the following note.
![image](https://user-images.githubusercontent.com/33069673/55732393-3073f280-5a1c-11e9-909c-e3d09da7e22c.png)

The problem is that we don't really have a dynamic re-rendering system for making small changes like changing a note's color, pitch, transparency etc. without re-rendering the whole score. And changing the pitch (#501) is even impossible right now because it's not so easy to alter VexFlow StaveNotes once you've added them to Vexflow voices, formatting etc.

Of course, these would be great features, and such a dynamic re-rendering system could be a great next thing to work on.
