### ISSUE TITLE
Question about MusicPartManagerIterator Class

### ISSUE THREAD

**Issue by cymhellfire** [opensheetmusicdisplay/opensheetmusicdisplay#518]
Hi, there. I'm recently trying to implement a function to limit the **Cursor** moving range. I found **Cursor** class has dependency on **MusicPartManagerIterator** class. Seems the iterator class controls the movement range of cursor.
I've passed two timestamps to *setSelectionRange()* function of **MusicPartManager** class and invoked *reset()* function of **Cursor**. As the code shows, the cursor will get a new instance of iterator class with the given selection range. But the result is not correctly.
I use VS Code following the code executing, and I found something strange. At the line 504 of **MusicPartManagerIterator** class, the code is like this:
`if (this.currentTimeStamp >= this.manager.MusicSheet.SelectionEnd)`
Both the *currentTimeStamp* and *SelectionEnd* are **Fraction** type variable. Here using a *>=* operator to compare the value will cause a type conversion. In my debug case, these two **Fraction** have been converted to **string** to compare.

This is very strange to me. I guess this line should be used to judge if current timestamp is out of selected range. If so, I think it should use **Fraction.RealValue** to compare. Or there is some reason to do this kind of comparison.

---
Anyway, I modified this line and try to make it work. Here is my code:
` if ((this.manager.MusicSheet.SelectionEnd === undefined) ||
      (this.currentTimeStamp.RealValue >= this.manager.MusicSheet.SelectionEnd.RealValue))`
But it not work properly. In my case, the cursor won't display any longer.

I'm very curious about this code line. And I want to confirm if this is the right way to limit the cursor movement range.
Any response is appreciate, thank you.

**Comment by matt-uib** [comment]
dear @cymhellfire yes this is a bug due to translation from a different codebase. There should never be a timestamp or fraction comparison with <, <=, >, >= signs as well as + or - operations for fractions as there is no operator overloading in typescript. We have the function Fraction.lt() or Fraction.lte() for < or <= operations (and the negation of it, if you need >= or >).
And you can do it as you did it, with the real value, but for consistency i would use these functions for it.
Please check the whole code of the iterator class for other bugs like this. It seems not to be checked for that properly and not tested.

**Comment by cymhellfire** [comment]
@matt-uib , thank you for your reply.

**Comment by sschmidTU** [comment]
I added methods gte and gt to the Fraction class (negations of lt and lte), and replaced all the >= operators and others of Fractions i could find.

I looked for "timestamp >" and "timestamp <" in the project and replaced 3-4 instances.
not sure if there's a way to find all occurences of a Fraction class used with arithmetic operators, because they could have any variable names, and there's no operator overloading
