### ISSUE TITLE
Transfer/Implement StemDirectionCalculator

### ISSUE THREAD

**Issue by matt-uib** [opensheetmusicdisplay/opensheetmusicdisplay#52]
The vexflow algo currently doesn't automatically set the stem direction correctly in case of e.g. 2 Voices in a stave.

**Comment by jimutt** [comment]
Hi!
I just tried using opensheetmusicdisplay for a choral arrangement but I quickly discovered that it wasn't viable due to the stem direction issues. What's the priority for this, is it something you think you will investigate in the near future or is there some information you could share about it if someone else want to look at it for making a PR? 

Keep up the good work!

**Comment by jimutt** [comment]
It seems like you at the moment rely only on the auto_stem feature of VexFlow and don't read the stem information from the xml. Could an initial solution perhaps consist of reading the value of the `<stem>up</stem>` element and saving it as a property on the note class? Other than "up" and "down" I believe a MusicXML note can also have "none" or "double", but for those I guess you could just use auto_stem like now.

I'll probably fork it and try fiddle with that by myself tomorrow. Though it's past midnight and I really haven't got any deep MusicXML nor VexFlow knowledge so I might just be way off track. ;)

**Comment by bneumann** [comment]
I just checked, there is currently no read for the stem direction. But I think it is not to difficult to implement. Currently the vexflow stavenotes are always set with auto stem.
So we could put the stem information to the GraphicalNote and build the Stavenote accordingly

**Comment by matt-uib** [comment]
@jimutt we have already a very simple solution that should work for all the typical cases, especially the one for 2 voices: We still ignore the original xml stem direction, which works very well so far, and just let the stems of the first voice point up and the others down. I have to look into the current implementation (from our app) of this and can provide you with some code example to add this functionality.

**Comment by jimutt** [comment]
@bneumann Sounds great! 

@matt-uib  I'm sure your solution works great (and feel free to share it! Would be nice to take a look at it). But I think for the OSMD library in general it would still make sense to read the stem information from the XML as I think it's a reasonable expectation to make that the library will act upon the explicit information given in the XML rather than resorting to automatic methods for determining such features.

**Comment by sebastianhaas** [comment]
I think we should read stem directions from the XML too. In my opinion, composers/arrangers must have total control of things like that. Stem directions are not only a visual detail but may transfer important musical information. IMHO we should really respect that and not make too many assumptions or corrections (or even no assumptions at all).

**Comment by bneumann** [comment]
According to the musicXML spec the stem is optional (0..1) so we need both anyways.

**Comment by matt-uib** [comment]
@jimutt auto stem calculation works now in a first version. Please check it out in the develop branch and tell me if it works for you.
