### ISSUE TITLE
Generating SVG files from command line

### ISSUE THREAD

**Issue by tbondar** [opensheetmusicdisplay/opensheetmusicdisplay#523]
Hi,

I have a lot of MusicXML files and I need to convert them to SVG. I'm wondering what would be the best way of doing it with opensheetmusicdisplay? Basically, I'm trying to develop a script that I can run from the command line.  An npm package is provided which I successfully installed but I couldn't find any examples. Sorry if the answer is something straightforward but I'm not an expert at javascript. Any help is appreciated.

Thanks,
-Tamás

**Comment by bneumann** [comment]
Hi there,

the problem is, that opensheetmusicdisplay is made for the browser. So you can load musicxml via http request because you won't have access to the file system.
I made a branch using node some time ago (most new cool feature are not in there) which you could technically use for this. But other then that you would need to write you own small application that opens a browser window where you can either drag&drop your files or load them from a local server.
That's not the hard part. You would also want to download the created SVG afterwards which is already discussed somewhere in the issues.

I'll mark it as duplicates of #491 and #437 
These two are also included in the [feat/exporting](/opensheetmusicdisplay/opensheetmusicdisplay/tree/feat/exporting) branch

**Comment by tbondar** [comment]
Thanks for the quick response. I think I'll have to change my approach.

Can I ask why is the npm package useful then?

**Comment by bneumann** [comment]
npm is only a package manager an can be used for both, client and server applications.

**Comment by tbondar** [comment]
I see. Thank you!
