### ISSUE TITLE
leadSheet not getting properly set from constructor?

### ISSUE THREAD

**Issue by jnpdx** [opensheetmusicdisplay/opensheetmusicdisplay#526]
I'm trying to use certain display options in OSMD that look like they should be part of the leadSheet mode if I'm reading the source correctly.  For example, not displaying the measure numbers or tempo indication.  My expectation is that I would enter leadSheet mode by doing something like this during the OSMD constructor:

`this.omsd = new OpenSheetMusicDisplay(element, {
      autoResize: false,
      backend: "SVG",
      drawPartNames: false,
      setWantedStemDirectionByXml: true,
      autoBeam: false,
      disableCursor: false,
      drawingParameters: DrawingParametersEnum.leadsheet
    });`

However, doing this doesn't appear to actually set it to leadSheet mode.  The measure numbers still appear as does the tempo marking.

I've managed to override this by changing `protected get leadSheet(): boolean` in `MusicSheetCalculator.ts` to always return `true`

My question: am I setting the `leadsheet` property incorrectly in the constructor or is this a bug?

**Comment by sschmidTU** [comment]
Fixed.
You're right, the leadsheet parameter wasn't properly set on GraphicalMusicSheet when this drawing parameter was used.

By the way, I disabled the custom leadsheet lyrics positioning we had used, because it now seems to always place lyrics into the stafflines.

<img width="331" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/01fd5d70-110d-41cd-abe3-e44a2289011b">

<img width="296" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/59e3e9ec-dfae-4b9c-a970-936a8a6d1dbf">

I'm not sure what the intention behind the custom lyrics positioning for leadsheets was.
