### ISSUE TITLE
How does OSMD render the measures according to different web width?

### ISSUE THREAD

**Issue by DavoWU** [opensheetmusicdisplay/opensheetmusicdisplay#529]
Hi, there.
I am currently using OSMD to do my own project, and i found that when i change my viewport size, and OSMD will render the measures(bars) in differnet number. for example, when my view port is narrow, it shows one measure(bar) for each row. When the viewport is large, OSMD could render few measures(bars) in one row. 
So i wanna knwo which specific function that OSMD calculate the viewport width and then decide how many measures(bars ) should render in one row?

Could anyone help me please?

**Comment by sschmidTU** [comment]
that would be in MusicSystemBuilder.buildMusicSystems().
Specifically in the while loop:
```ts
// go through measures and add to system until system gets too long -> finish system and start next system.
        while (this.measureListIndex < numberOfMeasures) {
```
The comment already says how it goes: We fit measures into a staffline until the next measure doesn't fit the width anymore.
We get the width of a measure from Vexflow.

So, the wider your viewport, the more measures will fit in one line.

If you like you can adjust this to your demands, like giving an option of maximum number of measures per staff line. Although you could also simply make your viewport less wide.
Still, this could be an [OSMDOption](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/src/OpenSheetMusicDisplay/OSMDOptions.ts).

If you want to submit a PR adding such an option or another one you'd like, i'd be open for that.
I can also help you understand the code more.
And if i like the option enough i may even implement it, though i also have other current tasks for OSMD.

If you have any more questions, go ahead and ask!

**Comment by DavoWU** [comment]
Hi @sschmidTU  much appreciated :)
Yes, I would like to use OSMD to render measures (exactly 4 measures per staff, so I can know the minimal viewport width for 4 measures, and set up my viewport according to the minimal width, before I render it. ) what should I do? Does OSMD already provide that OSMDOption? If yes, could you please tell me more about that.

**Comment by sschmidTU** [comment]
@DavoWU we don't use lengths and positions from XML at all, because they're unreliable and depend on how the program that rendered the score positioned the elements, and Vexflow has its own formatting anyways, so everything will be positioned differently. We just let Vexflow do its thing. It's probably not even possible to reposition all elements in Vexflow.
When Vexflow is done formatting, we get the bounding boxes of all elements which we convert to our own coordinate system (1 OSMD unit is 10 pixels in Vexflow), and then we know where every element is and can for example enlargen the measure so that there are no lyrics overlaps, though again Vexflow does the formatting.

**Comment by sschmidTU** [comment]
You can see more about how OSMD works and the differences between OSMD and Vexflow in the [Wiki](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki).

**Comment by new1333** [comment]
Hi, how can i  set count of measures per staff line ? 

```
 while (this.measureListIndex < numberOfMeasures) {
```

now there is no such code.
