### ISSUE TITLE
how to move cursor to a note? and the playback feature, is it completed?

### ISSUE THREAD

**Issue by suziW** [opensheetmusicdisplay/opensheetmusicdisplay#538]

**Comment by sschmidTU** [comment]
The Cursor class is quite primitive right now and only supports the next() command.
So, you'd have to call next() until you have the right notes under the cursor.
We just added convenience methods VoicesUnderCursor and NotesUnderCursor to the Cursor class.
This will be in the next release which will come out in the next days, and it's on the develop branch.

The playback feature is not completed yet, though there was a recent PR #543 that's being revised and there are working demos in #258 where this issue is being discussed.

If you have further questions, feel free to ask.

**Comment by ronnycsharp** [comment]
Hi,
I am also working on a play back mode. 
Is there also the ability to step back with the cursor?
I don't see anything like this and it looks a bit difficult to me, to work with the MusicPartManagerIterator class.

Kind regards
Ronny
