### ISSUE TITLE
export music XML file

### ISSUE THREAD

**Issue by postdep** [opensheetmusicdisplay/opensheetmusicdisplay#542]
We export music XML file through final and musescore editing, then import OSMD. However, we find that the music shown is not completely consistent with the original music score! How can we ensure that they are identical? What software is used to edit and export music XML files in their demo?

**Comment by sschmidTU** [comment]
as answered on [Gitter](https://gitter.im/opensheetmusicdisplay/opensheetmusicdisplay):
we also use MuseScore for editing scores.
The thing is, MusicXML will never be displayed identically between different renderers, because it's not a format that records layout very well.
However, it should have most or ideally all of the musical elements of the original.

@postdep What are your differences in rendering? is it just layout, or are you missing a few musical elements?
note that we do not support all MusicXML music elements yet, for example pedal marks.

will re-open if there are further questions
