### ISSUE TITLE
Issue with rendering of arpeggiated chords

### ISSUE THREAD

**Issue by ronnycsharp** [opensheetmusicdisplay/opensheetmusicdisplay#546]
Hi,
I've seen there is some issue with the rendering of arpeggiated chords.
The chords are too big and they're all over the page.
I've tried it with the latest dev version.

Steps: 
I've tested it with 'Liebestraum' from Franz Liszt.
You can easily download the musicxml file from the following link by pressing
on the download button.

I've also tested it with Musescore (Music Software) and imported the musicxml file.
In MuseScore, the sheet will be displayed in a correct way.

https://musescore.com/classicman/scores/65159

Kind regards
Ronny

ps: Many thanks for such a powerful and great library. ;)

**Comment by sschmidTU** [comment]
The problem with this score is that it is very messy.
In the last few measures there are about 20 arpeggios, some of them over invisible notes in third voices in addition to arpeggios over main voices, and somewhere Vexflow makes an error rendering one of these.
I've tried a few workarounds, but it's not so easy. Maybe i can fix it some time.

**Comment by ronnycsharp** [comment]
Okay, thank you.

**Comment by sschmidTU** [comment]
@ronnycsharp a bit late, but i fixed the bug.
unfortunately this means that some previously correctly rendered arpeggios across voices don't show up anymore.
The main reason for this is that Vexflow draws the arpeggio across all notes in all voices with the default setting. So if you have a rest in another voice, the arpeggio extends to it, whether it's contained in the notes/arpeggio or not. So i'd rather not draw some arpeggios than draw wrong arpeggios.

Also, this caused that bug where arpeggios were endless, it seems like their y value wasn't correctly set by Vexflow.
This is actually not the fault of a messy score with multiple arpeggios and invisible voices (sorry!), but a flaw in Vexflow.

Interestingly, this only seems to happen when the arpeggio goes from first to second voice, not the other way around:
first to second voice:
![image](https://user-images.githubusercontent.com/33069673/70259946-8fe2f780-178f-11ea-9534-2d4f6b43ec86.png)
second to first voice:
![image](https://user-images.githubusercontent.com/33069673/70259887-70e46580-178f-11ea-8d30-fafd3925f0ad.png)

This will have to be fixed in Vexflow.

We could theoretically enable these second to first voice arpeggios to be drawn in OSMD, but again, this would also draw the arpeggio over notes not contained in the arpeggio in XML, like a rest.
