### ISSUE TITLE
How to get the HTML element id of a specific note?

### ISSUE THREAD

**Issue by Abefocuson** [opensheetmusicdisplay/opensheetmusicdisplay#549]
for example 

`<g class="vf-stavenote" id="vf-auto37980"> ... </g>`

how to get "vf-auto37980" ?

**Comment by sschmidTU** [comment]
parse it from the SVG using a regular expression.
What do you want to do with this HTML tag or id string though?
I don't see how that would be useful.

**Comment by sschmidTU** [comment]
Or use an XML Parser of course

**Comment by Abefocuson** [comment]
in this way i can get the specific note in OSMD:

osmd.sheet.sourceMeasures[0].verticalSourceStaffEntryContainers[0].staffEntries[0].voiceEntries[0].notes

and I want to get the  HTML element id of this note. Is there a method for me to call to get this id?

**Comment by sschmidTU** [comment]
No. Why would you want the html element for this? do you want to remove the child element from the SVG? That's the only use i can see for this.
This id is probably generated by the Vexflow SVG Renderer and seems to have an automatically generated id.

If you search through the HTML Elements in the Google Developer Tools, you can see the note highlighted for the vf-stavenote element.
![image](https://user-images.githubusercontent.com/33069673/61460537-3492a300-a96f-11e9-8dd0-2e1e1e267ecb.png)

But if you want to find this out programmatically, you probably need to do some bounding box calculations.
You can get the OSMD bounding box with note.PositionAndShape, though it will be different from the Vexflow bounding box. One OSMD distance unit is 10 pixels in Vexflow.

**Comment by sschmidTU** [comment]
If you just want to remove a note, call `note.noteheadColor = "#00000000"` (transparent) and `osmd.render()`.
In theory, you should be able to set `note.PrintObject = false` to make it invisible, but re-rendering for that doesn't work yet, which i can hopefully fix with the transparent color method soon.

**Comment by misterallx** [comment]
> If you just want to make a note invisible, call `note.PrintObject = false` and `osmd.render()` (included in next release).
> Or set `note.noteheadColor = "#00000000"` (transparent color)

When will the next release be available?
Thank you!

**Comment by sschmidTU** [comment]
> When will the next release be available?

hopefully in the next few days.
You should already be able to use the noteheadColor method in the current release though.

**Comment by dnlfrst** [comment]
# Use Case

I do not agree with @sschmidTU's standpoint:

> No. Why would you want the html element for this? do you want to remove the child element from the SVG? That's the only use i can see for this.

Currently, I face the need to color a specific subset of note heads upon user interaction.

# Issue

It is not possible to use `note.noteheadColor` for the above use case as this requires a call to `render()`. In most cases the time necessary to render the music sheet again is too high and disturbs the user interaction.  
Manually parsing the DOM does not seem to be feasible as I am not aware of any mapping between a specific ID and its corresponding note in the music sheet.

# Solution

It would be beneficial to have access to a note's SVG element ID to do the coloring of its head manually.

As the necessary typings of [VexFlow](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/tree/develop/src/MusicalScore/Graphical/VexFlow) are [not `export`ed](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/src/MusicalScore/Graphical/index.ts), I added the [required ones](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/src/MusicalScore/Graphical/VexFlow/VexFlowGraphicalNote.ts#L32) manually:

```ts
import { GraphicalNote } from 'opensheetmusicdisplay';

declare module 'opensheetmusicdisplay' {
  class VexFlowGraphicalNote extends GraphicalNote {
    vfnote: [any, number];
  }
}
```

To access the ID or a reference to the note's corresponding SVG element, I use:

```ts
const note: GraphicalNote = openSheetMusicDisplay.GraphicSheet.MeasureList[0][0].staffEntries[0].graphicalVoiceEntries[0].notes[0];
const vexFlowNote: VexFlowGraphicalNote = note as VexFlowGraphicalNote;

console.log(vexFlowNote.vfnote[0].getAttribute('id')); // The ID of the note's SVG element.
console.log(vexFlowNote.vfnote[0].getAttribute('el')); // The reference to the note's SVG element.
```

# Question

@sschmidTU do you validate the presented use case? If so, is there any chance to implement the access to the ID of a note's SVG element in a more sophisticated way?

**Comment by sschmidTU** [comment]
@dnlfrst thank you for the input! the use case is definitely valid, as well as the performance concerns.
The problem is that both OSMD and Vexflow are not well equipped for fast interactive rendering like coloring notes with a click at runtime. For any shape changes (instead of just color) we would have to erase at least one measure and redraw it. There's discussion of this elsewhere, e.g. #509.

Your SVG manipulation is a solution for fast recoloring of notes, but you have to admit it's a bit of a hack, because it manipulates low level graphical information, while OSMD tries to solve rendering issues on a high level using Vexflow and its own rendering methods.
Still, if that's what OSMD users need, we should think about providing it.

I've made a commit that exports the Vexflow classes, so you won't have to add it manually anymore.
These not being exported was just an oversight, because the create-ts-index script we use mysteriously leaves out a few classes or folders.

As for methods that get the note's SVG element [id], you have already written them:
```typescript
    public getSVGId(): string {
        return this.vfnote[0].getAttribute("id");
    }

    public getSVGElement(): SVGElement {
        return this.vfnote[0].getAttribute("el");
    }
```
By the way, is SVGElement the correct Typescript class here? I've never used it.

So, for your purposes, you could just add these methods in your code somewhere as a meta-API, and you wouldn't need them from OSMD.

But we've thought about it and wouldn't mind adding these methods to VexFlowGraphicalNote. People who use this to manipulate the SVG should know that they're engaging in low level hacks, and then we won't stop them.

**Comment by sschmidTU** [comment]
getSVGElement().constructor.name says it's SVGGElement, so i'd give it that type.

**Comment by dnlfrst** [comment]
Thank you for the in-depth answer and your continuous efforts, @sschmidTU!

> The problem is that both OSMD and Vexflow are not well equipped for fast interactive re-rendering like coloring notes with a click at runtime.

Yes, this probably depends on #352 and #396?

> Your SVG manipulation is a solution for fast recoloring of notes, though you have to admit it's a bit of a hack, because it manipulates low level graphical information, while OSMD tries to solve rendering issues on a high level using Vexflow and its own rendering methods.

Totally a hack, it does not seem right to fiddle with the generated SVG elements.

> I've made a commit that exports the VexFlowGraphical classes, so you won't have to export VexFlowGraphicalNote manually anymore.
> (These not being exported was just an oversight, because the create-ts-index script we use mysteriously leaves out a few classes and folders)

That's great, thank you!

> But we've thought about it and wouldn't mind adding these methods to VexFlowGraphicalNote. 

Nice, I noticed your commit (3dbe83b) for that.

> By the way, i'm not sure how one could access the SVG element "in a more sophisticated way", but since as i said this is a hack anyways with simple code, i don't see a reason to.

Probably not phrased correctly, I was referring to some way that does not involve adding custom types or even completely go without them. However, I think that's covered with f0f63fd and 3dbe83b.

**Comment by sschmidTU** [comment]
> > The problem is that both OSMD and Vexflow are not well equipped for fast interactive re-rendering like coloring notes with a click at runtime.
> 
> Yes, this probably depends on #352 and #396?

I wouldn't say that the solution for fast interactive rendering is performance optimization exactly, rather it's a localized (re-)rendering system that can re-render one or two measures at a time. Because Vexflow takes most of the rendering time, the best performance optimization is rendering less.
Also, if Vexflow properly supported re-rendering of already rendered elements, we wouldn't need performance optimization either.
But yes, one or the other would be a great step for OSMD, because many use it for interactive purposes.

**Comment by yuvalha96** [comment]
Hi @sschmidTU , I'm using Typescript and OSMD version 1.7.0 and I have an issue with using `getSVGGElement()`. 
I'm getting "Property 'getSVGElement' does not exist on type 'GraphicalNote'."

**Comment by sschmidTU** [comment]
@yuvalha96 Hi, you need to cast it to `VexFlowGraphicalNote` :)

```typescript
(note as VexFlowGraphicalNote).getSVGGElement()
```

**Comment by yuvalha96** [comment]
Thanks for the quick response!
I'll add for anyone who encounters this in the future, there's another casting needed:
`(note as VexFlowGraphicalNote).getSVGGElement().children[0].children[1].children[0] as HTMLElement).style.fill`
since the svgElement returns Element Collection, and in order to access style parameter it needs to be HTMLElement.
