### ISSUE TITLE
Get volume information from notes under cursor

### ISSUE THREAD

**Issue by ronnycsharp** [opensheetmusicdisplay/opensheetmusicdisplay#550]
Hi,
since a few hours, I am searching for a way to get the volume information from a note.
Like ppp, or fff and so on. In the musicxml file, these kind of information is in the measure-node. Is there a way to get these information from the current cursor.

`
    <measure ...>
     <direction placement="below">
        <direction-type>
          <dynamics default-x="3.29" default-y="-80.00" relative-x="-8.12" relative-y="7.40">
            <pp/>
            </dynamics>
          </direction-type>
        <staff>1</staff>
        <sound dynamics="36.67"/>
        </direction>
       </measure>
`

Kind regards
Ronny

**Comment by ronnycsharp** [comment]
I found a solution. 

osmd.cursor.iterator.currentMeasure.StaffLinkedExpressions[0][0].instantaneousDynamic

The property DynEnum includes the Dynamic Information.

Regards
Ronny

**Comment by sschmidTU** [comment]
good to know, thanks for sharing!

**Comment by matt-uib** [comment]
@ronnycsharp actually for that you should use:
osmd.cursor.iterator.activeDynamicExpressions
There you have the currently operative dynamic at your disposal for every staff line.
So for the first staff line, use:  osmd.cursor.iterator.activeDynamicExpressions[0]
which might then be of type: 
InstantaneousDynamicExpression (like pp, f, ...) or
ContinuousDynamicExpression (cresc., hairpins, ...)

**Comment by JanVeb** [comment]
osmd.cursor.iterator.activeDynamicExpressions[0]
Is a volume that's set in score for next notes in line until next  <sound dynamics="71.11"/> is set in score?

I've tried to play around with this, but it seems that this doesn't change volume of played notes, is this still to be implemented or?

**Comment by JanVeb** [comment]
Neither of these two lines seem to work consistently, though for now I only tested it in one score, will provide update after further testing.
osmd.cursor.iterator.activeDynamicExpressions[0]
osmd.cursor.iterator.currentMeasure.StaffLinkedExpressions[0][0].instantaneousDynamic

In provided score file, from 2812 played notes (repeats included), 272 notes are missing volume info, instead returned value is NaN. These notes are in measures 38-43 and 56-60 


[WA_Mozart_Marche_Turque_Turkish_March_fingered.mxl.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/9594164/WA_Mozart_Marche_Turque_Turkish_March_fingered.mxl.zip)


Workaround for now, after every valid volume value I save it to:
correctVolume = volume;

then when volume is NaN, then I provide correctVolume instead of volume, and of course then I don't update correctVolume, works well after initial testing, need to run further tests.

Will provide video of score in question, as it often changes volume so its good example to showcase this workaround for now

**Comment by JanVeb** [comment]
https://youtu.be/3FaLtg0Soxc

**Comment by JanVeb** [comment]
In next two files im getting error: VM8243:15 Uncaught TypeError: Cannot read properties of undefined (reading 'soundDynamic')
[Rimsky Korsakov ''Flight Of the Bumblebee''.mxl.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/9594322/Rimsky.Korsakov.Flight.Of.the.Bumblebee.mxl.zip)
[Fur_Elise_Easy_Piano.xml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/9594323/Fur_Elise_Easy_Piano.xml.zip)

In this file it works, but again 12 notes out of 104 returned value for soundDynamic is NaN
[Fur_Elise_Easy_Piano.xml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/9594324/Fur_Elise_Easy_Piano.xml.zip)
