### ISSUE TITLE
Refactor/Unify grace note code

### ISSUE THREAD

**Issue by matt-uib** [opensheetmusicdisplay/opensheetmusicdisplay#56]
add "isGrace" flag in VoiceEntry (GraphicalVoiceEntry), as always all notes of one voice are grace notes or not.
Remove all current isGrace method arguments or flags and use the new flag in the VoiceEntry. 
In most methods where an isGrace argument is present, there is a note argument -> use note.parentVoiceEntry.isGrace instead.

**Comment by matt-uib** [comment]
Move also Note.GraceNoteSlash flag into VoiceEntry.

**Comment by sschmidTU** [comment]
The refactor should be mostly unproblematic, i surveyed the use of "grace" in the code. There is a lot of code explicitly for grace notes.

Sometimes, methods only get a GraphicalNote + isGrace, not a GraphicalVoiceEntry, so one could think about adding isGrace() to a GraphicalNote. But so far in these cases the grace note variables aren't used yet, for example in VexFlowGraphicalSymbolFactory.addGraphicalAccidental():

```
 public addGraphicalAccidental(graphicalNote: GraphicalNote, pitch: Pitch, grace: boolean, graceScalingFactor: number): void {
        const note: VexFlowGraphicalNote = (graphicalNote as VexFlowGraphicalNote);
        note.setPitch(pitch);
    }
```

i'm creating a refactor/isGrace branch, adding a isGrace flag to [Graphical]VoiceEntry, etc.

**Comment by matt-uib** [comment]
@sschmidTU yes, remove all unused grace method arguments. Also remove the graceScalingFactor arguments - this shall anyway be a fixed number in the engraving rules (where all the fixed layout parameters are defined) if used at all...

**Comment by matt-uib** [comment]
The InstrumentReader should not be changed by the refactoring. Also the VoiceGenerator.read() method. But then the changes can start :-)

**Comment by matt-uib** [comment]
This is the first step: adding the VoiceEntry.isGrace bool flag and removing the current method arguments.
This should be possible to change.
The next step will be then removing grace-VoiceEntries and grace-StaffEntries...

**Comment by sschmidTU** [comment]
state of refactor:
- [x] add "isGrace" flag in VoiceEntry
- [x] remove all current isGrace method arguments or flags and use the new flag in the VoiceEntry
- [x] move Note.GraceNoteSlash flag into VoiceEntry
- [x] remove all unused grace method arguments. Also remove the graceScalingFactor
- [x] remove special GraceBeam handling and simply handle as normal beam.
- [ ] remove GraceVoiceEntries
- [ ] remove GraceStaffEntries
- [ ] remove special Grace Slur handling and simply handle as normal slur

I couldn't find any code for grace slurs in my branch, and since slurs are still WIP, maybe we should cut the grace slur refactor for now, unless i'm missing something.

I'm working on the GraceVoiceEntries/GraceStaffEntries[Before/After] removal, but i still have to decide how to adapt VoiceGenerator.handleGraceNote(), also regarding questions in #293.

**Comment by matt-uib** [comment]
@sschmidTU great!
for VoiceGenerator.handleGraceNote():
I think we can remove this if statement and handleGraceNote() here -> always push to the currentVoiceEntry (which has to be created now in Instrument Reader also for grace notes.)
```
if (!graceNote) {
      this.currentVoiceEntry.Notes.push(note);
    } else {
      this.handleGraceNote(node, note);
    }
```
and remove the whole function handleGraceNote(), 
But:
The grace-slash reading code in handleGraceNote() has to be migrated to addSingleNote().

**Comment by matt-uib** [comment]
The problem will be, what musical timestamp to set for the new VoiceEntry which has to be generated for a grace note. But let's try for now, as it will be now anyway: the grace note has zero length and will be at the same timestamp as the following main voiceEntry.
