### ISSUE TITLE
Backend option ‘Canvas’ is not working (raw JS)

### ISSUE THREAD

**Issue by megatronofdeath3000** [opensheetmusicdisplay/opensheetmusicdisplay#570]
Hello dear OSMD-developers and community!  

I tested loading of my XML-file through OSMD-demo page with Canvas renderer and it worked fine. But when I try to render this file in my application the canvas is unfortunately empty.
I’m using RawJavascript-example and that’s what I exactly do:
- add this code to index.html:
//write some tags without opening brackets cause of Preview bugs`
div id="osmdCanvas" />
input type="file" id="files" name="files[]" multiple />
output id="list"></output>
<script src="js/fileSelectAndLoadOSMD.js"></script>`

- define variable in file fileSelectAndLoadOSMD.js like that:
`var openSheetMusicDisplay = new opensheetmusicdisplay.OpenSheetMusicDisplay("osmdCanvas", { backend: "Canvas", drawingParameters: "compact", drawPartNames: false});`

- if I don’t set backend-option then score renders as SVG well.

What am I doing wrong? Why I can’t render score in canvas?
I've attached my XML-file.

[example.xml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3609195/example.xml.zip)

Best Regards!

**Comment by matt-uib** [comment]
@megatronofdeath3000 if i remember correctly the canvas rendering does not work correctly for larger musicxml files where the height of the page gets too long.
Do you really need the canvas renderer? SVG should work fine.

**Comment by sschmidTU** [comment]
Actually the Canvas Renderer works for me for that sample, i was just about to write a comment.
<img src="https://user-images.githubusercontent.com/33069673/64856863-5339b100-d623-11e9-8c91-b20ecd27db99.png" height="300">

This is from the RawJavascript repository, all i did was set the renderer to Canvas in fileSelectAndLoadOSMD.js.

I also just pushed a small commit to the RawJavascript repo, now you can access the osmd object there in the Browser console as well.
So, I'd recommend comparing that sample project to your code for differences, because there must be a difference that causes your problem.
I'd be willing to take a closer look at your specific case, can you maybe provide more of the code that you use?
By the way, what are those "Preview bugs" that you're preventing with your HTML code there?

**Comment by sschmidTU** [comment]
Oh and also, open the console to see if there's an error message from OSMD.

**Comment by megatronofdeath3000** [comment]
Thank you for quick response @matt-uib and @sschmidTU !
@sschmidTU Empirically I found that problem is in simultaneous use of that options:
	drawingParameters: "compact",
	drawPartNames: false
Furthermore when I set render option to "svg" the svg-element on the page is trimmed in height. And it has this default style:
svg[Attributes Style] {
    width: 1424;
    height: 100%;
}
Maybe I should not use these options at the same time...

@matt-uib Perhaps I will look into using of SVG because it will avoid resolution troubles. But I really don't understand for now what will be better for animation tasks - SVG or Canvas. Further I planned to use OSMD for score playback in some frame but I think it's not the topic of this issue.

PS. @sschmidTU preview bugs that I mentioned earlier I think are Git bugs - when I click Preview to preview my issue I don’t see some tags :(

**Comment by sschmidTU** [comment]
Sorry for the late response, i'm working on a few improvements i noticed from your sample,
i thought i could push them quickly, but then i got held up.
Also, very interesting find about these options, i hadn't tried them in combination. Setting both seems to cause a bug. That should be fixed too. In the meantime, you should not set both options i guess ;) though i think you can set most options of compact mode separately.
For playback, click events and note timing there are multiple discussion threads already, have a look around.

**Comment by sschmidTU** [comment]
@megatronofdeath3000 are you sure the problem was setting `drawingParameters: "compact" and `drawPartNames = false` simultaneously?
Because i just tried it in the demo and it works:
![image](https://user-images.githubusercontent.com/33069673/65066680-210eb300-d985-11e9-8304-1015a858959f.png)

All i did was replace the `new OpenSheetMusicDisplay()` in the demo with this:
```js
openSheetMusicDisplay = new OpenSheetMusicDisplay(canvas, {
    drawingParameters: "compact", // try compact (instead of default)
    drawPartNames: false, // try false
});
```

**Comment by megatronofdeath3000** [comment]
@sschmidTU I experimented in my project - I made a repository with my example. You may look into it: https://github.com/megatronofdeath3000/OSMD_example
Thanks for your help!

**Comment by sschmidTU** [comment]
Your backend was set to svg in the OSMD constructor. you need to enter "canvas" there instead of "svg".
https://github.com/megatronofdeath3000/OSMD_example/blob/master/fileSelectAndLoadOSMD.js#L24

if you have any other questions, feel free to ask!
