### ISSUE TITLE
Bugs with 8va (SkyBottomLineCalculator.getMinInRange)

### ISSUE THREAD

**Issue by JanvyHung** [opensheetmusicdisplay/opensheetmusicdisplay#575]
![延音线八度bug](https://user-images.githubusercontent.com/50696364/66618311-3b961e00-ec0b-11e9-88ba-8664bda0f2ad.PNG)
![延音线八度示例](https://user-images.githubusercontent.com/50696364/66618317-43ee5900-ec0b-11e9-8d60-49573cba96a0.PNG)
![下行八度bug](https://user-images.githubusercontent.com/50696364/66618326-4ea8ee00-ec0b-11e9-9b1e-8daf717b8ac8.PNG)
There are some bugs when 8va used in the notes whith ties or the notes in the 2nd stave , how can I solve the problem ?

**Comment by sschmidTU** [comment]
I don't know, it works for me. Please provide samples (XMLs) next time.
Are you on the latest state of develop? It even works in the public demo for me:
![image](https://user-images.githubusercontent.com/33069673/66638531-6ab18d00-ec15-11e9-880b-dfa1c2a8c88b.png)
https://opensheetmusicdisplay.github.io/demo/

Which (sheet music) program do you use to export the XML? We mainly use MuseScore. Maybe your program exports to XML in ways we don't expect. That's why a sample would be good to have.

My samples:
[8va_slur_samples_working.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3716541/8va_slur_samples_working.zip)

**Comment by JanvyHung** [comment]
Here are the samples with bugs.Note that the slur of note is tie ,not a common slur, and I used musescore to edit. 

[8va_bug_examples.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3720243/8va_bug_examples.zip)

**Comment by sschmidTU** [comment]
I found the bug in the SkyBottomLineCalculator and fixed it.

Array.slice does not include the end index, so if we slice on the same start and end index, it returns an empty array (`[1, 1, 1].slice(0, 0) = []`), and Math.min on it returns Infinity.
So to include the end index, we need to slice (start, end + 1).

![image](https://user-images.githubusercontent.com/33069673/66932356-c0cc6900-f037-11e9-978b-e1159beecb15.png)

**Comment by thinker3** [comment]
I got the same error message, but I don't know the detail, please check the sample file.
[千与千寻片尾.xml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3920844/xml.zip)
