### ISSUE TITLE
Octave Shift doesn't display correctly over multiple lines/systems

### ISSUE THREAD

**Issue by JanvyHung** [opensheetmusicdisplay/opensheetmusicdisplay#591]
I found some display problems when I resize the developer tool window in chrome :
1、The barline between measure 12 and measure 13 may sometimes be protruding but other time is normal ;
![barline1](https://user-images.githubusercontent.com/50696364/67173256-b7a11a80-f3f0-11e9-8926-e47c9cdca565.png)
 
![barline2](https://user-images.githubusercontent.com/50696364/67173267-bec82880-f3f0-11e9-8836-8b35ded74f8f.png)
2、The octave-shift from measure 36 to measure 40 may sometimes partially disappear.
![octaveshift1](https://user-images.githubusercontent.com/50696364/67173623-e23fa300-f3f1-11e9-9c10-1de2b701ffe3.png)
![octaveshift2](https://user-images.githubusercontent.com/50696364/67173626-e4a1fd00-f3f1-11e9-978c-8ebcac0e87e2.png)
Here is my sample file.
[48.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3748899/48.zip)
Looking forward to your answer. Thank you very much.

**Comment by JanvyHung** [comment]
One more question , some slurs' placement is above in musescore ,but it turns into below in OSMD.

**Comment by DavoWU** [comment]
I also find this problem, and I ask on #586 ,  I notice that especially there is octave-shift tag in that measure, and the barline will pop up

**Comment by fredmeister77** [comment]
Github didn't seem to auto-link for some reason. This should be resolved as part of PR#777

**Comment by sschmidTU** [comment]
Fixed in PR #777.

This sample shows the fix well:
Before:
![image](https://user-images.githubusercontent.com/33069673/97759494-76fad780-1b01-11eb-8611-8deb2e448185.png)

After:
![image](https://user-images.githubusercontent.com/33069673/97759549-8aa63e00-1b01-11eb-8083-e921fb338c55.png)
[8va_many_lines.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5467801/8va_many_lines.musicxml.zip)

The issue of multiple octave shifts not being united to a single bracket is a different issue, the score is not exported well to XML, we could in the future add a feature to unify successive octave shift brackets.
