### ISSUE TITLE
About browser adaptation

### ISSUE THREAD

**Issue by TheBrightestStarInTheNightSky** [opensheetmusicdisplay/opensheetmusicdisplay#598]
I have a question about browser adaptation.
When I hid some of the rest in the score, it worked fine in Google, but it showed up in IE, as it did in android。

**Comment by TheBrightestStarInTheNightSky** [comment]
[screenshots.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3765570/screenshots.zip)
I intercepted museScore, Chrome, IE and Android webView for you

**Comment by TheBrightestStarInTheNightSky** [comment]
> how did you hide the rest? the ideal way is by setting `print-object="no"` in the XML or `note.PrintObject = false;` in the code.
> We don't test on IE and i'm not surprised, but Android is something we care about, and it should ideally render the same way.
> Can you give xml samples and screenshots?

I intercepted museScore, Chrome, IE and Android webView for you
[screenshots.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3765574/screenshots.zip)

**Comment by TheBrightestStarInTheNightSky** [comment]
I intercepted museScore, Chrome, IE and Android webView for you
[screenshots.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3765577/screenshots.zip)

**Comment by sebastianhaas** [comment]
Android WebView is using Chromium since 4.4. or something like that. On older devices, it is updated to Chromium via an additional package, so I'd say you can actually rely on Chromium being used for WebViews on Android. That in mind, I doubt that there is a difference between Chromium and the final proprietary user agent that could lead to the outlined differences.

Do you run the same code on the mobile and desktop? How come there is a yellow background on Android then?

**Comment by TheBrightestStarInTheNightSky** [comment]
Yes, white background is the screenshots in osmd demo, yellow background is running in my local project, my project is based on local osmd framework developed, the same XML file, when I run on the Google browser open localHost: 8000 pages, hidden symbol is not shown in the XML, but the same case, is shown in the IE browser and android webView.

**Comment by TheBrightestStarInTheNightSky** [comment]
Yes, the screenshot with white background is running in osmd demo, and the yellow background is running in my local project, which is developed based on osmd framework. The same XML file, when I ran it on the Google localHost: 8000 web page, the symbols hidden in the XML were not displayed, but in the same case, it was displayed in Internet explorer and android webView.

**Comment by sschmidTU** [comment]
are you sure you used the same OSMD version and sample on Android?
Can you give a musicxml sample?

When a note is invisible, it has `print-object="no"` in the XML, we set Note.PrintObject = false, which sets `notehead.setStyle({ fillStyle: "#00000000"})` which is transparent color in Vexflow.
(`in GraphicalVoiceEntry.color()`)

There is a workaround for this to never display invisible notes, by creating GhostNotes instead of StaveNotes in VexflowMeasure.graphicalMeasureCreatedCalculations, but that can lead to formatting issues.

**Comment by TheBrightestStarInTheNightSky** [comment]
Yes, I have updated the latest osmd code locally, and the android side has also been updated. I packed the XML file for you

[screenshots.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3769998/screenshots.zip)

**Comment by TheBrightestStarInTheNightSky** [comment]
I'm sorry, but I'm using Microsoft Edge instead of IE, which is what the screenshot says

**Comment by sschmidTU** [comment]
Thank you for the sample!
Basically, we don't support Microsoft Edge or IE right now, because it always renders differently and there is noone actively testing on it.
But Android should render the same, as sebastianhaas said, that's weird. Unfortunately, i don't have an Android testing environment right now either.
If you're modifying OSMD anyways, you can use the old method in `VexflowMeasure.graphicalMeasureCreatedCalculations`, as i said above, it's still there, commented.

**Comment by TheBrightestStarInTheNightSky** [comment]
Probably related to the version of android, the example I provided does not show a hidden pause in android API 28, but it does in API26. I downloaded PhonicScore 2.4.1 and uploaded my local musicxml to it. Unfortunately, the hidden rest is still visible. I hope this will give you some inspiration

**Comment by sebastianhaas** [comment]
Can you please provide us with information about the JS/rendering engine used on your test devices? As mentioned above, the WebView on Android varies depending on the packages installed, different vendors etc.

Should be easy to extract with JS only. Once we have the exact chrome versions, we can take a look.

**Comment by TheBrightestStarInTheNightSky** [comment]
My device is Android 8.1.0 and the webView version is 71.0.3578.99

**Comment by sebastianhaas** [comment]
Can you please update to the latest version, which seems to be `78.0.3904.62` at this time and see if the issue persists?

**Comment by sebastianhaas** [comment]
I have an Android emulator running 8.0 (API level 26) with all updates installed, which gives me Chrome `78.0.3904.62` and also WebView `78.0.3904.62`- I cannot see the issue you are describing.

It is rather hard to get the webview running you have described, so even if I did get it running, I don't really see a point in fixing OSMD for an obsolete browser. So please check if you can get the update and if that resolves your problems.

**Comment by TheBrightestStarInTheNightSky** [comment]
If you don't mind, what emulator are you using? I recently used Genymontion to simulate Android devices, but the version of Android system webView is too low. I tried to install android-system-webview-78.0.3904.62.apk into my emulator, but it will cause an exception to my emulator. I don't know how you updated the webView version, can you give me some guidance

**Comment by sebastianhaas** [comment]
I just used a emulated device with Google Play Services so that I could upgrade via the play store. Those images are available from Android Studio.

**Comment by sschmidTU** [comment]
this can be reopened if there's further questions.
