### ISSUE TITLE
Chords not displayed or shifted when not above a note

### ISSUE THREAD

**Issue by AlbertHart** [opensheetmusicdisplay/opensheetmusicdisplay#599]
Here is a score in Sibleius imported into OSMD

The chord without a not in measure 2 is lost. 
I split the notes in measure 4 to get the chord to display.

I checked the XML output from Sibelius and the <harmony> for the second chord in mesure 2 is in it.

Measure 2 has no second <note> entry, but it does provide:

```
    <backup>
    <duration>512</duration>
   </backup>
```

Which, presumably, tells MusicXML where to put the second chord.

Having more than one chord in a measure over a single note is fairly common in Jazz.

![image](https://user-images.githubusercontent.com/8965352/67406272-19898d80-f573-11e9-8c41-af7c6cd817e8.png)

I tried a similar layout from MuseScore with the same result - except that it grabbed the wrong chord from the MuseScore export.

![image](https://user-images.githubusercontent.com/8965352/67407104-3ffbf880-f574-11e9-9db9-c9a2e2d656ba.png)

![image](https://user-images.githubusercontent.com/8965352/67407013-180c9500-f574-11e9-8ed3-50ae4c83f4bb.png)

**Comment by sschmidTU** [comment]
True, we haven't yet implemented rendering a chord symbol without a note under it, but it shouldn't be too hard.

This could be something we do very soon, because it's really not too uncommon, e.g. also in the christmas song Alle Jahre wieder, bar 6.
sample of bars 5-6:
[alle_jahre_wieder_5-6.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3763191/alle_jahre_wieder_5-6.musicxml.zip)

**Comment by AlbertHart** [comment]
Thanks.

This will save me a lot of trouble = entering dummy slur notes when chords are missing.

**Comment by sschmidTU** [comment]
Looking into this.
First, i saved all chords in InstrumentReader and prevented multiple chords on one note overwriting each other, so at least we display the first chord on the note instead of the last.

So, an A7 B7 on a single note (MuseScore):
![image](https://user-images.githubusercontent.com/33069673/70175546-361ef680-16d7-11ea-9afa-f68e3a99e4d2.png)

now shows A7 instead of B7 in OSMD, like previously:
![image](https://user-images.githubusercontent.com/33069673/70175575-459e3f80-16d7-11ea-8e55-0626805be9b4.png)

Next, I'll save all chords in a staffEntry and try to show all of them, like in MuseScore.

**Comment by sschmidTU** [comment]
Basic display of multiple chord symbols over one note/staff entry is implemented:

![image](https://user-images.githubusercontent.com/33069673/70180002-68cced00-16df-11ea-9bf3-3e52a99a8634.png)

Now I'm adding a simple method to space the symbols using the available space.
My idea:
Check the remaining space for chords, which is the space until the next StaffEntry if there is one in the measure, or the end of the measure if there's none.
Then, space the chord symbols equidistant by the remaining space, minus the width of the chordsymbols, divided by number of chordsymbols. if there's not enough space (result << 1), use minimal spacing.
Or, if there's not enough space, we could extend the measure, just like the lyrics spacing currently works.
Ideally, these two systems should use the same spacing method of course, same principles.

**Comment by sschmidTU** [comment]
This issue is fixed, chord spacing will be dealt with in #597.

**Comment by TormodKv** [comment]
I'm still having trouble with this.
This is my score in sibelius: 
![image](https://user-images.githubusercontent.com/61188430/186606203-751efe91-1778-47f5-aab7-25cde5b58e80.png)
And here's how it looks in OSMD (demo site)
![image](https://user-images.githubusercontent.com/61188430/186606642-07ff40af-db2a-4490-8e89-1be6b8257d4b.png)

Here's the files:
[Test Score.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/9422639/Test.Score.zip)
 
 It isn't exactly the same issue as earlier, since all the chords are represented, but still misplaced 😅

**Comment by TormodKv** [comment]
I tried with and without dolet and seems like i get the exact same reuslt both in musescore and in OSMD.
I got it to work in musescore, but for some reason it appeared on page 2 🤔

![image](https://user-images.githubusercontent.com/61188430/189916244-86438534-bcfb-4675-ae45-50e0b42764e4.png)

But it did however render it correctly, so i don't think sibelius is at fault here
Here's the same score with dolet export included:
[Testscore with dolet.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/9557632/Testscore.with.dolet.zip)

**Comment by sschmidTU** [comment]
@TormodKv Oh, you're right, the first "test score" you shared also does render on page 2. Musescore didn't show any indication that there was a second page. Still odd, but the MusicXML seems to be workable.
Unfortunately this is a tricky issue layout-wise when there is no note to anchor the chord to, or when the chord doesn't start on the beginning of a note. Hopefully we can fix it at some point.

**Comment by sschmidTU** [comment]
Fixed in #1446.

<img width="201" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/df2a8a4b-07ed-440f-bc3e-ec42ed977a96">
