### ISSUE TITLE
svg is a const

### ISSUE THREAD

**Issue by AlbertHart** [opensheetmusicdisplay/opensheetmusicdisplay#608]
in #594, I am experiencing a problem where a second render to a second container overwrites the svg from the original render and original container.

I see that SvgVexFlowBackend declares its 'svg' as a const, which means it can not then be changed.

```
public clear(): void {
        if (!this.ctx) {
            return;
        }
        const { svg } = this.ctx;
        // removes all children from the SVG element,
        // effectively clearing the SVG viewport
        while (svg.lastChild) {
            svg.removeChild(svg.lastChild);
        }
    }
```

If 'svg' was saved in the context, rather than as a const, then each render context could use its own svg.

Perhaps svg would work as a local variable here? 
Or as something stored in "osmd"?

Everything appears properly in my second container, but it appears in the first container as well.

I seem to be having a similar problem when i use backend: "canvas" instead of svg

**Comment by sschmidTU** [comment]
@AlbertHart I changed the declaration of SVG. Could you test if it's still static between OSMD instances?
Now it should in any case not be static between osmd instances, as far as i understand it, because svg is only declared locally in this function.
I don't know what that `const { svg }` was for anyways, because it automatically changes the type of this.ctx to SVGElement.
