### ISSUE TITLE
Whole Rest Bounding Box wrong

### ISSUE THREAD

**Issue by Abefocuson** [opensheetmusicdisplay/opensheetmusicdisplay#609]
In 4/3 beat music sheet：
divisions is 1
if rest's duration is 3,its VexFlowStaffEntry is not in the right position.

![image](https://user-images.githubusercontent.com/1825445/67839569-e7f26280-fb2e-11e9-9204-cf1dddd1177c.png)

Musicxml file please go to the attachment.
[test.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3787558/test.zip)

**Comment by sschmidTU** [comment]
BoundingBox is correct for me for the sample you provided, with current develop version and 0.7.1d tag.
Which version of OSMD are you using? Do you run the local demo?
![image](https://user-images.githubusercontent.com/33069673/70081153-4c11b600-1608-11ea-94cf-32641811a8f0.png)
(in the local demo, click Show Bounding Box for -> StaffEntries)
[whole_rest_bbox_test.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3918219/whole_rest_bbox_test.musicxml.zip)

**Comment by TheBrightestStarInTheNightSky** [comment]
After I updated the develop branch code, the test found that the problem was not completely solved. In the test muxicxml provided by you, Clementi, m-sonatina op. 36, section 13 of No1 pt.2, section Haydn, section 28 of j-concertante Cello, and my musicxml, the problem still appeared


![question](https://user-images.githubusercontent.com/37290585/70107085-8323ae00-1680-11ea-96cd-17edeaa3460c.png)
![question1](https://user-images.githubusercontent.com/37290585/70107880-c41cc200-1682-11ea-8f41-2ea3947ef867.png)





[musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3919722/musicxml.zip)

**Comment by TheBrightestStarInTheNightSky** [comment]
After I updated the develop branch code, the test found that the problem was not completely solved. In the test muxicxml provided by you, Clementi, m-sonatina op. 36, section 13 of No1 pt.2, section Haydn, section 28 of j-concertante Cello, and my musicxml, the problem still appeared. Screenshots and musicxml I put in the zip
[problem.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3919752/problem.zip)

**Comment by sschmidTU** [comment]
I fixed the whole rest bounding box error.
It only worked for 4/4 rhythm, because our whole rest check was wrong.
Somehow it took me a while to see that it simply checked whether the RealValue was 1.
There's a very simple test case, a whole rest in 3/4 (or 2/4 or 1/4) time signature:
![image](https://user-images.githubusercontent.com/33069673/70169233-b9861b00-16ca-11ea-93a8-a1cf38991672.png)

It's also fixed everywhere else of course, like Clementi Op. 36/1/Pt2 measure 13.
