### ISSUE TITLE
Display question about double barline.

### ISSUE THREAD

**Issue by JanvyHung** [opensheetmusicdisplay/opensheetmusicdisplay#610]
I find that the start-barline of the measure with end double barline may sometimes be showed wrong like the example shows . The situation caused by the change of key or tempo of the next measure.
![barline](https://user-images.githubusercontent.com/50696364/67840117-1b81bc80-fb30-11e9-84d3-ce0b58cef79b.PNG)
 And here is the musicxml file of the example.
[double_barline.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3787589/double_barline.zip)

**Comment by sschmidTU** [comment]
These vertical lines are created in `MusicSystem.createVerticalLineForMeasure`.
If you put a return at the start of the function, there are no vertical lines.
Unfortunately i couldn't fix the problem quickly, the logic of calls to this method is quite convoluted.
The bug exists at least since 0.6.8, probably since much longer.

revised sample:
[double_barline 2.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3918064/double_barline.2.musicxml.zip)

**Comment by sschmidTU** [comment]
This has been fixed some time ago.

<img width="445" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/9f10bad4-24f8-4bb4-a18a-c2421238ae90">
