### ISSUE TITLE
Display just one staff

### ISSUE THREAD

**Issue by AlbertHart** [opensheetmusicdisplay/opensheetmusicdisplay#611]
My musicxml file has two staffs. 

I would like to load it, but display just the top staff.

I tried changing .numberOfStaves after loading, but couldn't get that to work.

Ands I can't see an easy to change the musicxml file.

Any Ideas?

**Comment by matt-uib** [comment]
Yes.
First it depends: do you have 
1) an xml with 2 parts/Instruments given, or with 
2) one part which has two staves (like typically used for piano scores where you see the brace/bracket)
Case 2) we can't handle currently as this is not so easy due to some musical symbols like beams and slurs can go from staff 1 to staff 2...
For case 1) simply first set e.g.:
osmd.sheet.instruments[1].Visible = false
before rendering.
This would hide the second part/instrument of the score.

**Comment by DavoWU** [comment]
hi there are two ways, i think  you can have a try 
1. one is change your xml file, and remove note by get `<note/>` tag which contains `<staff>2</staff>`
but I find there is an issue with OSMD cursor show function (margin-left is not correct then), because I find that cursor marginLeft is controlled by vexflowStaffEntries, here: 
![Screen Shot 2019-11-05 at 22 15 44](https://user-images.githubusercontent.com/23088138/68215420-306fbb80-001a-11ea-9bf8-816fae73456c.png)

 and there is another issue #609 . I don't know its because I remove staff2 notes to make this, or because OSMD calculates its wrong. @sschmidTU 

2. you can add one more attribute to your XML <note    "print-object="no" >, and osmd change this note to invisible.

**Comment by sschmidTU** [comment]
> 2. you can add one more attribute to your XML <note <b>"</b>print-object="no" >, and osmd change this note to invisible.

clarification: it's `<note print-object="no">`
