### ISSUE TITLE
arpeggiate between voices doesn't work, bug on single note

### ISSUE THREAD

**Issue by eyalcohen7** [opensheetmusicdisplay/opensheetmusicdisplay#617]
I am using the following reduced xml:

[bug.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3815404/bug.txt)

The arpeggiao is looking like this:
![image](https://user-images.githubusercontent.com/3308022/68313863-f6f08c00-00bd-11ea-887e-52fd633256a2.png)

I think it has something to do with the backup, since when I remove the backup instruction, the issue disappears.

any ideas?

**Comment by bneumann** [comment]
<sarcasm>Backup is my favorite xml tag in musicxml. Just plain awesome </sarcasm>
But seriously:
Why is there a backup in a one note piece? I thought it's only for multiple voices over 1 measure/staff

**Comment by sschmidTU** [comment]
@bneumann the `<sarcasm>` tags in the first line of your comment don't appear anymore. But yes, i have similar feelings toward the backup tag.
Still, it's a valid MusicXML tag.
It's used to change between voices, so in this sample you get the first note in the first voice, back up, then get the note of the second voice.
https://www.musicxml.com/tutorial/the-midi-compatible-part/multi-part-music/

So it looks like this backup sets the arpeggio notes incorrectly. I'll have a look. It's a good, minimal test case.

**Comment by sschmidTU** [comment]
Ah, we currently only check for arpeggios within a VoiceEntry, but of course we can have Arpeggios between voices too. (and even more advanced, between staves)
So, we need to check all notes at the same timestamp instead of in the same voice.

**Comment by sschmidTU** [comment]
I fixed the render bug by not drawing one-note arpeggios anymore.
So, the sample XML was probably incorrectly exported, because an arpeggio on a single note doesn't normally make sense.

This is what the sample should look like (loaded in MuseScore here):
![image](https://user-images.githubusercontent.com/33069673/68397473-899f3280-0173-11ea-9df3-24f258f57922.png)

Vexflow doesn't render correctly, but again, this arpeggio doesn't make sense anyways, so for now it's better not to draw it at all.

So, the more important issue is rendering arpeggios between different voices, that would be a less important feature for OSMD 1.0, for which we can create a new issue.

Here are a few samples (the original one is the `one_arpeggiate` one)
[arpeggio_two_voices_render_bug.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3820117/arpeggio_two_voices_render_bug.zip)

**Comment by sschmidTU** [comment]
@eyalcohen7 which program did you use to export the MusicXML? Either that program or your manual editing led to this faulty sample, which only has arpeggiate on a single note.

**Comment by sschmidTU** [comment]
by the way, in Musescore you can't create arpeggios between multiple voices, you can only extend the arpeggio line.
But in the MusicXML standard you can create (numbered) arpeggios between multiple voices, and in any case even arpeggios between the two piano hands exist in classical music.

**Comment by eyalcohen7** [comment]
> @eyalcohen7 which program did you use to export the MusicXML? Either that program or your manual editing led to this faulty sample, which only has arpeggiate on a single note.

it's a simplified version of the full file exported from Sibelius to help reproduce the bug on a simpler xml file - I have attached the full version.

I have applied your patch and read the full file, and it made some of the arpeggiates disappear (I believe it was the problematic ones...)


[full.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3829243/full.txt)
