### ISSUE TITLE
File size of .min.js

### ISSUE THREAD

**Issue by danielleeman** [opensheetmusicdisplay/opensheetmusicdisplay#641]
Is there a way to select which components are needed for the dist build of the JS file? I noticed the demo JS file is a quarter of the size of the production min.js, which sits at 1.2mb. Any way we can shrink this down further?

**Comment by bneumann** [comment]
Hi,
Yes the demo is smaller because it only contains the controls for the demo page, e.g., the buttons. The other js file is the osmd render layer and vexflow. 
If you built for release there should be a statistics HTML where you can check the sizes of all modules. Last time I optimized for size it was only a handful kb that could be squeezed out. The biggest part is still vexflow

**Comment by sschmidTU** [comment]
We're actually working on reducing the bundle size right now and shaved off several dozen KB already, but as @bneumann said, the potential for reduction is limited, vexflow is the biggest part (and has lots of string literals which can't be minified).
