### ISSUE TITLE
CanvasBackend breaks at height > 32767 (SVG doesn't)

### ISSUE THREAD

**Issue by sschmidTU** [opensheetmusicdisplay/opensheetmusicdisplay#678]
Loading large scores on CanvasBackend breaks the DOM:
![image](https://user-images.githubusercontent.com/33069673/74976900-f17b3f80-5429-11ea-9733-cc19932f0e12.png)

I fixed one problem where sometimes a rogue SVG-HTMLElement was left even when switching to Canvas. (first commit in this issue)

The second problem is that 2D Canvas Context in Browsers is limited to certain dimensions. And if you exceed them, they just break without an error message, of course.
I just found this out later, which is why the info for this is a few comments below.

To reproduce, load this in the local demo in a window with low width:
http://localhost:8000/?showHeader=0&debugControls=0&backendType=canvas&pageBackgroundColor=FFFFFF&openUrl=CharlesGounod_Meditation.xml&endUrl

**Comment by sschmidTU** [comment]
It seems like no errors are thrown during render, the canvas just breaks.
For PNG generation, we should probably simply render to SVG, which works better, then generate a PNG from that.

**Comment by sschmidTU** [comment]
Okay, i found the issue:
backend.resize(width, height) works up to a height of 32767, but breaks at a height of 32768.
Which happens to be 2^15, of course.
backend.resize directly calls Vex.Flow.Renderer.resize().
So, it would be interesting to see whether this is a Vexflow limitation, or Browser limitation, or whatever.
(npm fix memory limit didn't help)

**Comment by sschmidTU** [comment]
Well, it looks like all browsers have canvas size limits, and the maximum height is 16 bit right now (Chrome/Firefox).
https://stackoverflow.com/a/11585939/10295942

So we should probably just limit the height to 32767 (2^15 - 1) for CanvasBackground for now,
and maybe reduce the zoom if we exceed that, otherwise the score gets cut off.

Btw, there's a npm module canvas-size that tells you the current browser's maximum canvas size:
https://stackoverflow.com/a/53677532/10295942

**Comment by sschmidTU** [comment]
For now i limited the width and height to 32767, which cuts off the score at that y-value.
That also gives a console warning.

We could go for smoother solutions like reducing the zoom to fit the score (though we have to render before we know if a score fits),
or using multiple Canvas elements stitched together to split the rendering to.

**Comment by sschmidTU** [comment]
Also raised an issue at Vexflow:
https://github.com/0xfe/vexflow/issues/742

**Comment by alex-sherwin** [comment]
This breaks the `RenderSingleHorizontalStaffline` option for SVG rendering when the total natural width exceeds 32767, it ends up wrapping to multiple lines.

@sschmidTU, Would you be open to a PR which made this hard-coded limit a configurable value, perhaps?  That way for SVG rendering where there is no theoretical limit, this can be made larger so that `RenderSingleHorizontalStaffline` can be properly honored?

**Comment by sschmidTU** [comment]
There is currently no browser that can have a width > 32767, to my knowledge, and neither can Vexflow.
You can edit the HTML/CSS so that the next container gets placed besides the first one, not below it.
@playthatsheet.com uses this technique.

**Comment by alex-sherwin** [comment]
@sschmidTU, I was playing with this last night on Chrome and had no issue rendering a single-line MusicXML that has ~ 120 measures that ended up being around 40,000px wide

I didn't run into any issues.. the only thing I did was change the hard-coded 32767 in OSMD to 100,000 so that it wouldn't hit any logical wrapping limitation, and the existing code self-adjusts the width down to the natural size (~40,000 or so in my case) without any kind of problem.

Chrome displays it just fine, dev tools report the width as 40,000+ px wide...

**Comment by sschmidTU** [comment]
Oh, interesting, if SVG doesn't have the same width limit, we can disable it for SVG, or make it an option.
It would be interesting if there is any width limit for SVG (above 32767).

**Comment by sschmidTU** [comment]
@alex-sherwin This should be fixed in OSMD 1.4.4, just released.
Just set osmd.EngravingRules.SheetMaximumWidth to 100000 or something.
