### ISSUE TITLE
Stop messing with canvas size

### ISSUE THREAD

**Issue by sebastianhaas** [opensheetmusicdisplay/opensheetmusicdisplay#7]
We want to remove the `setWidth()` option as OSMD should retrieve the width from the underlying HTML canvas only. Furthermore, OSDM should _not_ change the size of HTML elements such as the canvas. The size of a music sheet display must be determined _only_ by the size of the canvas HTML element, which is set by the browser according to inline attributes or CSS styles. We have to respect that, otherwise it will be impossible to integrate OSMD into any webpage.

- [x] Refactor to avoid usage of `setWidth()`
- [x] Stop resizing canvas, respect HTML element size
- [ ] Tests for removed `setWitdh()`
- [ ] Tests for respecting true canvas size

**Comment by oliver-h** [comment]
maybe it can make sense to set the width, but we would have to think of a resize logic than...

for the height, we just need the canvas to be scrollable, because we still want to draw the whole music sheet at once and therefore we at least have to resize the "paintable" area - the question is, if this is the same as the canvas size. If yes, then we have to check if putting the canvas into an html element which enables the scrolling can do it...

**Comment by sebastianhaas** [comment]
+1 for the paintable are, need to research how this is usually done then. I think we want to keep it as simple as possible for the end user, but I don't know. If it's usual to put a canvas into a `div` which determines the actual visible size, it will be fine I guess.

The `setWidth()` can be safely removed though, I don't see a use case were we want to make the drawing area smaller or bigger as the visible are unless we want to introduce horizontal scrolling.

How will it be done with a moving cursor and repetitions later on?

**Comment by oliver-h** [comment]
Andrea did some experiments on that, and if I remember it right, he used two html divs for that. 

The moving cursor will have to make the browser scroll somehow.

And for the setWidth() -> I was thinking of the fact, that the layout of the sheet is of importance to the musicians. By setting a fixed width and a fixed zoom, one can make sure to see the same layout, independent of the actual window size. 
Also I can think of scenarios with an opened sheet on the left side and some text commenting the music notes, to the right. Again it would be important to preserve the exact layout.
Anyways, if the solution will be to put the canvas into another html element which controls the scrolling and space the canvas can consume in the browser, this would not be of importance, as we could just take the width of the parent html element for the canvas instead of the browser window width (and therefore we don't need to set it explicitly in javascript).

**Comment by acondolu** [comment]
* The height of the canvas is determined by the length of the sheet music. Shouldn't the library resize the canvas to that height?
* I wonder how would the resize take place then. Do you mean, instead of
```javascript
sheet.setWidth(width);
```
something like
```javascript
container.width = width;
sheet.render();
```

**Comment by acondolu** [comment]
Yes I agree with you. Then I propose that the user passes the `div` container to the OSMD object, and we create and handle a canvas inside it.
Something like:
```javascript
var container = document.getElementById("div-container");
var sheet = new OSMD(container);
window.onresize = function() {
    container.width = "window's width or whatever";
    sheet.render();
}
```

What do you think?

**Comment by sebastianhaas** [comment]
I just did some research, I guess both (scrolling content inside the canvas vs. scrolling the canvas itself) is possible and has pros and cons. Since we don't deal with huge data, scrolling the entire canvas with something like `overflow:hidden` in a scrollable div is probably the way to go, so I agree with you and given this use-case it is obviously inevitable to resize the canvas from code.

> Then I propose that the user passes the div container to the OSMD object, and we create and handle a canvas inside it.

I very much like this approach. We should definitely get rid of anything like `setWidth()` for any default use case. I guess we can use [1] for most cases, and leave the explicit option to more advanced users. Ideally, you can setup a running OSMD instance with only one, maybe two calls injecting it into a parent `div` and supplying the data to be displayed?

[1] http://stackoverflow.com/questions/4032179/how-do-i-get-the-width-and-height-of-a-html5-canvas

**Comment by oliver-h** [comment]
I like acondolus approach. But, we can reduce it even more.
```javascript
var container = document.getElementById("div-container");
var sheet = new OSMD(container, true);  // second param -> autoResizeOnSizeChange
// we register to the onresize event inside of the OSMD object, if the autoResizeOnSizeChange
// param is true
```
That's it. If the user wants the size to be fixed, he just sets the second option to false. If he wants a certain size, he sets it in the container. 
What do you think?

@sebastianhaas I don't get the point from the stackoverflow post. Am I missing something, do we really need it?

**Comment by acondolu** [comment]
To my knowledge only the window element has a onresize event, thus attaching a callback to div resize could not be possible.

**Comment by sebastianhaas** [comment]
> That's it. If the user wants the size to be fixed, he just sets the second option to false. If he wants a certain size, he sets it in the container. 

I don't know if that would work as @acondolu already mentioned, no resize events on DOM elements other than the window.

> @sebastianhaas I don't get the point from the stackoverflow post. Am I missing something, do we really need it?

Idk. I just posted it in case @acondolu is interested in retrieving height and width from a canvas. It basically says that the `height` and `width` properties are not the canvas' internal size rather then the actual size specified by CSS. I thought it was good to know.

**Comment by oliver-h** [comment]
@acondolu @sebastianhaas By saying, that we register to the onresize event inside of the osmd object, I did not mean, that we should register to the resize event of the htlm element, but that we could move the this 4 lines from Andreas expample into the osmd class.
```javascript
window.onresize = function() {
    container.width = "window's width or whatever";
    sheet.render();
}
```

@sebastianhaas okay, I understand now :-)

**Comment by sebastianhaas** [comment]
Let's see how people are using OSMD. Or how @petrosalema is planning on using it. E.g. if multiple OSMD instances are placed inside different containers on a page, are we really interested in on-window-resizing at all?

Resizing on window resize is certainly a must for a full screen mode, but I'm not sure about the use case I described above.

**Comment by sebastianhaas** [comment]
kk, and that one is supposed to control whether OSMD scales with the window or not.

**Comment by oliver-h** [comment]
jup. so the initializing can be reduced to 2 lines of code, 1, if we decide to provide the id of the container element as parameter in the constructor as well - which sounds quite decent to me.

it's getting better and better :-)

**Comment by sebastianhaas** [comment]
Is this something we can do this week @acondolu? If not, pls change the milestone to next week.

**Comment by acondolu** [comment]
I can do it tomorrow.

I think nobody will ever use the option of auto-scale to the full window (I'm almost not using full width even on the simplest case - the demo).

I also disagree with passing the id of the HTMLElement instead of the element itself. But it would be great if one could pass either, and the constructor would figure out what to do.

**Comment by oliver-h** [comment]
> I also disagree with passing the id of the HTMLElement instead of the element itself. But it would be great if one could pass either, and the constructor would figure out what to do.
Let's do that. Just overload the constructor.

**Comment by acondolu** [comment]
Fixed the behaviour in cd8baf40fa5f22cbe778c2092edef271ef8919b8.

I did the constructor overloading mentioned above. The boolean option for auto-scaling to window size is still missing, though.

**Comment by sebastianhaas** [comment]
I think it's fine for now, lets publish this tomorrow.

**Comment by oliver-h** [comment]
Yeah, it's okay to postpone it in favor of a new build, but let's don't forget it...

**Comment by acondolu** [comment]
Added the auto resizing option in 9b1ed426ce6677b4d74c6d7f48950b0a2b84a833
