### ISSUE TITLE
Honour new-system and new-page print tags

### ISSUE THREAD

**Issue by dieuwedeboer** [opensheetmusicdisplay/opensheetmusicdisplay#702]
I cannot see a way to force a break (new system or page) to be rendered.

The demo scores all seem to contain the following:
```
<supports element="print" attribute="new-page" type="yes" value="yes"/>
<supports element="print" attribute="new-system" type="yes" value="yes"/>
```
Some demo scores also have a print tag: `<print new-system="yes">`

Playing around with the demos and some custom scores and searching the codebase and docs seemed to reveal that this hasn't been implemented yet.

I would propose that in OSMD a new-system and new-page should initially have the same effect: a forced line-break.

**Comment by sschmidTU** [comment]
Yes, we do not use these tags so far.
The initial reasoning was that since we render the score from scratch (with Vexflow), all absolute positioning information in the XML becomes obsolete.
So, a line-break could occur in the first measure of a new line in OSMD,
and a page-break could occur in the first measure of a new page (now that we have pagination).
Pagination is a very new feature, so page-breaks wouldn't have had any meaning beforehand except as line-breaks.

However, if you still want to use line-breaks and page-breaks under these circumstances, we should probably support that.
And we are considering page breaks and line breaks anyways for our updates to formatting.
So, we are already thinking about this, but still thanks for the feature request and showing that this is a wanted feature.

**Comment by sschmidTU** [comment]
new-system ("line break") is now supported, needs to be enabled via OSMDOption:
`osmd.setOptions({newSystemFromXML: true})`
By default, this is not enabled (XML new-system is ignored), because OSMD is doing its own layout and we may get a new system after a single measure, see my comment above.

**Comment by sschmidTU** [comment]
Page breaks working too now.

Sample with multiple page and system breaks:
![image](https://user-images.githubusercontent.com/33069673/79501957-389f3e80-802f-11ea-83f4-e798b3e801eb.png)
[page_system_break_multi_4_pages.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4489537/page_system_break_multi_4_pages.musicxml.zip)
Will probably become new OSMD Function Test - System and Page Breaks.

Needs these options:
```js
osmd.setOptions({
  newPageFromXML: true,
  newSystemFromXML: true
})
```
