### ISSUE TITLE
Customize Background color

### ISSUE THREAD

**Issue by bukaznik** [opensheetmusicdisplay/opensheetmusicdisplay#729]

**Comment by sschmidTU** [comment]
This is basically already functional:
`osmd.setOptions({pageBackgroundColor: "#123456AA"})`

The only problem is that the cursor will not be visible anymore if your color isn't at least slightly transparent (the "AA" in the last hex code above is the transparency).
That's because of how the cursor draws in a background layer. You can fix that, but then the notes are slightly transparent, see https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/pull/318#issuecomment-410279280.
Maybe there's a better solution for this transparency/layer problem.

**Comment by conde2** [comment]
While studying the source I found out that using

    this.osmd.EngravingRules.FingeringInsideStafflines = true;
    
This accounts for the bounds box, so I'm using this  option now, and from 5seconds it droped to 1.4 seconds.
