### ISSUE TITLE
Keyboard / Foot Pedal support

### ISSUE THREAD

**Issue by phonicscore** [opensheetmusicdisplay/opensheetmusicdisplay#730]

**Comment by DamianRivas** [comment]
If things like this do get implemented it should be opt-in.

Right now, the minified bundle `opensheetmusicdisplay.min.js` is already pushing 1MB

**Comment by sschmidTU** [comment]
Agreed. We can add it to the demo.

@DamianRivas By the way, we recently reduced the bundle size by moving the PDF export to the demo. Also, much of the bundle size is Vexflow (465KB).
![image](https://user-images.githubusercontent.com/33069673/85023567-2d72a700-b175-11ea-8659-5991210e3374.png)

You can check this for yourself after `npm run build` in `build/statistics.html`.
We already have a branch to reduce bundle size, but it won't be a huge factor because of this.

**Comment by sschmidTU** [comment]
This seems more of a demo feature, and it's not clear with what scope it would be implemented.
