### ISSUE TITLE
Transposing

### ISSUE THREAD

**Issue by bukaznik** [opensheetmusicdisplay/opensheetmusicdisplay#733]

**Comment by ice6** [comment]
Is there any progress about this feature?

I read musescore's implementation [here](https://github.com/musescore/MuseScore/blob/master/libmscore/transpose.cpp), it seems that it is not as easy as @AlbertHart described [here](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/613)

Anyone working on this and how will the api looks like. :)

**Comment by ice6** [comment]
Is there a branch working on this? how to contribute?

**Comment by matt-uib** [comment]
We have this code in a private repo as we want to be able to license it. I'm just working on it and maybe i can show you a result soon.
So most likely we will not make the code public - but we still think about the best way here.

**Comment by matt-uib** [comment]
Got it working now:
![grafik](https://user-images.githubusercontent.com/17180665/82090148-4e1e8b80-96f5-11ea-9b8d-dee28e079a47.png)

**Comment by matt-uib** [comment]
+ 2 semitones:
![grafik](https://user-images.githubusercontent.com/17180665/82090249-83c37480-96f5-11ea-8f08-42188eab56b8.png)

-1 semitone:
![grafik](https://user-images.githubusercontent.com/17180665/82090495-fc2a3580-96f5-11ea-840c-3a08f2296a38.png)

**Comment by ice6** [comment]
👍 cool. thanks for making the project forward.

As you mentioned at another thread.

```
The idea behind this is to provide some income with some premium plugins to get the money needed to allow a sustainable development of OSMD.
```

It is understandable to make the repo private. 

Best wishes!

**Comment by matt-uib** [comment]
@ice6 thanks for the interest and also your efforts in that direction.
As i said, we want to provide this transpose feature for free for non-commercial projects. So, if you or anyone else is interested, please write to us.

**Comment by ice6** [comment]
@matt-uib 

thank you very much.

do I have to write an email or something else?

will you give the supplicant the source code that implement the `src/MusicalScore/Interfaces/ITransposeCalculator.ts` interface and sign a ` non-disclosure agreement`?

**Comment by matt-uib** [comment]
@ice6 yes that's how we plan to do it.
We provide then an implementation of ITransposeCalculator, add a function for setting the TransposeCalculator on the OpenSheetMusicDisplay.ts object
where it internally will set MusicSheetCalculator.transposeCalculator.
Yes please write to us at office@phonicscore.com for it.
Thanks also for the info about pay methods for donations - we will check that out what we can add here. Makes very much sense!

Actually our app (Practice Bird for iOS and PhonicScore for Android) is also very suitable for choir rehearsal (Playback, metronome, loop a section, ...) would be great if you check it out and tell us what you think about it. Feedback is very welcome!

**Comment by ice6** [comment]
@matt-uib 

thank you, I have sent an email to the address.

looking forward to that.

**Comment by fredmeister77** [comment]
Transpose plugin interface available, plugin available w/ license

**Comment by sschmidTU** [comment]
Good news: The Transposition plugin is now free and open source, released on the public osmd develop branch.
It will be included in the next OSMD release.

Up to now, it was an early access feature available to sponsors only, 
but as we promised as a subgoal on [Github Sponsors](https://github.com/sponsors/opensheetmusicdisplay), after reaching 15 sponsors, we are making it available for everyone.

Our [index.js](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/demo/index.js) shows how to use the TransposeCalculator:
```js
import { TransposeCalculator } from 'opensheetmusicdisplay';

// (create osmd object etc)

osmd.TransposeCalculator = new TransposeCalculator();

// osmd.load(your sheet)

osmd.Sheet.Transpose = transposeValue;

// if you've already rendered before:
// osmd.updateGraphic();

osmd.render();
```

![image](https://user-images.githubusercontent.com/33069673/115450603-690a5180-a21c-11eb-953d-841a106748b4.png)

Note that there is still an occasional problem when you transpose a second time after load and render to a new key like F# or B (+3 or -4 for Beethoven Geliebte),
but that can be solved by cleanly loading a sample (again) and setting the Transpose before the first render. (see #1012)

Also see #886, #769, #613, #886, #580, and #132, all obsolete (all issues about transposing!).

One possible addition would be to add methods to give a key to transpose to instead of a number of semitones, and choose a direction (up/down or closest), see #769 for a demo/description, but that should be discussed in a new issue.

**Comment by AlbertHart** [comment]
This will be a great addition.

Key and direction can be very helpful. Key - so you don't have to count correctly the number of half steps, or the interval, from Bb to F# (. And direction is important when the transposed score gets too high or too low.

I'll check it out when I can.

**Comment by sschmidTU** [comment]
Yes, that would be great, thank you! :)

**Comment by mt633** [comment]
> Good news: The Transposition plugin is now free and open source, released on the public osmd develop branch.
> It will be included in the next OSMD release (the one after 0.9.5).

That's great news! I'm just not sure how to use the feature. I'm new to JavaScript and just adding

> ```js
> import { TransposeCalculator } from 'opensheetmusicdisplay';
> ```

doesn't work for me after I've added `opensheetmusicdisplay.min.js` to my project. Do I need to build it with npm or something first? I suppose it's not included in the main code (since it's called a plugin), but I don't suppose there is a pre-built JavaScript file I can use for it?

**Comment by sschmidTU** [comment]
@mt633 sorry for the late reply, i forgot to answer as this is a closed issue.
The TransposeCalculator class should be exported like any other class in OSMD. Are you using OSMD v1.0.0?
You should be able to simply do `osmd.TransposeCalculator = new opensheetmusicdisplay.TransposeCalculator()`, depending on your setup. What's the error message?
How do you call the OSMD constructor? Can you share more of your code? Do you use a module manager like webpack or plain javascript?

Here's a plain javascript usage example:
https://github.com/opensheetmusicdisplay/RawJavascript-usage-example/blob/master/indexSimpler.html

**Comment by mt633** [comment]
No worries, thanks for your help. I did get it to work eventually. I think I just got confused when looking at [the wiki page](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Transposing) about transposing where I thought you needed the line `import { TransposeCalculator } from 'opensheetmusicdisplay';`.

**Comment by sschmidTU** [comment]
@mt633 does it work for you without the import? Where do you get TransposeCalculator from then? Could you share your code so we can improve the Wiki?

**Comment by mt633** [comment]
Yes it does. My code is pretty similar to the raw JavaScript example you linked to. An excerpt from the code looks like this:
```html
  <div id="osmdCanvas" />
   <script src="opensheetmusicdisplay.min.js"></script>
  <script>
    var osmd = new opensheetmusicdisplay.OpenSheetMusicDisplay("osmdCanvas");
    osmd.TransposeCalculator = new opensheetmusicdisplay.TransposeCalculator();
    await osmd.load(score);
    
    async function transpose(interval) {
      osmd.Sheet.Transpose = interval;
      osmd.updateGraphic();
      await osmd.render();
    }
</script>
```

**Comment by sschmidTU** [comment]
@mt633 thanks! I'll update the Wiki.

**Comment by sschmidTU** [comment]
You can now transpose a single instrument: #1115 
Also, `note.TransposedPitch` now gives the transposed pitch.
(`note.Pitch` is always untransposed, because OSMD needs it internally)
