### ISSUE TITLE
cursor undefined bug (after upgrading to 0.7.6 from 0.7.3)

### ISSUE THREAD

**Issue by ifredom** [opensheetmusicdisplay/opensheetmusicdisplay#736]
0.7.3 upgrade to 0.7.6

MusicEngine.js?073d:220 Uncaught (in promise) TypeError: Cannot read property 'cursor' of undefined
 
`osmd.cursor`

**Comment by sschmidTU** [comment]
does this happen when you try to build your javascript, or when you load a MusicXML sample?
If it happens when you load a sample, please upload a MusicXML sample that causes this.
Otherwise i don't have enough information to help you, your comment doesn't show where this error happens.

**Comment by ifredom** [comment]
After upgrading, the cursor property is no longer available on the osmd.

---

![image](https://user-images.githubusercontent.com/13759936/81151474-9af6b980-8fb3-11ea-8e3b-20949879ca49.png)

**Comment by sschmidTU** [comment]
This should be fixed, it seems like the problem was using the CanvasBackend with the Cursor, in which case the cursor was created on the wrong HTMLElement.

(so now there's `VexFlowBackend.getRenderElement()` which returns this.inner for SVG and this.canvas for CanvasBackend).

Here's the current develop build if you want to test it, with osmd.version = 0.79-RC to identify the build:
https://drive.google.com/file/d/1bHoXvVOU4MhHqmQVSRSAhrDtXxnlC8G6/view?usp=sharing
(of course, you need to rename it to opensheetmusicdisplay.min.js again and replace your osmd build with it, if possible)
