### ISSUE TITLE
New Transpose Function for OSMD

### ISSUE THREAD

**Issue by AlbertHart** [opensheetmusicdisplay/opensheetmusicdisplay#769]
**Transposing Scores in OSMD**

ice6 and I have been working on a transpose function for OSMD which we would like to include as part of the OSMD code.

We have created a demonstration of the new feature here:

[](https://ice6.github.io/opensheetmusicdisplay/build/)

You can load or paste a score, select a transpose selection and see it transposed.

Transposing is controlled by two new options on the Demo Page

![image](https://user-images.githubusercontent.com/8965352/83698977-14d48f80-a5c0-11ea-83b7-8dff44eb9b2d.png)

The DEMO code calls a single function - transpose_xml() after loading the xml file and before passing it to the OSMD rendering engine. This could easily be called by any OSMD developers wanting to offer an option to transpose the Music XML files.

[sschmidTU: [code here](https://github.com/ice6/opensheetmusicdisplay/blob/master/demo/transpose_functions.js) ]

We propose to add transpose_xml() to the core OSMD code, and also to add the call to it to the demonstration page, so it can be easily tested.

This would be available, of course, to all OSMD participants,

If this seems like a good idea to, we can create a fork, add the code, then let you test it and incorporate it.

**Bugs, etc.**

I am sure you will find some bugs as soon as you try to test it. We can fix most of them easily,

And ice6 and I will both be willing to make changes to the code as bugs are found or new features are requested.

**Comment by sschmidTU** [comment]
The OSMD Transposition plugin is now integrated into OSMD, see https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/733#issuecomment-823530818.
(currently on the develop branch, will be released in the next OSMD version after 0.9.5)

Still, the transposition plugin you've been working on here looks very nice, and the transposition by key and direction instead of semitones is a feature we could add as well.
