### ISSUE TITLE
Hello World example throws error

### ISSUE THREAD

**Issue by cyluxx** [opensheetmusicdisplay/opensheetmusicdisplay#790]
Hello. Thank you for this awesome work!

I have the following problem: When I try to use the [Hello World](https://www.musicxml.com/tutorial/hello-world/) example from the makemusic site, I get an error.

```
const osmd = new OpenSheetMusicDisplay(this.container.nativeElement);
await osmd.load(`
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE score-partwise PUBLIC
    "-//Recordare//DTD MusicXML 3.1 Partwise//EN"
    "http://www.musicxml.org/dtds/partwise.dtd">
<score-partwise version="3.1">
  <part-list>
    <score-part id="P1">
      <part-name>Music</part-name>
    </score-part>
  </part-list>
  <part id="P1">
    <measure number="1">
      <attributes>
        <divisions>1</divisions>
        <key>
          <fifths>0</fifths>
        </key>
        <time>
          <beats>4</beats>
          <beat-type>4</beat-type>
        </time>
        <clef>
          <sign>G</sign>
          <line>2</line>
        </clef>
      </attributes>
      <note>
        <pitch>
          <step>C</step>
          <octave>4</octave>
        </pitch>
        <duration>4</duration>
        <type>whole</type>
      </note>
    </measure>
  </part>
</score-partwise>
`);
osmd.render();
```

```
Could not parse MusicXML, no valid partwise element found
```

```
ERROR Error: Uncaught (in promise): Error: OpenSheetMusicDisplay: Document is not a valid 'partwise' MusicXML
Error: OpenSheetMusicDisplay: Document is not a valid 'partwise' MusicXML
```

However, importing the xml to the opensheetmusicdisplay demo site works. Is this a bug or, am I understanding something wrong? I also tried to use a document instead of a string as a parameter.

**Comment by dnlfrst** [comment]
The observed issue is due to the code formatting. In particular,

```js
await osmd.load(`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
```

works, where as

```js
await osmd.load(`
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
```

and

```js
await osmd.load(`
    <?xml version="1.0" encoding="UTF-8" standalone="no"?>
```

throw _different_ error message. `Could not retrieve requested URL 0` in the former and `OpenSheetMusicDisplay: Document is not a valid 'partwise' MusicXML` in the latter case (which @cyluxx observed). Compare [this sandbox](https://codesandbox.io/s/osmd-issue-790-gidd1?file=/src/index.js) for illustration of the issue.

**Comment by sschmidTU** [comment]
@dnlfrst thanks for the hint! the problem is indeed the newline before the xml.

@cyluxx as dnlfrst showed, the problem is that you formatted the XML by adding a newline, which is not a good idea when handling xml literals. It would be best if you removed the newline and gave the XML like this:
```js
osmd.load(`<?xml...
```

But to prevent errors like this, i added a trim() to the osmd.load() function, so in future even giving whitespaces at the start of the xml should work.

It only trims if `/^\s/.test(stringToTrim)` (whitespace at start of string), so this should be computationally very cheap/fast.
(i don't know how long trim() takes if there is no whitespace in the beginning, but this should be an improvement, since we technically don't need to trim the end of the xml string)
