### ISSUE TITLE
The cursor cannot keep up with the new page

### ISSUE THREAD

**Issue by djae88** [opensheetmusicdisplay/opensheetmusicdisplay#817]
![84872150-7a467700-b0bc-11ea-90a6-87c702c4e153](https://user-images.githubusercontent.com/56290540/86314573-0af78800-bc63-11ea-84f6-937328111db3.png)

this project work well when pageformat is endless
but when I set pageformat option (or newPageFromXML option) like "a4 p" or others
cursor cannot follow the new page
it came back to starting point (but it wasn't an exact location)

![84872124-70bd0f00-b0bc-11ea-8fbb-984ef9d97dd6](https://user-images.githubusercontent.com/56290540/86314580-1054d280-bc63-11ea-9ac8-728cb21cd61d.png)

![84872096-6438b680-b0bc-11ea-917d-7b173a50fb3f](https://user-images.githubusercontent.com/56290540/86314578-0e8b0f00-bc63-11ea-9087-d25a9856e0b9.png)

Thanks

**Comment by sschmidTU** [comment]
This is a known bug that will be fixed.
I thought there was already an issue for this, but apparently not, thanks for creating.

**Comment by sschmidTU** [comment]
This is now fixed.

Here's the cursor on page 2 of our OSMD Function Test - System and Page Breaks:
![image](https://user-images.githubusercontent.com/33069673/89341155-2827d800-d6a1-11ea-9b89-011dbc9ed332.png)

The fix was not that easy to implement, because right now unfortunately each MusicPage is at relative and absolute position (0,0), so for the cursor position, which is in HTML-DOM space, we need to add the height of the previous pages' containers to the cursor y position.
Maybe we'll change that in the future, but for now, the cursor position works on all pages.

**Comment by sschmidTU** [comment]
I improved the cursor positioning and DOM-attachment.
Instead of adding the height of previous pages to the cursor position, the cursor is now reattached to the div/canvas of the current page.
You can now also change the PageFormat or size of the window, and the cursor will be redrawn correctly at whatever new page and location the currently highlighted position is now.

**Comment by djae88** [comment]
Thank you so much! 
This is a great work!!
