### ISSUE TITLE
How to hide BPM

### ISSUE THREAD

**Issue by Sunyuzhuo** [opensheetmusicdisplay/opensheetmusicdisplay#818]
@sschmidTU Hi there , I want to hide the BMP, what should I do.
![21593672860_ pic](https://user-images.githubusercontent.com/48279156/86329121-4f415300-bc78-11ea-992b-67dafab0d233.jpg)

**Comment by sschmidTU** [comment]
```js
osmd.setOptions({drawMetronomeMark: false})
```
There you go!

**Comment by Sunyuzhuo** [comment]
@sschmidTU I try to do this,but it doesn't hide.

**Comment by sschmidTU** [comment]
@Sunyuzhuo sorry, i made a typo, it's `drawMetronomeMarks: false`.

**Comment by Sunyuzhuo** [comment]
`                osmd.setOptions({drawCredits: false, drawPartNames: false,drawMetronomeMarks: false,drawTitle:false});

`
it still not hide.  :(

**Comment by sschmidTU** [comment]
@Sunyuzhuo That is strange.
You can try it in the Demo:
https://opensheetmusicdisplay.github.io/demo/

![image](https://user-images.githubusercontent.com/33069673/86460485-c3d3ca80-bd28-11ea-967c-3a0660e8e1c1.png)

Do `osmd.EngravingRules.MetronomeMarksDrawn = false;` in the console, then select the first Clementi score.

Maybe you're using an old version of OSMD? Do `console.log(osmd.Version)`, what does it say?
The latest release is 0.8.2, you can get it from here:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/releases

Otherwise, can you share a sample where this doesn't work?
If it doesn't work in our public demo, you're probably doing something wrong in your code.

**Comment by Sunyuzhuo** [comment]
@sschmidTU Has been resolved, it’s reason for version. thanks : )
