### ISSUE TITLE
Mark composer in Multiple lines?

### ISSUE THREAD

**Issue by djae88** [opensheetmusicdisplay/opensheetmusicdisplay#826]
Are you planning to mark the composer in multiple lines?
The reason I need it is because
if the sheet writer wants to write the composer, arranger, cover at the same time
I think it would be better to mark multiple lines than one line.
![1](https://user-images.githubusercontent.com/56290540/86875716-1bee4080-c11e-11ea-8f5d-49ba04400ce3.png)
↑ Musescore
![image](https://user-images.githubusercontent.com/56290540/86875737-2d374d00-c11e-11ea-941c-a6447afcbf23.png)
↑ OSMD

and show only the first line when the value is multiple lines in xml.
![image](https://user-images.githubusercontent.com/56290540/86876341-7936c180-c11f-11ea-86a1-d1518a0fe2ce.png)

I hope these problems are solved without difficulty
thanks

**Comment by sschmidTU** [comment]
This was recently implemented, just not released yet. If you don't want to build from our develop branch, you'll have to wait for the next release, which should be pretty soon.
![image](https://user-images.githubusercontent.com/33069673/87095135-7d0e3500-c240-11ea-914d-fc4fa559a678.png)

But it was a good idea to open an issue for it anyways, because we didn't have one yet. Cheers!
