### ISSUE TITLE
Editor?

### ISSUE THREAD

**Issue by vinzentt** [opensheetmusicdisplay/opensheetmusicdisplay#83]
Hi,

thanks for this promising project. I'm using as well vexflow in a project you can check here http://sonycsl-paris.github.io We made possible music XML import as well but our project is more jazz oriented at the moment.

I was wondering if you're planning to make an editor ? Or if the plugin structure will allow score modification.

Thanks for your answer.

Vincent

**Comment by sebastianhaas** [comment]
Thanks for your link, love the idea of having lead sheets in vexflow!

The plugin infrastructure will definitely enable us to build something like an editor since it will expose the underlying music information. I haven't thought about writing back to MusicXml from vexflow at the moment though but obviously it could be done.

The plugin infrastructure is high among our priorities but I guess we will focus on improving score display (grace notes, braces etc.) before working on additional features then.

**Comment by sschmidTU** [comment]
Way out of scope at the moment. Would be fantastic of course.
