### ISSUE TITLE
Positioning of notes with 2 voices

### ISSUE THREAD

**Issue by JanvyHung** [opensheetmusicdisplay/opensheetmusicdisplay#853]
I found some problems about the position of the notes with 2 voices ,which is different with the musicxml shows, but I don't know how to generalize them, just like the example shows. Could you let me known the causes and how to deal with the problem? Looking forward for your reply. Thank you.
![image](https://user-images.githubusercontent.com/50696364/89164064-27ac1600-d5a9-11ea-8df9-80f7cedad07e.png)
![image](https://user-images.githubusercontent.com/50696364/89164094-3266ab00-d5a9-11ea-9537-98f9e25d2794.png)
[2_voice 2.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5014835/2_voice.2.musicxml.zip)

**Comment by bneumann** [comment]
Not sure if that is fixable in OSMD. We are only adding the notes. They are placed by vexflow.

**Comment by sschmidTU** [comment]
Yes, Vexflow does the layouting, we can't change most of this.
The first two notes could maybe share the same notehead, see #414, we already have an issue for that.
The second two notes don't make much sense anyways, because this is how the stems are given in the XML, they should probably be the other way round.
MusicXML doesn't say on which side of the note the stem should be, and i don't think you can change it in Vexflow.
