### ISSUE TITLE
When the cursor moves to this position, it is offset

### ISSUE THREAD

**Issue by yx570** [opensheetmusicdisplay/opensheetmusicdisplay#872]
![1](https://user-images.githubusercontent.com/13014581/90380088-3537c480-e0ae-11ea-8fe5-a5af9b14788a.png)

This is the XML for testing
[offset.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5083358/offset.zip)

**Comment by sschmidTU** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/33069673/105871006-24925f80-5ff9-11eb-9d46-6275831621fe.png)

The problem was having an endClef in one measure but not the other (similar to begin key signatures, #797),
so now when one instrument has an endClef, we draw an invisible one in all the others (unless they have their own).

New test added that automatically draws the StaffEntry bounding boxes in our visual regression tests:
![image](https://user-images.githubusercontent.com/33069673/105871391-89e65080-5ff9-11eb-9c71-bf9d33d45878.png)

`test/data/test_end_measure_clefs_staffentry_bbox.musicxml`

**Comment by sschmidTU** [comment]
This also fixed a couple problems with end clefs in Debussy - Mandoline:
measures 5, 7, especially 11:
before:
![image](https://user-images.githubusercontent.com/33069673/105881590-fb77cc00-6004-11eb-84ea-147fb65fd2c2.png)

after:
![image](https://user-images.githubusercontent.com/33069673/105881626-07fc2480-6005-11eb-842d-1cbbb496a8c6.png)
