### ISSUE TITLE
Engraving Rule `PageBottomExtraWhiteSpace` Breaks Measure Bounding Boxes

### ISSUE THREAD

**Issue by dnlfrst** [opensheetmusicdisplay/opensheetmusicdisplay#875]
# What is this issue about?

In response to #788, #822 introduced a new engraving rule [`PageBottomExtraWhiteSpace`](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/src/MusicalScore/Graphical/EngravingRules.ts#L30) in version [0.8.3](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/CHANGELOG.md#features-1). This issue applies to the versions [0.8.3](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/tree/0.8.3) and [0.8.4](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/tree/0.8.4).

# What is the problem?

After rendering a music sheet, I would expect the `PositionAndShape` of a `GraphicalMeasure` to contain the correct bounding box of the measure contents as rendered hereafter:

![Correct Bounding Boxes](https://user-images.githubusercontent.com/13868083/90499989-92815380-e14a-11ea-9d1d-4f69434232a6.png)

However, with

```typescript
musicSheet.EngravingRules.PageBottomExtraWhiteSpace = 50;
```

set, the bounding boxes do seem to be messed up:

![Incorrect Bounding Boxes](https://user-images.githubusercontent.com/13868083/90500013-9a40f800-e14a-11ea-8b83-d12a535a5fb2.png)

I illustrated the above-described issue in [an MWE](https://codesandbox.io/s/osmd-issue-875-hijfz?file=/src/index.ts).

**Comment by sschmidTU** [comment]
Thanks for the report! This should be fixed now. Though you need to use `PageBottomMargin` instead of `PageBottomExtraWhiteSpace` again, as i fixed the former, and the latter is not necessary anymore, so it was removed.

I also fixed the container height, which was sometimes too large for small scores, now it fits,
see new OSMD Function Test - Container height:
![image](https://user-images.githubusercontent.com/33069673/92522362-eb5e7c00-f21e-11ea-8af3-4930dadce78f.png)

Now we can set any margin:
```js
  osmd.EngravingRules.PageBottomMargin = 30;
```

![image](https://user-images.githubusercontent.com/33069673/92522510-21036500-f21f-11ea-830e-db5e8c146b63.png)

You can even set a negative PageBottomMargin to reduce the container height, though it will crop the score/image if the new height will be smaller than what OSMD renders.
