### ISSUE TITLE
Support for Vexflow 3 softmax / Note spacing proportionate to note duration

### ISSUE THREAD

**Issue by monadiconion** [opensheetmusicdisplay/opensheetmusicdisplay#882]
Seems VexFlow version has been downgraded to 1.2.93 due to some issues in rendering (https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/pull/706) in recent releases.

Is there any workaround (through e.g. EngravingRules / OSMD options) other than using the softmax feature in VexFlow 3 to make note spacing proportionate to note value? i.e. the **width of a half note + its spacing** in a bar should = **width of 2 quarter notes + their spacings** (same voice, horizontally). This feature will be useful for rhythm education / for beginners to learn the "distance" from one note to another.

Thanks for this amazing library!

**Comment by monadiconion** [comment]
Also, may I ask if the following rules are used in the process of rendering? I tried setting them but seems they have no effect on the score. (Which I suppose they may be associated with note spacing?)

```
public NoteDistances: number[] = [1.0, 1.0, 1.3, 1.6, 2.0, 2.5, 3.0, 4.0];
public NoteDistancesScalingFactors: number[] = [1.0, 2.0, 4.0, 8.0, 16.0, 32.0, 64.0, 128.0];
```

**Comment by sschmidTU** [comment]
With our current version and Vexflow 1.2.93, you can set these values:
```js
  osmd.EngravingRules.VoiceSpacingMultiplierVexflow = 1.0; // currently the default is 0.85, though it will probably be restored to 1.0 again, because it causes formatting issues
  osmd.EngravingRules.VoiceSpacingAddendVexflow = 10;
  // osmd.zoom = 0.8; // optional: reduce zoom to reduce score size (e.g. 80%)
```

This seems to lead to pretty much exactly 2:1 spacing for half and quarter notes (80 vs 40 pixels distance):
![image](https://user-images.githubusercontent.com/33069673/92486162-0f549a00-f1ec-11ea-88b3-81f8ed72e8d4.png)
[half_quarter_distances.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5188763/half_quarter_distances.musicxml.zip)

To reduce the size of the score again, you can modify osmd.zoom.

As a side note, we are already setting the softmax factor in vexflow, but it only gets applied properly if you install vexflow 3.x.

Also note that it's very hard to set specific note positions, to my knowledge, because vexflow does the formatting, and it's not designed to be modified by hard-coding. It could be that there are some ways to hack hardcoded positioning into vexflow though.

**Comment by sschmidTU** [comment]
Oh and the NoteDistances values in EngravingRules aren't used, they are for our custom renderer which doesn't exist in OSMD, since we use Vexflow.

**Comment by monadiconion** [comment]
Thanks a lot. I will mark this as closed!

**Comment by monadiconion** [comment]
As a follow-up to the issue, @sschmidTU may I ask if there's any option to enable "equal bar width", i.e. a **44 bar with full rest** should occupy same bar width as a **44 bar with 4 quarter notes**.

**Comment by sschmidTU** [comment]
No, not currently. Vexflow does the layout. Also, we don't know how long a 4/4 bar may be when layouted, so setting it to the same width as a full rest measure could either lead to extreme squeezing or a huge full rest bar.
I suppose we could offer that option if the user wants to take that compromise.
