### ISSUE TITLE
How to get fingering of specific note ?

### ISSUE THREAD

**Issue by conde2** [opensheetmusicdisplay/opensheetmusicdisplay#889]
Hello guys, I'm trying to get some information of the notes, but I'm having problem to define which fingering is for each note and what is the bpm also.

What I have so far:

```
    const readNotes = this.osmd.cursor.NotesUnderCursor();
    for (const note of readNotes) {
      console.log(note);
      if (note.halfTone > 0) {
        var finger: string;

        note.ParentVoiceEntry.TechnicalInstructions.forEach(instruction => {
          if (instruction.type == TechnicalInstructionType.Fingering) {
            finger = instruction.value;
            console.log(finger);
          }
        })

        const noteInfo = {
          "note": note.halfTone + 12, // see issue #224
          "hand": note.ParentStaff.Id, // staff
          "finger": finger,
          "bpm": 60,
        };
      }

    }

```

The problem is note.ParentVoiceEntry.TechnicalInstructions contains all the fingerings for the Staff and I cant match them with the correct note.

**Comment by conde2** [comment]
I managed it doing this, but i think I`m doing the difficult way, not sure.

```
    const voicesUnderCursor = this.osmd.cursor.VoicesUnderCursor();
    const notesInfo = [];
    for (const voice of voicesUnderCursor) {
      console.log(voice);
      let satrtNotes = this.notesToSend.length;
      voice.Notes.forEach( note => {
        console.log(note);
        this.notesInfo.push({
          note: note.halfTone + 12, // see issue #224
          hand: note.ParentStaff.Id, // staff
          time: 0,
        });
      });

      let count = voice.Notes.length;
      voice.TechnicalInstructions.forEach(instruction => {
        if (instruction.type == TechnicalInstructionType.Fingering) {
          if (this.notesInfo[satrtNotes] != null) {
            this.notesInfo[satrtNotes].finger = Number.parseInt(instruction.value);;
          }
          count--;
          satrtNotes++;
        }
      })
    }
``

**Comment by sschmidTU** [comment]
I pushed a fix to develop that makes this easier.
A Note now has Note.Fingering, and voiceEntry.TechnicalInstructions[i] has a sourceNote if it's a fingering.

I also fixed a bug where the fingering was assigned to the wrong note, because the middle note didn't have a fingering:
![image](https://user-images.githubusercontent.com/33069673/94352002-d461bb80-005f-11eb-9b39-f423168624d7.png)

This is how it's supposed to look:
![image](https://user-images.githubusercontent.com/33069673/94352008-e6dbf500-005f-11eb-8a8e-6ef3d2fd5533.png)

sample:
[chord_fingering.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5287501/chord_fingering.zip)

This shows how you can easily get each note's fingering now:
![image](https://user-images.githubusercontent.com/33069673/94351996-bdbb6480-005f-11eb-814c-b71f47023123.png)

Saving the fingering per note made me notice that bug and made solving it easier, thanks for the suggestion!

**Comment by sschmidTU** [comment]
@conde2 for BPM, each measure has a `measure.TempoInBPM`, e.g.:
```js
osmd.cursor.NotesUnderCursor()[0].sourceMeasure.TempoInBPM
```

**Comment by conde2** [comment]
Thank you !
That makes it alot easier, great additiion.
