### ISSUE TITLE
Rendering pickup bar

### ISSUE THREAD

**Issue by monadiconion** [opensheetmusicdisplay/opensheetmusicdisplay#890]
Is there any setting where the pickup bar (score typed in NoteFlight) can be rendered without the additional time signature (44)?

Original score on NoteFlight
![image](https://user-images.githubusercontent.com/70841126/94432929-173fa280-01ca-11eb-8305-1ef72af83fc8.png)

OSMD
![image](https://user-images.githubusercontent.com/70841126/94432820-e8293100-01c9-11eb-92d3-b8ebcfb6a8d9.png)

**Comment by monadiconion** [comment]
@sschmidTU Has the fix for this been planned? Or any relevant code section you could point me to so I can look into?

**Comment by sschmidTU** [comment]
Can you share a sample musicxml?
This doesn't happen for our samples:
Mozart - An Chloe:
![image](https://user-images.githubusercontent.com/33069673/97002409-3c5dd180-153a-11eb-89fe-4e14b4e6fa64.png)
Mozart - Das Veilchen:
![image](https://user-images.githubusercontent.com/33069673/97002452-4e3f7480-153a-11eb-8931-50250c800e35.png)

I think this code at line 520 in MusicSystemBuilder should fix it:
```ts
if (currentRhythm !== undefined && currentRhythm.PrintObject && this.rules.RenderTimeSignatures) {
    // only add rhythm at the beginning if no pickup measure
    if (measure.parentSourceMeasure.Duration === measure.parentSourceMeasure.ActiveTimeSignature) {
        measure.addRhythmAtBegin(currentRhythm);
        rhythmAdded = true;
    }
}
```

**Comment by sschmidTU** [comment]
@monadiconion Can you share a MusicXML sample? I can't reproduce this with my samples, so I don't want to commit a fix that I can't test.

**Comment by monadiconion** [comment]
@sschmidTU Sure. There you go. This is a file exported from NoteFlight.

[we_wish.xml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5470419/we_wish.xml.zip)

**Comment by sschmidTU** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/33069673/98152144-8a2af000-1ed1-11eb-8ccb-ddfa402a7887.png)

I would actually say this XML is written incorrectly, because it does give the rhythm both in the pickup measure and in the following measure, even with `PrintObject="true"` in both, so we showed what the XML said to show.
But given that many MusicXML exporters in many music programs are notoriously bad, and it doesn't hurt to prevent this from happening (it never makes sense to give the rhythm twice including in the pickup measure, because the pickup has no full rhythm), there's no reason not to.
