### ISSUE TITLE
How do i draw a single note (without staff) at a given positon?

### ISSUE THREAD

**Issue by Luci404** [opensheetmusicdisplay/opensheetmusicdisplay#900]
I want to draw and remove notes on top of the existing sheet, how is this done?

**Comment by conde2** [comment]
For single note you can use VexFlow, try if you search it, you will find a lot of examples on how to do it.
OSMD is more suitable for scores in musicxml  format.

Although you can try creating a musicxml file that only contains one note information and pass this xml to you OSMD instance and then draw it.

**Comment by Luci404** [comment]
I have been looking around but i can't figure out how i draw to an already existing sheet?

**Comment by conde2** [comment]
As far as I know you can't, you can change the XML using javascript and then rerender or use VexFlow and draw above the sheet.

**Comment by Luci404** [comment]
> As far as I know you can't, you can change the XML using javascript and then rerender or use VexFlow and draw above the sheet.
You can, if it is build with VexFlow you can... It just must be hidden away somewhere. @sschmidTU I might need some help from someone who knows the way this is build here? I just need a way to add/remove graphical notes - they are meant as a way of showing what the user is currently playing in my app so they are purely graphical?

**Comment by sschmidTU** [comment]
@Luci404 unfortunately it's not easy to "just" draw extra notes without rerendering the sheet. OSMD is a MusicXML rendering engine, not an interactive music notation program. The problem is that Vexflow does the layout, and if you want to add notes in Vexflow, you need to have it format the measure again.

As conde2 said, the best way is to add the notes to the XML or to OSMD's sheet model, and render again.
To add notes to the OSMD sheet model, it's probably best to create a new voice and add notes like in OSME:
https://github.com/opensheetmusicdisplay/osme/blob/develop/src/OSME/SourceGenerator/ExampleSourceGenerator.ts

We might offer a method to re-render individual measures in future, to increase performance for cases like this.

**Comment by Luci404** [comment]
> might offer a method to re-render individual measures in future, to increase performance for cases like this

How would I go about doing this then? Generate a sheet with the same time signatures and render it on top of the existing one? How can I make this fast enough? Can I somehow only render nodes and skip rendering all the other stuff for speed?

**Comment by sschmidTU** [comment]
No, you would add the notes to the measure, then re-render it. You can add change the color and transparency of notes etc., so there shouldn't be anything basic you can't do by re-rendering.
We could try to improve performance by only re-rendering notes, yes, though then we'd have to selectively call the render method of Vexflow elements (like Stavenote) instead of letting the measure render.
But maybe rendering one measure is fast enough anyways.

**Comment by sschmidTU** [comment]
By the way, as i said, this is something that WE (OSMD) would offer, so if you're talking about what you can do, you'll have to do it in OSMD.

**Comment by Luci404** [comment]
> You can add change the color and transparency of notes etc., so there shouldn't be anything basic you can't do by re-rendering

Yeah, so how do i add a note without regenerating the XML?

**Comment by sschmidTU** [comment]
I answered that already. It's not easy.
> the best way is to add the notes to the XML or to OSMD's sheet model, and render again.
To add notes to the OSMD sheet model, it's probably best to create a new voice and add notes like in OSME:
https://github.com/opensheetmusicdisplay/osme/blob/develop/src/OSME/SourceGenerator/ExampleSourceGenerator.ts
