### ISSUE TITLE
File does not render on demo

### ISSUE THREAD

**Issue by infojunkie** [opensheetmusicdisplay/opensheetmusicdisplay#905]
The attached file [comma_pump_min_0.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5404385/comma_pump_min_0.zip) is a valid MusicXML file:

```
$ xmllint --schema ~/src/music/musicxml-3.1/schema/musicxml.xsd comma_pump_min_0.xml --noout
comma_pump_min_0.xml validates
```
(after [fixing an issue with the MusicXML XSD](https://github.com/w3c/musicxml/pull/284))

When I drop it at https://opensheetmusicdisplay.github.io/demo/, I get the following JS console log:
```
[OSMD] Loaded sheet Comma-Pump successfully.
Error loading sheet: TypeError: Cannot read property 'parent' of undefined
StackTrace: 
TypeError: Cannot read property 'parent' of undefined
    at Function.copy (demo.min.js:1)
    at e.MusicSystemBuilder.initializeActiveInstructions (demo.min.js:1)
    at e.MusicSystemBuilder.initialize (demo.min.js:1)
    at w.calculateMusicSystems (demo.min.js:1)
    at w.calculate (demo.min.js:1)
    at e.GraphicalMusicSheet.reCalculate (demo.min.js:1)
    at _.render (demo.min.js:1)
    at demo.min.js:188
```

**Comment by sschmidTU** [comment]
Well, Musescore does say the xml is corrupt as well. Interesting that it passes the MusicXML scheme.
I fixed some errors to do with not giving any clef, key signature or tempo, and now it renders, is that what it's supposed to look like?
<img src="https://user-images.githubusercontent.com/33069673/96753220-d48b7780-13cf-11eb-8b6d-64246b9534e4.png" height="150">

i did set `osmd.EngravingRules.RenderPartNames = false`, otherwise it shows the random part names given in the XML:
<img src="https://user-images.githubusercontent.com/33069673/96753463-30ee9700-13d0-11eb-9c1b-b381e15e3588.png" height="150">

MuseScore renders two measures somehow, even though the xml only gives one.
<img src="https://user-images.githubusercontent.com/33069673/96753781-a0fd1d00-13d0-11eb-8d29-7fa4ca41df28.png" height="150">

**Comment by sschmidTU** [comment]
Not rendering the time signature if none is given would be another issue.
For now you can hide it yourself via this, before render():
`osmd.sheet.sourceMeasures[0].firstInstructionsStaffEntries[0].instructions[2].PrintObject = false`
or hide all time signatures like this:
`osmd.setOptions({drawTimeSignatures: false})`
(see #793)

**Comment by infojunkie** [comment]
Thanks, that's great. It's up to you of course to choose how to handle ambiguous conditions such as a missing measure or time signature - assuming the MusicXML spec is not explicit about those.
