### ISSUE TITLE
New system directive not handled

### ISSUE THREAD

**Issue by infojunkie** [opensheetmusicdisplay/opensheetmusicdisplay#918]
As per [the attached file](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5604977/bolivia.zip), the measure directive `<print new-system="yes"/>` is not handled. Would be great to process it :pray:

**Comment by infojunkie** [comment]
For reference, [this is MuseScore renders the same file](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5604988/bolivia.pdf).

**Comment by sschmidTU** [comment]
You can respect system and page breaks:
```js
osmd.setOptions({
  newSystemFromXML: true,
  newPageFromXML: true
}
```

The reason OSMD doesn't do this by default is because many MusicXMLs have excessive, senseless system breaks, which nullify OSMD's layout capabilities.
Usually System breaks are included as the music program it was written in would render it.
But if OSMD already breaks after 5 measures, and there's a system break in measure 6 in the MusicXML,
you'd get a system with a single measure (6).
