### ISSUE TITLE
Performance: optimize SkyBottomLineCalculator

### ISSUE THREAD

**Issue by sschmidTU** [opensheetmusicdisplay/opensheetmusicdisplay#937]
For very large scores, OSMD can take a lot of time to render (e.g. Actor Prelude, our largest sample in the demo).

It looks like `SkyBottomLineCalculator.calculateLines()` takes the bulk of the time (~96.1% of `render()`), and `ctx.getImageData()` (Vexflow) a large part of that (~57%).

![image](https://user-images.githubusercontent.com/33069673/104622554-b614df80-5691-11eb-835c-f2d8ddc26da4.png)

Maybe we can optimize something here - either `getImageData()` in Vexflow or the rest of the `calculateLines()` function in SkyBottomLineCalculator.

@bneumann maybe you could help out here a bit as well, since you know the SkyBottomLineCalculator pretty well.

(of course, the goal is not to make the Actor Prelude sample render extremely fast, it's an extremely large sample that's unrealistic for most uses.
also note that the 17 seconds are on a pretty old dual core cpu from 2012, 2.9Ghz )

**Comment by bneumann** [comment]
Yes that part's always been a problem. What we do here is, that we prerender all measures off-canvas and check for the boundaries. @matt-uib and I were discussing that methodology a lot. The alternative would be to properly implement all bounding boxes (which were not done at all at the time of the implementation of the skybottomcalculator) and only do some math over those boxes. 
This would have 2 benefits and 1 drawback:
Pro:
- Faster
- Can be done in a backround job where you don't have a canvas
Con:
- Precision loss because we for instance beams might get a rectangular box while they are actually more triangular shaped.

Anyways, I will look into it if I find some time. Been quite blocked due to Corona :(

**Comment by infojunkie** [comment]
I wonder if using an existing collision library that's used in game engines would help here. They're typically optimized and well-tested. [Here's an example of real-time collision detection with lots of non-rectangular objects](https://sinova.github.io/Collisions/demo/?stress).

**Comment by sschmidTU** [comment]
I think the problem is getting the bounding boxes in the first place, because vexflow doesn't always give them, so we have to check where it draws things. Checking for collisions is the lesser problem.

**Comment by sschmidTU** [comment]
Closing for now. There was a 30-60% performance improvement in #1158 by computing skylines in batch and/or via WebGL, depending which is faster. (released in OSMD 1.5.0)
We can reopen or open another issue if necessary.

**Comment by sschmidTU** [comment]
Performance improved again by ~1.8x - see #1681
